### ISSUE TITLE
Refinement of search results

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1005]
If you search for "TVET" you currently receive 9 hits:
https://oerworldmap.org/resource/?q=TVET

I checked them and it seems to me that most results are shown, because they include the word "TV".
As far as I can see it, only the Bundesinstitut für Berufsbildung explicitly referts to "TVET" in a tag. Interesting is that it  appears as the third result - I would have expected it to appear first. 

Also interesting: If I look for "tvet" in small letters, the Bundesinstitut für Berufsbildung disappears, the other results still remain. I would guess that searching for tags at the moment is case sensitive, while searching in other fields is not.

@philboeselager could you please have a look at this?

**Comment by trugwaldsaenger** [comment]
This ticket starts, where #994 ends

**Comment by literarymachine** [comment]
> As far as I can see it, only the Bundesinstitut für Berufsbildung explicitly referts to "TVET" in a tag. Interesting is that it appears as the third result - I would have expected it to appear first.

This is because of the field boost settings; we can simply set a higher one for [`keywords`](https://github.com/hbz/oerworldmap/blob/master/conf/search.conf#L52).

> I would guess that searching for tags at the moment is case sensitive, while searching in other fields is not.

Yes, tags are case sensitive; see also #793.

**Comment by philboeselager** [comment]
> > As far as I can see it, only the Bundesinstitut für Berufsbildung explicitly referts to "TVET" in a tag. Interesting is that it appears as the third result - I would have expected it to appear first.

> This is because of the field boost settings; we can simply set a higher one for keywords.

Yes, I'm going to check this out. Nonetheless, we've got to be aware of that there is no such thing as perfect working ranking for every case. I'm going to try to implement this case as a unit test so that we can always keep track of the behaviour.

**Comment by karindr** [comment]
The first times I was doing searches for words after keywords and descriptions were included I was surprised of the increased number of search results with often not much connection to the search term. I think this is especially noticeable for short search term. But doing some more searches I appreciate the new way because you are really able to find every entry related. That there are some irrelevant results is like searching on google, you will not look at the last results.

For getting lists with no such “wrong” results you can still use the filters for keywords.

And yes I also think keywords should be given a greater weight.

**Comment by philboeselager** [comment]
Implemented in https://github.com/hbz/oerworldmap/commit/ce7442db91e2d6242f59f1a8e070af4143f7be0b . It looks a bit strange that we need a higher boost value for `keywords` (11) than for `name` (9). That should be OK because `name` is stored 3 times, each with a boost of 9.

**Comment by literarymachine** [comment]
Fixed in  ce7442d, closing.
