### ISSUE TITLE
Disable automatic truncation

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#1026]
Currently, search terms are automatically truncated, see e.g. https://oerworldmap.org/resource/?q=hochschu. While this is useful when looking up entities in an editing form, I don't think this is the best behaviour for the map's standard search. I propose removing it but enabling truncation with asterisk.

**Comment by literarymachine** [comment]
> I propose removing it but enabling truncation with asterisk.

Please verify with @karindr as this is the exact opposite of what was requested in #651.

**Comment by acka47** [comment]
Good hint, @literarymachine, I remembered something like this. Though I think this is not as important as #1025 I think we could reduce the number for some searches significantly. The question is whether we would gain more comfort than we would lose...

Another option is to show suggestions (like in Google) or the whole result list as soon as people start typing and adjust this with every new character typed in.

**Comment by philboeselager** [comment]
The conflict of this issue and #651 shows that it is important to 

1. commit on a desired search functionality so that everyone involved knows about the why's and
2. document the commitment (in a light style) so that everyone can check in case of a future issue

Because especially with search algorithms and rankings, you will run into conflicts again and again. We will be losing time if we always try to re-tune in small steps.

@acka47 and @trugwaldsaenger: I suppose you might have done some of this commitment already in the course of your discussions for #1024. If you could check with @karindr in general that should help a lot.

**Comment by literarymachine** [comment]
Here is another comment where

**Comment by acka47** [comment]
I understand, obviously @karindr's expectations regarding the search that require fuzzy search interfere with @trugwaldsaenger's wish to offer a result list that is rather short. Karin & Jan, as you are sharing the same office you should discuss this before we open more conflicting issues.

**Comment by acka47** [comment]
We decided at the team meeting to actually turn it off and implement #1123 as substitute.

**Comment by literarymachine** [comment]
Fixed in #1179.
