### ISSUE TITLE
List of 1239 entries shown when clicking on any number

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1033]
I agree to  @literarymachine  that as for automatically enabling it when zooming into to the map etc, we have to put some more thought into this as this can be very confusing if enabled / disabled automatically. (See #979) 

But in the moment there is a rest of the old behavior shown that is really disturbing: When you look at the map and click on a number the map zooms in and a list is shown. Because the list is no longer restricted to the shown part of the map it shows all 1239 entries of the map. My suggestion would be not to display any list until the maps stops zooming in when you click on a number. When you finally have one of these unresolvable numbers there should be a list of these entries. As visitor I would understand this behavior but I don’t know it if it is complicated to realise.

**Comment by literarymachine** [comment]
>  When you look at the map and click on a number the map zooms in and a list is shown.

It is true that this is new when: before, clicking on a cluster when the map is full screen did not automatically reveal the list. But if you have enabled e.g. the `Organization` filter manually, the list always has - as it is now - displayed all hits, regardless of the map zoom:

![screenshot from 2017-01-18 13-58-24](https://cloud.githubusercontent.com/assets/149825/22064959/37fdc46e-dd86-11e6-9b09-e1c995ff51b6.png)

This is the exact reason, why "Search as I move the map" was enabled by default: to synchronize what you see on the map and what you see in the list. The only problem with that is that things that do not have a location are not shown until "Search as I move the map" is disabled, which is why after your feedback we disabled it by default again.

>  When you finally have one of these unresolvable numbers there should be a list of these entries.

We can do this for now, but then again when is the list "unrestricted" automatically again? At last weeks workshop, we have discussed an approach that completely decouples the question of restricting the list to the map extent and the problem of unresolvable clusters. In case a cluster cannot be further resolved, the cluster displays a popup-list from which you can *directly* select the resource you want. I would suggest to give it a go!

**Comment by karindr** [comment]
If you have a solution for the unresolvable clusters that doesn't use the list in the right column it will be better. I agree, go on with it.

But concerning the list of all results shown after clicking on a number: I suggest to turn this behaviour off. It is not the same as a having chosen a filter. If you have chosen a filter you made a selection so there is a  subset of the entries shown and not the whole list. This makes a difference: working with the filters means selecting from a list.

**Comment by literarymachine** [comment]
> If you have a solution for the unresolvable clusters that doesn't use the list in the right column it will be better. I agree, go on with it.

On https://beta.oerworldmap.org/

> But concerning the list of all results shown after clicking on a number: I suggest to turn this behaviour off.

Also on https://beta.oerworldmap.org/

**Comment by karindr** [comment]
The list isn't shown any more that is ok.

The behaviour for unresolvable clusters is sometimes like shown in the picture above and then works well. But for example for the hbz there is a drop down you can't click on.
![image](https://cloud.githubusercontent.com/assets/18674205/22198595/7b6104e4-e157-11e6-8cd7-72555d70e1c2.png)

**Comment by literarymachine** [comment]
> But for example for the hbz there is a drop down you can't click on.

See https://github.com/hbz/oerworldmap/issues/582#issuecomment-274441243 for this case.
