### ISSUE TITLE
Deleted entries are still found

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1042]
![image](https://cloud.githubusercontent.com/assets/18674205/22195898/8f5a305e-e14a-11e6-8186-bba599b76eb8.png)
I deleted 6 entries a visitor made by mistake (I will ask him what the problem was also). Bu two of them are still in the list when searching. Does this happen because of a delay in indexing? An 404 error is shown when clicking on them.

**Comment by acka47** [comment]
By now, there is only one left in the search results, see https://oerworldmap.org/resource/?q=leitfaden. So, yes it must have been the asynchronous indexing. The 404 is shown because single resource are loaded from the triple store and not from the search engine. Please close the issue if you are satisfied with the answer.

**Comment by karindr** [comment]
I assume we have to live with this delay? I tried a lot of times to get rid of the deleted entries by reloading the search result. It felt like 5 minutes or so-

**Comment by literarymachine** [comment]
> I assume we have to live with this delay? I tried a lot of times to get rid of the deleted entries by reloading the search result. It felt like 5 minutes or so-

Depending on how interlinked an entry is, and on how many *previous* indexing jobs are in the queue, it might take this long, yes. I have opened #1044 to investigate reducing indexing time.

**Comment by karindr** [comment]
+1
