### ISSUE TITLE
Country view of Russia doesn't show the whole country

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1046]
Even the pins are not shown this way:
![image](https://cloud.githubusercontent.com/assets/18674205/22246144/a41445a4-e233-11e6-9eb1-2ffd5414a1e2.png)

**Comment by literarymachine** [comment]
Interesting, on my local machine it is displayed properly:

![screenshot from 2017-01-30 13 41 20](https://cloud.githubusercontent.com/assets/149825/22423453/ff208170-e6f1-11e6-88ca-8370efd21549.png)

But on production I can reproduce the issue. @j0hj0h do you have any idea why this could be?

**Comment by formimkontext** [comment]
I’m not sure if this is the right ticket, but on my 21'' display the map isn’t shown completely when entering the site. 
this is firefox:
![bildschirmfoto 2017-02-14 um 13 48 25](https://cloud.githubusercontent.com/assets/15141949/22929496/57ec95c0-f2bc-11e6-800c-897d6a999963.png)

this is safari:
![bildschirmfoto 2017-02-14 um 13 50 54](https://cloud.githubusercontent.com/assets/15141949/22930829/7b5ab932-f2c2-11e6-8a4b-1b2ac5cfefb0.png)

**Comment by karindr** [comment]
Same for me on chrome:
![image](https://cloud.githubusercontent.com/assets/18674205/22970083/15bc2f0c-f371-11e6-89c5-bf9cd1aa8536.png)
And on firefox:
![image](https://cloud.githubusercontent.com/assets/18674205/22970101/2a62efd6-f371-11e6-8aca-7537fb3b10f4.png)

**Comment by karindr** [comment]
The Russia phenomenon on firefox is the same as above:
![image](https://cloud.githubusercontent.com/assets/18674205/22970169/6f5ff93a-f371-11e6-9d4e-490044cd903c.png)

**Comment by j0hj0h** [comment]
**Concerning Russia:** For me this only happens when I click on Russia while having the page in the initial state, where no filters are set and the index column is floating (e.g. at URL: https://oerworldmap.org). When I reload or click on Russia from any other previous state, the zoom level is set correctly. I can't find the reason so far. Russia is the only country, where it happens. (@literarymachine: Yes, we override the boundaries of Russia, but we also do that for US and FR for example, and they work as expected.) I invested 2 hours now. Do you think I should go on? Switching to the other mapping library, will most likely solve the problem, so I'd suggest, to skip this issue for now.

**... and the world:** Well, this is a question of the aspect ratio of your viewport. If it is "landscape-ish", we basically have to decide between showing the world repetitively or cutting a bit on top and bottom. As far as I remember there was the wish from @trugwaldsaenger , to avoid the repetition as far as possible. But if we agree, that priority should be on "showing the full height" – no problem. It's just a parameter. So let me know.
Another point here: With the current mapping library, we can only zoom to certain steps, not in between. This increases the problem. When we switch, we can choose fine grained zoom levels.

**Comment by formimkontext** [comment]
> As far as I remember there was the wish from @trugwaldsaenger , to avoid the repetition as far as possible. But if we agree, that priority should be on "showing the full height" – no problem. 

I prefer to show the whole world rather repetively than to cut off parts of south america and australia. However, i think we should push the map a bit upwards, as we don’t have any resources located at the north pole but in south america, australia and new zealand.

**Comment by karindr** [comment]
I agree to @formimkontext, It would be good to push the map upwards!

**Comment by philboeselager** [comment]
> I agree to @formimkontext, It would be good to push the map upwards!

+1

**Comment by literarymachine** [comment]
Fixed during rewrite.
