### ISSUE TITLE
Finding events by entering city or country in the search field

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1079]
Often you don’t know the exact name but the place of a conference so it would be good to be able to find the events for a city or a country by using the search.
For London for example the two events being located in London are listed in the middle and as last:
https://oerworldmap.org/resource/?q=London&filter.about.%40type=Event
And for Malta it is 8 of 29:
https://oerworldmap.org/resource/?q=malta&filter.about.%40type=Event
https://oerworldmap.org/resource/?q=&filter.about.%40type=Event#urn:uuid:6c9b4e67-290e-468f-af66-a17bb4f2005e
It would be useful especially for events to put more weight on the location for the searching.
(Yes, I know that for countries you also can use the country filter.)

**Comment by trugwaldsaenger** [comment]
+1

**Comment by literarymachine** [comment]
Makes sense, but it is more than the weight that has to be adjusted, at least in case of countries. These are represented by their [two letter country codes](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) in the database and only expanded for display in the UI to their full name (depending on the requested language, e.g. `Germany` or `Deutschland`). So in order to allow to search for country names, we have to add them to the index in the different languages.

For city names, this problem does not exist because they are simply input by the end users. That being said, I don't really understand where most of the results for 

> https://oerworldmap.org/resource/?q=London&filter.about.%40type=Event

currently come from, because they don't contain `London`. @philboeselager any idea?

**Comment by philboeselager** [comment]
> where most of the results for https://oerworldmap.org/resource/?q=London&filter.about.%40type=Event currently come from, because they don't contain London. @philboeselager any idea?

No, not really. There is no referred / indirect data containing "London", as far as I can see.

My assumption is that the results come from word similarities. The [13th Annual Open Education Conference](https://oerworldmap.org/resource/urn:uuid:1a9be075-5a7f-4321-b991-4f3af7ec4dd4) occurs to be a hit for whatever you type, be it "London", "Paris", "Cape Town" or "Schokolade". The reason might be that its description contains a large set of words, being tokenized into "almost every" combination of letters and therefore providing a huge number of possible hits.

As a solution, we should try `"variations": { "search_analyzer": "standard", [...] }` (instead of `"title_analyzer"` for `description` (as well as all other fields). I'm going to check that.

**Comment by philboeselager** [comment]
To be a able to search for countries, I was thinking about the following.

- Setup an additional, Elasticsearch index, named "countries": ISO2 codes will serve as `id` for each entry, country names in full for as many as possible languages are listed.
- Each frontend query runs towards this additional index. In case of a hit, the country's ISO2 code is returned.
- The query term then gets enriched with the country information returned and is send towards our main index.

The downside might be the additional response duration for user queries. Given the quite small size of the country index, I think this lag should be unnoticeable.

Should we have a try or do you think that the benefit would not justify the effort?

**Comment by literarymachine** [comment]
Actually https://www.elastic.co/guide/en/elasticsearch/guide/current/synonyms.html might be a better approach in this case!

**Comment by philboeselager** [comment]
+1 for synonyms!

**Comment by literarymachine** [comment]
Fixed and deployed to production, see e.g. https://oerworldmap.org/resource/?q=London&filter.about.%40type=Event
