### ISSUE TITLE
Introducing splash screen

### ISSUE THREAD

**Issue by formimkontext** [hbz/oerworldmap#1086]
At our meeting in january we thought about introducing a splash screen to the world map. Its content would be the information which is shown in the welcome window right now, without distracting elements like e.g. the search bar and the map itself. The splash screen would disappear by entering the map and should not be shown again. This is how it could look like:   

![20170214-oerwm-splashscreen](https://cloud.githubusercontent.com/assets/15141949/22929008/95a11aec-f2b9-11e6-97ec-8ea73855bf10.png)

**Comment by karindr** [comment]
For people working with the World Map more often it would be very important to come to the map by simply pressing the return button (or by clicking somewhere on the map). Otherwise it will be annoying to go with the mouse to the button every time.

In my opinion the blue could be more transparent so the World Map could be seen a bit better at the first look.

**Comment by formimkontext** [comment]
Initial draft of the future homepage / onepager instead of the splashscreen. The structure of content is based on the text document "New OER World Map Homepage" [https://docs.google.com/document/d/1kmDJdBMUBszRk2Fwk6NMECJ3LMIFGHKTzEIm_CDbATk/edit#heading=h.lg5joyvt9246](url). 

![20170629-oer-wm-startseite-3](https://user-images.githubusercontent.com/15141949/27696396-c873f0be-5cf1-11e7-8402-624486703374.png)

**Comment by karindr** [comment]
In general I like this onepager!

Some details may be discussed:

- shouldn't the "finding section" come before the "data enty"
- I think Join us/Log in/Not now is not very clear
- we now have 2 tetxs about the world map and two points where poeple should become editors. This may be better if it is straighter
- I like the three screenshots to ilustrate data editing!

**Comment by literarymachine** [comment]
> shouldn't the "finding section" come before the "data enty"

I would say so, too. But we stuck to the structure of the [Google Doc](https://docs.google.com/document/d/1kmDJdBMUBszRk2Fwk6NMECJ3LMIFGHKTzEIm_CDbATk/edit#heading=h.lg5joyvt9246) that @trugwaldsaenger and Susan prepared together.

> I think Join us/Log in/Not now is not very clear

We have investigated other networking sites such as https://www.facebook.com/, https://www.researchgate.net/, https://www.linkedin.com/ and https://trello.com/ and all of those present the options to `Join` or `Log in` on the first page (obviously only if you are not logged in yet). It seems to be a well established practice. Since you can also use the World Map without registering, we added the "Not now" option.

> I like the three screenshots to ilustrate data editing!

Excellent, @j0hj0h would like to add some more in other places. I think it is a great idea, too!

**Comment by j0hj0h** [comment]
In the process of creating this draft we reviewed some homepages of other platforms, like Researchgate, Trello, Xing, Linkedin and Facebook. Based on this and on my general attitude on how to introduce the OER Worldmap, I suggest three additions/shifts:

1. Prepend two paragraphs to the first "learn more" section: one saying what is OER and the other one saying what is it's benefit. I think we should give this some space! Even if "Newbies" aren't our primary target group, it's a pity, that they don't get some guidance when entering the page. I imagine three columns, where the current text is in the right one, the two paragraphs suggested here in the left and middle.
2. Change the wording of the "Adding and editing data" section towards describing more concrete possibilities and illustrate them with more screenshots. If we have a slider here, we would also be flexible to announce new features and visualize them. So instead of "editing data", I think we should name it less technical towards particular features seen from a user perspective (each illustrated with a screenshot). Imagine Researchgate would welcome you with "Adding data is easy!" ... It's not about adding data, if you are a user, it's about
   - "Setup a personal profile"
   - "Put your organization on the map"
   - "Announce an event"
   - "See upcoming events"
   - "Discover the OER movement in your country"
   - "Find services on a specific subject or grade level"
   - and so on ... (I don't say this list/wording is already perfect, but shows the direction I think it should take.)
3. I think the homepage could bare some namedropping e.g. a logo section, saying that the map is financed by Hewlett, created by HBZ/graph thinking, name the cooperation with the OU, potential regional cooperations like with DIPF and the link to the Unesco, if this has any official status. Everyone does this and it I think it's important to strike out the connection to prominent partners.

... I'll add my suggestions (also a quick draft for the two paragrahs from 1.) in the Google Doc as well.

**Comment by j0hj0h** [comment]
Talked with @trugwaldsaenger about suggestion 3. ...

Current official partners:
- Open University (Development Partner)
- Hewlett Foundation (Funder)
- HBZ (Provider)
- graphthinking (Provider)

Current Country Champions (Regional Partners):
- NDAL
- DIPF
- SURF
- Transferstelle für OER
- Kennisnet (Niederlande)
- KlasCement (Belgium)
- Centrum Cyfrowe Projekt (Polen)
- Unsesco Chairs
- BCOER Libariens
- Jozef Stefan Institute
- Lumen Learning

... https://oerworldmap.org/resource/?q=about.countryChampionFor:*

**Comment by j0hj0h** [comment]
@trugwaldsaenger will provide texts for the additional steps, suggested in 1.

@formimkontext and @j0hj0h will make suggestions for the slides suggested in 2.

**Comment by j0hj0h** [comment]
Rename link "Not now" to "Enter the map!"

**Comment by trugwaldsaenger** [comment]
Hi @j0hj0h, I updated the google doc and made a proposal for the wording mentioned in your comment above. I also pasted some earlier comments from Susan to the doc - for some points she proposes good alternative wordings.

**Comment by j0hj0h** [comment]
@literarymachine and me discussed a solution for the "Add to the map now" functionality in the intro section:

It will just link to the corresponding form to add the resource. In case this is loaded without being logged in there will be an info box at the top of the form, saying something like: "You are contributing without being logged in. The data you enter will be reviewed and most likely published within the next days. If you want to contribute directly, you can [login](https://oerworldmap.org/.login) or [register](https://oerworldmap.org/user/register)."
Sending the form will cause an email being send to @karindr, containing the JSON with all data that allows to recreate the form inputs somehow.

**Comment by formimkontext** [comment]
current draft for the landingpage. icons within the first section are not final, but we wanted to show an discuss the concept. 

i also made some suggestions (in german) for the texts of the contribution-section. i think we should follow a more narrative and / or asking approach in our communication. 

the layout and content of the menu / header-bar is not final. we should discuss this in another issue.

![20171103-desktop-welcome-splashscreen](https://user-images.githubusercontent.com/15141949/32386422-6fbfa678-c0c1-11e7-985e-ee12ae7d3f74.png)

**Comment by j0hj0h** [comment]
@trugwaldsaenger, I made a suggestion for the slides in [the google doc](https://docs.google.com/document/d/1kmDJdBMUBszRk2Fwk6NMECJ3LMIFGHKTzEIm_CDbATk) (section 4.)

**Comment by formimkontext** [comment]
update 2017.11.08.: 
* new example for highlighted features section
* added contact section

[20171108-desktop-welcome-splashscreen](https://user-images.githubusercontent.com/15141949/32558425-fe879e06-c4a4-11e7-8bc6-011876d71a33.png)

**Comment by karindr** [comment]
I'm not shure if the subscription to the mailinglist is so important that it should be the only part that is orange. Maybe there should be more parts in orange?

Didn't we agree that there should be a kind of news section for announcements and teasers from blog articles and so on?

**Comment by literarymachine** [comment]
> Didn't we agree that there should be a kind of news section for announcements and teasers from blog articles and so on?

I think this is currently meant to be a separate page, see https://github.com/hbz/oerworldmap/issues/1124#issuecomment-342612622

**Comment by formimkontext** [comment]
we said, that we could add new and remove current sections if needed. @karindr if you provide an example for content of the news section i will integrate that into the layout.

**Comment by karindr** [comment]
See #1124 . The teasers and pictures from the blogs homepage are good examples.

**Comment by trugwaldsaenger** [comment]
I guess other examples could be the highlighting of a new OER World Map entry: "Great new project by Open Osmosis" or our call for action: "Please help us to understand your needs better and fill out our survey, it will take you as little as 10 minutes!" So these examples are more like our tweeds.

**Comment by j0hj0h** [comment]
Updated draft by @formimkontext with news section ...
[20171215-desktop-welcome-splashscreen](https://user-images.githubusercontent.com/3071485/34043968-712d741a-e1a3-11e7-94ad-5d6a61bc15f6.png)

**Comment by dobladov** [comment]
Implemented closing issue

![screen shot 2018-10-10 at 17 19 39-fullpage](https://user-images.githubusercontent.com/1938043/46747068-b0f5a880-ccb0-11e8-817b-920fa759e16f.png)
