### ISSUE TITLE
Layout and behaviour of country view

### ISSUE THREAD

**Issue by formimkontext** [hbz/oerworldmap#1087]
New draft for the country view layout and behaviour as discussed at the meeting in january. By clicking on a country the map zooms in, showing the selected country highlighted while the rest of the map is darkened. Country view specific information (country champion and country reports) are shown at the top left. Since we don’t have that much space, my suggestion would be, to show all further and detailed information abut the country champion and country reports within the result list and / or single ressource column.  

You can exit the country view via the x or by cklicking at the map anywhere around the selected country. 

![20170214-oerwm-countrychampion-2](https://cloud.githubusercontent.com/assets/15141949/22936486/f589962a-f2d5-11e6-8b52-ca2e24377c50.png)

**Comment by literarymachine** [comment]
> Since we don’t have that much space, my suggestion would be, to show all further and detailed information abut the country champion and country reports within the result list and / or single ressource column.

I would prefer to keep the country information at the top left, maybe making the box expandable to overlap the map further if needed. Also, I would think a frame around the country information could be worth a try, maybe moving the x to close the country view there?

**Comment by karindr** [comment]
It is a good point to have a possibility to leave the country view. At the moment you sometimes get no results when searching because you are still in a country which you thought you left already. An x and the possibility to click on the background are both useful.

I agree with @literarymachine to keep the information in one place. In addition I think we should stay with displaying the picture of the country champions and the information on them. People should make contact, not see how may champions are there. 

We have a first country report now. This feature should become a prominent place too. And I like the statistic we have at the moment. I think it should be kept. If you want to see the list you have to scroll down anyway.

I like the blue background (because with more information on the map like Bundesländer, the rest becomes distracting).

**Comment by literarymachine** [comment]
> We have a first country report now.

Where can this be found?

> And I like the statistic we have at the moment. I think it should be kept.

Yes, definitely. But I would also move them to the top left, e.g. when expanding the box. The idea is that an "OER Country Map" has the same behavior in the columns as the World Map, with anything more specific shown in the top left.

**Comment by karindr** [comment]
The country report can be found only by the tag "country report" at the moment. It is here:
https://oerworldmap.org/resource/?q=&filter.about.%40type=Article&filter.about.keywords=country+report#urn:uuid:c466ee13-ad4c-4a1f-b5ee-6200c7f5a5b0

(By the way we got a new version today which is much longer, we also think about putting this long article into the blog and maybe link to the blog.)

**Comment by formimkontext** [comment]
in general, i think that we should concentrate on the most important information and don’t clutter the map with redundant information. 

all statistic information can be seen by switching to the statistic-view within the aggregation column. this is a feature we planed to implement a long time ago. maybe this could be the result list ordered by type as long as we are not able to provide any further or graphic statistics. until then, whoever wants to check how many organisations are listed in germany, only has to click the organisation-button in the filter section and will find the result below. 

i agree, that we could display the names of the country champions and country report within the country view box on the top left. but i dont think it is necessary to show their picture and e-mail-adress there. since all further information about the country champions aren’t that interesting to all user, i would prefer to link to their personal profile. both country champions and country reports are shown within the result list and can be easily found by using the filter.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/country/de. Apart from UI changes, this enables using the usual filters in context of a specific country, e.g.

https://beta.oerworldmap.org/country/DE?q=&filter.about.%40type=Service&filter.about.about.%40id=https%3A%2F%2Fw3id.org%2Fclass%2Fesc%2Fn08

which is important for our integration with OERinfo.

**Comment by karindr** [comment]
Great with the new filter possibilities!

There are some bugs in the list of the Bundesländer, some are in German and in English, some are more than one time in the list. One is withour name, one is DE.
![image](https://user-images.githubusercontent.com/18674205/28356934-058eb6e6-6c6a-11e7-9b3b-2e0298bd92c8.png)

**Comment by literarymachine** [comment]
> There are some bugs in the list of the Bundesländer, some are in German and in English, some are more than one time in the list.

Yes indeed, but this is a bug in our data. Some legacy data contains the name of the Bundesland instead of the ISO-code. I talked to @trugwaldsaenger about this, the entries causing this can be found [here](bd320dc3bb847e2b9902141369f5c2607f19b458). These can be fixed by opening the editing template and pressing publish, the region code will then automatically be updated from the mini map. We should probably do this on production only, but I have to deploy a small fix for `DE.BB` ("Brandenburg") before.

**Comment by karindr** [comment]
All other features I looked at seems to work pretty well.

I would like it better if the country was shown bigger (see my screenshot above).

The coulour of the chosen country is always the same shade of green. Is this intentional? In the draft there was the little heat map "Legende".

**Comment by literarymachine** [comment]
> I would like it better if the country was shown bigger (see my screenshot above).

On my screen, the country cannot be bigger without partially being off screen.

> The coulour of the chosen country is always the same shade of green. Is this intentional? In the draft there was the little heat map "Legende".

Yes, this is intentional. The legend actually only makes sense when comparing countries or as soon as the regions are color coded.

**Comment by literarymachine** [comment]
>  We should probably do this on production only, but I have to deploy a small fix for DE.BB ("Brandenburg") before.

The fix is deployed, in order to fix the data, [these](https://oerworldmap.org/sparql/query?q=SELECT+%3Fs+WHERE+%7B%0D%0A++%3Fs+%3Chttp%3A%2F%2Fschema.org%2Flocation%3E+%3Fl+.%0D%0A++%3Fl+%3Chttp%3A%2F%2Fschema.org%2Fgeo%3E+%3Fg+.%0D%0A++%3Fg+%3Chttp%3A%2F%2Fschema.org%2Flat%3E+%3Flat+.%0D%0A++%3Fg+%3Chttp%3A%2F%2Fschema.org%2Flon%3E+%3Flon+.%0D%0A++%3Fl+%3Chttp%3A%2F%2Fschema.org%2Faddress%3E+%3Fa+.%0D%0A++%3Fa+%3Chttp%3A%2F%2Fschema.org%2FaddressCountry%3E+%22DE%22+.%0D%0A++%3Fa+%3Chttp%3A%2F%2Fschema.org%2FaddressRegion%3E+%3Fr+.%0D%0A++FILTER+%28%21regex%28%3Fr%2C+%22DE.*%22%2C%22i%22%29%29+.+%0D%0A%7D) entries have to be fixed by opening and saving them in the input template. @karindr can you do that? As soon as the data is fixed, #1087 can be deployed.

**Comment by karindr** [comment]
I'll start doiing this.

**Comment by karindr** [comment]
I wasn't finished with this list, but you did it in another way, I assume.

**Comment by literarymachine** [comment]
> I wasn't finished with this list, but you did it in another way, I assume.

Nope, I opened each one and saved yesterday because I wanted to deploy the new country view. Unfortunately there is more trouble with legacy data that I still have to investigate so in the end I did not deploy yet.

**Comment by karindr** [comment]
Than  thank you. I had it on my list to finish it yesterday  but forgot about the downtime.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/country/de

**Comment by literarymachine** [comment]
The "region" filter in the country view is excluding any invalid region-codes. We still have some [invalid data](https://oerworldmap.org/sparql/query?q=SELECT+%3Fs+WHERE+%7B%0D%0A++%3Fs+%3Chttp%3A%2F%2Fschema.org%2Flocation%3E+%3Fl+.%0D%0A++%3Fl+%3Chttp%3A%2F%2Fschema.org%2Faddress%3E+%3Fa+.%0D%0A++%3Fa+%3Chttp%3A%2F%2Fschema.org%2FaddressRegion%3E+%3Fr+.%0D%0A++FILTER+%28%21regex%28%3Fr%2C+%22..%5C%5C.%22%2C%22i%22%29%29+.+%0D%0A%7D) in there but this should not stop us from deploying the new country view in time for the congress. What do you think, @trugwaldsaenger?
