### ISSUE TITLE
Import iCalendar events

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1106]
Provided a URL of an iCalendar file, the events contained within that file should be imported as `Event`s into the OER World Map.

**Comment by philboeselager** [comment]
Sounds good. Just to make sure: we would add other ways to import iCal events, too, wouldn't we? (For example file upload.)

**Comment by literarymachine** [comment]
>  Just to make sure: we would add other ways to import iCal events, too, wouldn't we? (For example file upload.)

Hadn't thought of that yet, but yes!

**Comment by literarymachine** [comment]
A good first use case is the import of the Year of Open events:

https://calendar.google.com/calendar/ical/ocwconsortium.org_efbnbs0r0lbvualuto9kggtqa4%40group.calendar.google.com/public/basic.ics

**Comment by philboeselager** [comment]
I've implemented a Mapzen autocompletion, see [latest commits](https://github.com/hbz/oerworldmap/commits/1106-importICalEventsViaPython). It focusses on the geo coordinates, if the latter is applicable.

Still, the results can be wrong, especially when the targetted location is not comprised within the Mapzen data and therefore can not be properly returned.

@literarymachine How would we deal with that?

**Comment by acka47** [comment]
Another use case, I referred to in #1152 is the iCal file of the [March OpenCon community call](https://www.addevent.com/create/?service=ICAL&dstart=29-03-2017%2012%3A00%3A00&dend=29-03-2017%2013%3A00%3A00&dzone=15&dsum=March%20OpenCon%20Community%20Call&ddesc=OpenCon%20community%20calls%20give%20a%20chance%20for%20you%20to%20learn%20what%C2%B4s%20happening%20in%20open%20research%20and%20education%20around%20the%20world%2C%20share%20what%20you%C2%B4re%20doing%20and%20find%20collaborators%20and%20opportunities.%26amp%3Bnbsp%3B%20Call...&dorga=Joe&dorgaem=joe%40sparcopen.org&dateformat=DD%2FMM%2FYYYY&reference=http://www.opencon2017.org/march_2017_community_call).

**Comment by philboeselager** [comment]
So far, we've mapped:
- `DTSTART` ==> `startDate`
- `DTEND` ==> `endDate`
- `LOCATION` ==> `location.address`
- `GEO` ==> `location.geo`
- `SUMMARY` ==> `name.@value`

We add the following information:
- `@id`
- `@type`
- `@context`

TODO (@philboeselager):
- `CREATED` ==> `dateCreated`
- `DESCRIPTION` ==> `description`

Yet unmapped fields:
- `UID` (possibly different formats; for some, it appears in email-address style, like: 1234567890abcdefghijklmnopq@google.com)

Fields to be ignored (?):
- `DTSTAMP` (is date-time of calendar retrieval)
- `LAST-MODIFIED` (we only store this data for the surrounding WebPage, not for the Resource itself)
- `SEQUENCE` (an event- or calendar-specific subfield)
- `STATUS` ("confirmed" etc.)
- `TRANSP` (transparency)
- `X-APPLE-TRAVEL-ADVISORY-BEHAVIOR` (whatever that means)
- `BEGIN:VALARM`, `END:VALARM` and all sub specifications in between

Open questions (@acka47, @literarymachine):
- Should we use the given `UID` value (instead of a new `urn:uuid`)?
- Or should we generate a new UUID and link to the given `UID` using `sameAs`?
- We could use `VALARM` specifications in the future for reminding people via email or so. As we should not collect data that we don't actually need, we should leave this information for now, right?

**Comment by philboeselager** [comment]
> Should we use the given UID value (instead of a new urn:uuid)?

By now, we do use the given `UID` as `@id` if and only if its value starts with `urn:uuid:`

**Comment by literarymachine** [comment]
> By now, we do use the given UID as @id if and only if its value starts with urn:uuid:

Our data model only says that `@id` has to be a URI. So it does not necessarily have to start with `urn:uuid`. Anyways, I would got with either reusing all ids or adding new ones for every entry and linking with `sameAs`. Which would you prefer, @acka47?

**Comment by acka47** [comment]
I can't oversee the implications for reusing the IDs and thus tend to create new ones. If we want to retain external IDs for events, we might add them using http://schema.org/identifier...

**Comment by philboeselager** [comment]
@philboeselager: add tagging functionality as discussed with Anne

**Comment by philboeselager** [comment]
@literarymachine Is there anything to be done (for me)?

**Comment by literarymachine** [comment]
> Is there anything to be done (for me)?

No. I was waiting for @trugwaldsaenger to provide an actual real world use case to import some stuff, but there seems to be none.

**Comment by philboeselager** [comment]
So, let's close it and reopen it in case of reald world data.

**Comment by literarymachine** [comment]
I think we should merge https://github.com/hbz/oerworldmap/pull/1195 and then close this, no?

**Comment by philboeselager** [comment]
> I think we should merge #1195 and then close this, no?

+1

**Comment by literarymachine** [comment]
Fixed on #1195.
