### ISSUE TITLE
Different approaches to searching and the consequences

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1117]
There are two approaches to searching on the OER World Map we both need. Because they are very different and sometimes result in conflicting requirements to the settings of the search engine I will describe them here:

1. **Google-like searching**: I want to find a specific entry and I expect this entry to be on the top of the result list (or beneath the top three). I want to find this entry even if I don’t know how it is spelled exactly or if I know only Parts of its name (like United Nations for UNESCO). I don’t look at all entries of the result list. I don’t mind if they start at entry number 10 to look strange and random, because I’m only interested in finding this one entry not a list! Like searching with google nobody expects to get a list with only 10 hits but all perfectly fitting. Everybody only looks at the top results and adjusts the search terms if these results don’t fit.
2. **Searching like filtering from a database**: I want to generate a list of entries with special characteristics. I don’t want not exactly fitting entries included. 

Maybe the solution is to generate lists of results by using the filters and finding special entries by using the search.

**Comment by philboeselager** [comment]
> Maybe the solution is to generate lists of results by using the filters and finding special entries by using the search.

That seems to be a good approach, as long as we can't think of a case for wanting a list by query term.

As this issue does not contain a specific request we could label it as a discussion. Probably we'll find some time it for it on our upcoming team meeting? @trugwaldsaenger

**Comment by philboeselager** [comment]
>> Maybe the solution is to generate lists of results by using the filters and finding special entries by using the search.

> That seems to be a good approach, as long as we can't think of a case for wanting a list by query term.

@trugwaldsaenger @karindr So, is this the way we should go for?

**Comment by philboeselager** [comment]
Having talked with @karindr about this issue more specifically, it appears that the distinction described above is a question of sorting (when seen from the technical side).

- The behaviour that feels "Google like" and which offers "top results" is based on "intelligent" an multidimensional search. Unlike Google and due to our project's capacities, we have to keep our search mechanism in the syntactic dimension. This means, we have no chance to automatically derive "UNESCO" from "United Nations".
- Filtering can be regarded as searching without any sorting.

So if we would want to tune our "Google like" search results, we have parameters like the following to refine:

1. Truncation
2. Weighting of fields
3. Fuzzy search
4. Language specific stemming
...

We dropped 1. due to too many unwanted search results.
We are working on 2. from time to time. Non- or badly-working examples contribute to our test case collection, by which we tune our search behaviour.
Fuzzy search (3.) can help to find "similar" results and thereby can help finding things, but it would not be suitable for the "United Nations" vs. "UNESCO" example.
We are currently working on 4. in [another issue](https://github.com/hbz/oerworldmap/issues/1407).

@karindr So, if you'd like to add some non-working example URLs, please attach them by commenting here. Otherwise: I don't see what we could do on this specific issue - please close it then.
