### ISSUE TITLE
Include number of links to search algorithm

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1120]
We should consider to rank entries, which are linked often in the database higher, than entries, which are not often linked. One example would be the "OERInfo Richtlinie":

https://oerworldmap.org/resource/urn:uuid:3f11cdbd-a74a-4aa4-83b3-b4148bfdbe82

This entry includes links to 23 sub-projects and events as well, which indicates, that it is important.

**Comment by philboeselager** [comment]
@literarymachine I'm thinking about the way to implement this. My idea so far:

- add an Elasticsearch subfield "referencedBy"; its value is an array of the uuids that refer to this entry
- when storing new resources, the "referencedBy" array of every directly referred resource is appended with the new uuid
- when removing resources, the uuid of the resource is removed from the "referencedBy" array of every directly referred resource
- refine the (default) Elasticsearch scoring by the means of [scripting](https://www.elastic.co/guide/en/elasticsearch/guide/current/script-score.html)

Not sure about it in detail, but it should work. What do you think?

**Comment by literarymachine** [comment]
`about.*.@id`

**Comment by philboeselager** [comment]
After having searched intensively for a dynamic solution that counts occurences of `*.@id`, it seems that this is not possible in the context of Elasticsearch scripting (but only for MultiMatchQueries). So the remaining solution would be to explicitely iterate over a predefined field list, consisting of:

- about.comment.@id
- about.performer.@id
- ...

Anyway, it turns out that this is an expensive query, thinking of big result lists. Therefore I would favour a counter in

1. either a very simple way, consisting of just a number, that is increased with every new link and decreased with a deleted link; this solution requires the least data redundancy
2. or an @id list way, where the size() of the list is queried for the ranking / boost; this additional data is easier to validate

@literarymachine Which way would you prefer?

While thinking about it, I would go for the simple number counter (1.) as it is exactly what we are looking for and we would still have the opportunity to validate the data against the `@id` subfields.

**Comment by literarymachine** [comment]
> Which way would you prefer? While thinking about it, I would go for the simple number counter (1.)

Sounds reasonable. How about we add this to the `Record` instead of the `Resource`, e.g. as a property called `centrality`? This way we don't "pollute" the actual data. We could do so e.g. like this:

```
public class Record extends Resource {

  private static final long serialVersionUID = 5181258925743099684L;
  public static final String TYPE = "WebPage";
  public static final String RESOURCE_KEY = "about";
  public static final String DATE_CREATED = "dateCreated";
  public static final String DATE_MODIFIED = "dateModified";
  public static final String AUTHOR = "author";
  public static final String CONTRIBUTOR = "contributor";
  public static final String CENTRALITY = "centrality";

  public Record(Resource aResource) {
    super(TYPE, aResource.get(JsonLdConstants.ID) + "." + RESOURCE_KEY);
    put(RESOURCE_KEY, aResource);
    put(DATE_MODIFIED, UniversalFunctions.getCurrentTime());
    put(CENTRALITY, getCentrality());
  }

  public Resource getResource() {
    return (Resource) get(RESOURCE_KEY);
  }

  private int getCentrality() {
    // crunch some numbers
  }

}
```

What do you think?

**Comment by philboeselager** [comment]
> Sounds reasonable. How about we add this to the Record instead of the Resource, e.g. as a property called centrality? This way we don't "pollute" the actual data.

Good idea. Also, this makes more sense semantically, while both ways are providing the same features.

**Comment by philboeselager** [comment]
@literarymachine and @trugwaldsaenger Would it make sense to provide an option for not respecting the centrality (number of links) in the search ranking to the user? (That means an option for: "Switch number-of-links effect to off.")

**Comment by literarymachine** [comment]
> Would it make sense to provide an option for not respecting the centrality (number of links) in the search ranking to the user?

I am very much in favor of *not* confronting the user with this option.
