### ISSUE TITLE
Add full screen view for single resources

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1134]

**Comment by trugwaldsaenger** [comment]
I think the full screen view would also be an important first step for creating topical pages

**Comment by formimkontext** [comment]
First draft of full screen view for single resource as a modal. I would prefer a modal, because we can even use it in the country view to show country reports. And since the main task of the full screen mode is to reach better legibility, a plain backround and less distracting surrounding will work fine. Are there any other special needs, besides displaying text and images bigger?

We should think about a possibility to customize the header. This doesn’t nessecarely have to be an uploaded photo, it could be a static picture of the map or an illustration or something else …

![20170516-fullscreen-story](https://cloud.githubusercontent.com/assets/15141949/26108066/9eece552-3a4b-11e7-9a2b-fe099c098d4d.png)

**Comment by karindr** [comment]
The user should have the possibility to easily be able to add pictures with full width and pictures right and left aligned.

I personally like am world map (even an empty one) as background (where it is dark blue in the draft) much better. This would not have to be displayed in the mobile view.

**Comment by formimkontext** [comment]
Yes, the modal should be transparent as it is in our modals right now (e.g. global statistics modal). 

![20170517-fullscreen-story-viewport](https://cloud.githubusercontent.com/assets/15141949/26146869/f279d3d2-3af1-11e7-8274-38e25285f00b.png)

**Comment by literarymachine** [comment]
Deployed to production.
