### ISSUE TITLE
Only list sub-projects at super-project

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#1180]
Felix already attached the imported OER world map project phases as sub-project to the existing entry see https://oerworldmap.org/resource/urn:uuid:43526b28-66f8-49bb-bf1c-c3cb8d4bbbcd. I also created a superordinated entry for the The Community College Open Textbook Project to attach the different imported sub-projects, see https://oerworldmap.org/resource/urn:uuid:12c8928e-dbbf-418c-883e-6bf85d843aee. This already adds some structure but the entries of the operating organizations get even more confusing as the sub-projects are listed along the super-project, see https://oerworldmap.org/resource/urn:uuid:a5ed320b-dc9b-420d-97d2-51881dc09e87 & https://oerworldmap.org/resource/urn:uuid:e08975fe-acc0-4733-8496-2cfc034a120a.

As already discussed offline, we should find a way to only show sub-projects at the super-project entry and to exclude sub-projects from search result lists.

**Comment by literarymachine** [comment]
> As already discussed offline, we should find a way to only show sub-projects at the super-project entry and to exclude sub-projects from search result lists.

One way would be to simply exclude entries that have a `isPartOf` relation to another project from the search results. But this would be a problem for those projects that are part of program, which should be shown in the result list. So in order to properly do this, I suggest we implement a simple SKOS to differentiate `Program`, `Project` and `Subproject`.
