### ISSUE TITLE
Location on map is not shown

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1183]
When I add the location to an existing entry, the orange point is not shown after saving, see:
![image](https://cloud.githubusercontent.com/assets/18674205/25332004/5ed965ca-28e5-11e7-8b2c-34119fc7e994.png)
Although a pin on the little map is shown (which is strangely grey), see:
![image](https://cloud.githubusercontent.com/assets/18674205/25332166/cfa31120-28e5-11e7-830b-4cd9aa13b5c5.png)

**Comment by karindr** [comment]
This strange gray map is shown for all entries, even old ones:
![image](https://cloud.githubusercontent.com/assets/18674205/25376733/78dbe770-29a5-11e7-932a-144a6390b50a.png)

**Comment by karindr** [comment]
Opened new issue for the grey map: #1188

**Comment by literarymachine** [comment]
After reloading the page, the orange pin with the new location will be shown. The problem here is that with #1165 the pin will only appear after indexing into Elasticsearch is done. @j0hj0h should we maybe go back to an approach where the pin of the currently selected entry is read directly from that JSON-LD instead of the GeoJSON?

**Comment by karindr** [comment]
When I start on the map showing the whole world and enter a new organisation in India the orange dot is not shown. This is probably the same issue. I think it should be changed because it looks like a bug.

**Comment by karindr** [comment]
+1
