### ISSUE TITLE
Add proper attributions to map

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1193]
See https://www.mapbox.com/help/attribution/

**Comment by acka47** [comment]
The text and watermarks looks good, but one link isn't correct I think:  "© Mapbox" should link to https://www.mapbox.com/about/maps/ 

(At https://www.mapbox.com/help/attribution/, the HTML example has the wrong link I think. All other examples link to the one above. Also, they once have a different link (http://www.openstreetmap.org/about/) for "© OpenStreetMap". I'll ask them to fix this.)

**Comment by literarymachine** [comment]
On beta.

**Comment by acka47** [comment]
The watermark should also link to http://mapbox.com/about/maps (currently links to https://www.mapbox.com/map-feedback/).

**Comment by j0hj0h** [comment]
fixed the watermark link, also changed the feedback link form /map-feedback/ to /feedback/ as this seems to be the new url. now it's like suggested here: https://www.mapbox.com/help/attribution/#other-mapping-frameworks ... only the © Mapbox link is different and goes to /about/maps/ instead of /feedback/ ... as this seems to be a typo on the help page.

**Comment by acka47** [comment]
+1 (I find https://www.mapbox.com/help/attribution/ quite confusing.)
