### ISSUE TITLE
Enable browser to fill in user name automatically

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1242]
When I log in with chrome I have to type in my username every time even 2 times when I made a mistake in the PW. Please enable the browser to suggest my username when I start typing it like for example twitter does. 

I think sometimes people who use the map not very often will have problems to remember which username they chose so this will help them also so they won't get frustrated and leave the map.

**Comment by literarymachine** [comment]
> Please enable the browser to suggest my username when I start typing it like for example twitter does.

We are using the standard browser HTTP authentication mechanism; depending on your browser, it should ask you if you want to save your user name and password. This way, you don't have to type it in at all. We cannot influence the content of the presented login popup though.

**Comment by karindr** [comment]
To understand this: Other websites don't use this standard browser HTTP authentication mechanism so they are able to suggest my email to me without me having saved my password? Would it be time consuming to develop a solution to do it the other way?

**Comment by literarymachine** [comment]
>  Other websites don't use this standard browser HTTP authentication mechanism so they are able to suggest my email to me without me having saved my password?

There are dozens of different mechanisms out there. Some sites use cookies to store your username so that it can be pre-filled (we just recently wrote in our new terms and conditions that we are only using cookies for piwik). Some use input fields of type `password` for which *the browser* offers to save the credentials.

We use HTTP Basic Auth which is built into browsers and looks something like this:

![screenshot from 2017-06-27 11-15-34](https://user-images.githubusercontent.com/149825/27580248-578c1f0c-5b2a-11e7-855c-225123a838b7.png)

Browsers usually offer to store your username and password. What is so troublesome about just confirming your browser to save your credentials.

> Would it be time consuming to develop a solution to do it the other way?

Yes.

**Comment by karindr** [comment]
OK then. (I never safe my passwords in the bowser :-).)
