### ISSUE TITLE
Tajikistan is still white despite its first entry

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1243]
See:
![image](https://cloud.githubusercontent.com/assets/18674205/26674781/cd8acbd6-46c1-11e7-81dd-471afd0486aa.png)

**Comment by karindr** [comment]
Now, a while later and with a second entry it is green.

**Comment by literarymachine** [comment]
> Now, a while later and with a second entry it is green.

This is yet again due to the asynchronous indexing (like #1183 and others). Since our indexing process has been tuned, we could try to re-enable synchronous indexing. Saving an entry will be a bit slower, but the map will always display the correct data right away after that. What do you thing, @karindr?

**Comment by karindr** [comment]
It depends on how much the difference will be. Could we test it on beta? (This issue only is obvious when you have entered the first entry for a country so it is not worth slowing down the map very much.)

**Comment by literarymachine** [comment]
> Could we test it on beta?

Synchronous indexing has actually been enabled on beta for a while, so I assume it would be ok. Nevertheless I just realized for this issue and #1183 to be fixed we do need some slight modifications in the code, too. Will discuss this with @j0hj0h.

**Comment by literarymachine** [comment]
Inactive, closing.
