### ISSUE TITLE
Publications should  inherit the location of its publisher or get an own location like stories

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1272]
At the moment publication is the only datatype without location, shouldn't we change this to make the map more consistent? If publication has no location it could not be used to create the heat map and it could not be shown in the country view. A lightweight approach to get this would let the publication inherit the location of its publisher. Stories which are similar to publications have a location.

**Comment by formimkontext** [comment]
> A lightweight approach to get this would let the publication inherit the location of its publisher. 

Sounds reasonable.

**Comment by karindr** [comment]
Publications are a great possibility to add entries to countries with only few entries, so it would be great to give them al localisation so the are counted for heat map and country view! The localisation should be optional. We have for example a publication on OER in Oman and one on OER in India.

**Comment by literarymachine** [comment]
> Hamburg is not in Africa

No it isn't. But the coordinates `[0,0]` are, and this is where the map is focused when no `location` is given.

Since this issue is marked as a question, what do @trugwaldsaenger and @acka47 think?

**Comment by acka47** [comment]
> A lightweight approach to get this would let the publication inherit the location of its publisher.

I don't know whether this really is so lightweight. See for example this publication which has two projects as publisher: https://oerworldmap.org/resource/urn%3Auuid%3A8a7c5aa5-3b92-4ea3-acff-2b64a492ef68 The projects also do not have a location so we'd need to fetch the location from yet another entry and in the end we would have two locations in Hamburg and one in Frankfurt for this publication.

Another possibility is to (optinally) let people add a location the publication is about.

**Comment by acka47** [comment]
Another example is this one with three "publishers" only one coming from Chile which the publication is about: https://oerworldmap.org/resource/urn%3Auuid%3A56610306-796a-4a18-9a6a-d1b47192b089

**Comment by karindr** [comment]
In the new item view there are several points shown for different locations, so three publishers are not a problem.

What about this idea: We add a field that a publication can be given a location actively by the person entering the data (as we have for stories). If there is no data in this field the publication inherits the location of its publishers. I don't see a problem if the publisher is a project which inherits the location from its operating organisataion.

**Comment by acka47** [comment]
This is similar to #1272 which is about locations for online events.

**Comment by trugwaldsaenger** [comment]
Certainly an issue, it would be preferably to have as many pins as possible. Nevertheless publications are not our highest priority at the moment. This might change, when we are working on implementing the OER policy registry, since I consider policies to be a subtype of publications. 

In this context I think it is interesting to read @acka47 remark:

> Another possibility is to (optinally) let people add a location the publication is about.

This would be helpful for policies, since with those it is most important where they are geografically applicable (e.g. in an institution or in a certain region or state) and not where the author comes from.

I guess this is a P2 issue and it might become more important, when we intensify our work on the registry.

**Comment by karindr** [comment]
>> Another possibility is to (optinally) let people add a location the publication is about.

> This would be helpful for policies, since with those it is most important where they are geografically applicable (e.g. in an institution or in a certain region or state) and not where the author comes from.

If we add a location field to the publication template like it is in the stories template we can choose the location the publication is about. And if this field is left empty we can show the location(s) of the publishers as we do for projects.

**Comment by karindr** [comment]
Now we have the new field "Country" and this is better than nothing because when getting a result list after searching the map might not be empty:
![image](https://user-images.githubusercontent.com/18674205/44518096-ad3ea000-a6c9-11e8-93dc-e682b31a85ea.png)

**Comment by trugwaldsaenger** [comment]
We can decide at our teammeeting, if the current solution is sufficient, or if we need additional functionality.

**Comment by trugwaldsaenger** [comment]
Increase priority to P1 - I guess it would be very helpful to show policies on the map...

**Comment by literarymachine** [comment]
> Increase priority to P1 - I guess it would be very helpful to show policies on the map...

Policies resp Publications have the possibility to add a country, as @karindr states above in https://github.com/hbz/oerworldmap/issues/1272#issuecomment-415356586. Is this not enough?

**Comment by karindr** [comment]
I would prefer to have dots for policies (and also publications) because like this we can show for example policies on different levels in a country at different places: The country policies are located at the capital of the country (government or federal agency) and the policies of different states (regional authorities) are located in the regional capital. This would be especially helpful in the United States as we can see in the policy table.

Since policies seem to become quite important we should treat them as much as the other important entries on the map as we could so the visitors get similar maps for the different types of entries.

**Comment by drrobertfarrow** [comment]
Hi all - just my 2c.

We experimented with publication locations a bit in the old OU prototype map.  It gets quite tricky because many publications are based online and don't include a place of publication.  I think associating a publication with a publisher is the easiest thing because there aren't really that many publishers relative to the number of publications.  Doing it this way might make it easier to visualise where the majority of influential publication centres.

Another possibility for academic publications is to use the home institution of the lead author as the 'place' of the publication.  This approach is supported by the fact that journals always publish this information. It might also be a better reflection of the OER community and encourage networking more than the 'publication centre' approach.  

For policies, one important aspect is the scope.  It is of marginal interest, for example, if a national policy is based in any particular town in a country.  But if the scope of the policy is regional then the location is more important.  Many policies (e.g. EU directives) have international scope.  In these cases the interesting aspect is not where the policy was thought up, but how many people are affected and where they reside.  I think there could be a case for treating policies not as pins but as blocks of influence on the map - more like a heat map.  (No doubt this is harder to do, but all policies should describe the areas they are supposed to influence.)  Maybe some combination of pins and heat mapping would be most effective?  If so, it should be possible to toggle the heatmap on/off.

**Comment by literarymachine** [comment]
The main use case was the policy registry. We will establish an own type for policies which will get / inherit a location.
