### ISSUE TITLE
English word not in translation file and other translation issues

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1325]
I'm pretty sure that this "country" in the organisations template ("Country hinzufügen") is not in the files which are exported to Crowdin. I assume it is still in the code.
![image](https://user-images.githubusercontent.com/18674205/30319213-91221624-97af-11e7-9212-161c3427118d.png)

**Comment by karindr** [comment]
There are some more english words:

- "Upsert failed" as name of the browser tab when saving an entry failed.

- "None" in the list of countries to deselect a wrong country (maybe we don't need it anymore once we are able to enter "we" or "internet".

- "Language hinzufügen" in the template for events.

- "Service.provides" in service template

And simmilar to this a wrong combination:

- "Weiterer Bildungssektor hinzufügen" has to be translated as phrase not be combinded of "Weiterer Bildungssektor" and "hinzufügen"

**Comment by karindr** [comment]
And simmilar to this a wrong combination title of the persons template:

- "Bearbeiten Person"

**Comment by literarymachine** [comment]
> "Weiterer Bildungssektor hinzufügen" has to be translated as phrase not be combinded of "Weiterer Bildungssektor" and "hinzufügen"

You probably mean this should result in "Weitere**n** Bildungssektor hinzufügen"? This is currently not possible because we generically translate these types of string as "`type` `action`", and `type` is "Weiterer Bildungssektor" here. Changing this to use non-combined phrases for individual fields is not a good option because it would either have to be hard coded or again configured somewhere.

If we really want to implement this, we would need additional strings in `conf/labels.properties` specifying the proper `type` string for individual grammar cases.
