### ISSUE TITLE
Location of entry visited before is shown

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1336]
Maybe this is a known problem, but I can't find an issue.

When I visited an entry and go to the next entry the shown location is not changing and showing the first location. For Example USA and Oman, see:
![image](https://user-images.githubusercontent.com/18674205/30585534-771e660a-9d2d-11e7-9991-1a7b3f492273.png)
This feel like a bug!

**Comment by acka47** [comment]
For reproducing the issue:

- I go to https://oerworldmap.org/resource/urn:uuid:ff56c436-7e76-11e5-b76b-54ee7558c81f
- Click on any of the OEC members, e.g. "Korea University"
- The profile opens but the map doesn't reload.
- When reloading the page the map zooms as expected.

I confirm that this is no expected behaviour. At best, the profile should open and the map should reload in parallel.

**Comment by literarymachine** [comment]
> I confirm that this is no expected behaviour.

From a technical point of view, it currently is [expected behaviour](https://github.com/hbz/oerworldmap/wiki/Memo:-Frontend-2017-03-29-(Map-extents-and-highlights)#on-page-transition):

> On page transition
>
>no zoom or center
>highlight as on initial page load

This was confirmed at one of the past team meetings. Nevertheless, it does feel strange in this case (a resource being directly loaded and thus zoomed to).

**Comment by literarymachine** [comment]
Within the front-end rewrite, @dobladov is currently implementing #1134. We are thinking about also adding a mini-map for the location zoom there. This should clarify the state of the map in most, if not all cases. The full-screen map would then only be used in list-view.
