### ISSUE TITLE
Add new fields to csv export for production of oer-Atlas, 2. edition

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1357]
According to this list:
https://docs.google.com/document/d/1ITNe1WLl52VYHrXLZ2RH5pjx_AEUFqTB8IT-0IL_Aes/edit#heading=h.dph175gn3dpl
Talked to @philboeselager about this.

**Comment by philboeselager** [comment]
As discussed with @literarymachine , we will not customize the code fitting this one specific case. Instead, we will enable "export all fields" for lists so that individual resource export and resource list export provide the same fields.

If necessary, we can implement Python scripts to sort out unwanted fields from this "all fields export".

**Comment by literarymachine** [comment]
This should automatically be resolved when #1358 is.
