### ISSUE TITLE
Search-optimization: Sächsische OER Tage

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1407]
If I search for "sächsische OER Tage" no results are found. Searching for "sächsische**n** OER Tage" brings the right result (https://oerworldmap.org/resource/urn:uuid:751c2006-4601-4c43-935b-4f7380784dd3).

**Comment by philboeselager** [comment]
@literarymachine : Following the idea of solving this by the means of using stemming in the Elasticsearch mapping:

- we would need to use different stemmers for different languages.
- therefore, we would need to re-write our mapping from
`"name" : {"@value" : "<value>", "@language" : "<language>"}`
to
`"name_<language1>" : { "@value : "<value1>" },
"name_<language2>" : { "@value : "<value2>" }`,
using different `analyzer`'s per language. Right?

Is the the life we really want?

**Comment by philboeselager** [comment]
Following the approach of multiple `"name_<language>"` fields, we would have to rewrite the Json coming from the frontend the way described above.

The thing is that we would need to configure our mapping so that it contains all languages provided by our frontend, right? So, every occurance of 

    ": {
      "properties": {
        "@value": {
          "fields": {
            "simple_tokenized": {
              "search_analyzer": "standard",
              "type": "string",
              "analyzer": "simple"
            },
            "variations": {
              "search_analyzer": "title_analyzer",
              "type": "string",
              "analyzer": "title_analyzer"
            },
            "@value": {
              "type": "string"
            }
          },
          "type": "multi_field"
        },
        "@language": {
          "index": "not_analyzed",
          "type": "string"
        }
      }
    }

would have to be replaced by up to `numberOfPossibleLanguages` entries like:

    _<language1>": {
      "properties": {
        "@value": {
          "fields": {
            "simple_tokenized": {
              "search_analyzer": "standard",
              "type": "string",
              "analyzer": "simple"
            },
            "variations": {
              "search_analyzer": "title_analyzer_<language1>",
              "type": "string",
              "analyzer": "title_analyzer_<language1>"
            },
            "@value": {
              "type": "string"
            }
          },
          "type": "multi_field"
        }
      }
    }

Having 51 specifications of language fields, this seems to make the index unmanageable. I'm sure we would be able to create an index like that by the means of our [fix mapping script](https://github.com/hbz/oerworldmap/blob/master/scripts/fix_mapping.py). But does it make sense? Especially, as we do not have Elasticsearch stemmers for the biggest part of OER WorldMap's languages.

I guess it's possible but my intuition says it would be better to work with fuzzy search on this issue. WHat about offering the user the possibility to re-search fuzzily in case the exact search has not provided a hit?

**Comment by literarymachine** [comment]
I would give this a try: https://www.elastic.co/guide/en/elasticsearch/guide/current/mixed-lang-fields.html

**Comment by literarymachine** [comment]
> I would give this a try: https://www.elastic.co/guide/en/elasticsearch/guide/current/mixed-lang-fields.html

I.e. the "Analyze multiple times" approach described there.

**Comment by philboeselager** [comment]
Fine for me as long as we are confident with only featuring a few languages. The argument that most text passages are written in English is strong. Also, I'm not sure if providing fuzzy search for all languages would provide better user experience in rare languages.

Following your suggestion, @literarymachine , the resulting mapping structure would look like:

    "name": {
      "properties": {
        "@value": {
          "fields": {
            "simple_tokenized": {
              "search_analyzer": "standard",
              "type": "string",
              "analyzer": "simple"
            },
            "variations": {
              "search_analyzer": "title_analyzer",
              "type": "string",
              "analyzer": "title_analyzer"
            },
            "@value": {
              "type": "string",
              "fields": {
                "de": { 
                  "type":     "string",
                  "analyzer": "german"
                },
                "en": { 
                  "type":     "string",
                  "analyzer": "english"
                },
                "fr": { 
                  "type":     "string",
                  "analyzer": "french"
                },
                "es": { 
                  "type":     "string",
                  "analyzer": "spanish"
                }
              }
            }
          },
          "type": "multi_field"
        },
        "@language": {
          "index": "not_analyzed",
          "type": "string"
        }
      }
    }

Correct?

**Comment by acka47** [comment]
I am not sure whether this would help here, but @literarymachine and I discussed once or twice to use the "language maps" approach for language tagging in JSON-LD as outlined in the [spec in paragraph 4.10](https://json-ld.org/spec/latest/json-ld/#string-internationalization), see example 37.

For this, we would add `"@container": "@language"` in the context for all properties we want to use alnguage maps for. Int he data, looking at the hbz entry as example, this would result in

```json
"name":{
  "de":"Hochschulbibliothekszentrum des Landes Nordrhein-Westfalen",
  "en":"North Rhine-Westphalian Library Center"
}
```
 instead of 

```json
"name":[
  {
    "@value":"Hochschulbibliothekszentrum des Landes Nordrhein-Westfalen",
    "@language":"de"
  },
  {
    "@value":"North Rhine-Westphalian Library Center",
    "@language":"en"
  }
]
```

**Comment by philboeselager** [comment]
@acka47 Language maps look fine. But they won't help us here in using language specific stemmers, right?

@literarymachine suggested to use [Elasticsearch multi-fields](https://www.elastic.co/guide/en/elasticsearch/guide/current/mixed-lang-fields.html). This is a handy approach as long as we effectively deal with a rather limited number of content languages. Looks like the most practical way to go.

**Comment by literarymachine** [comment]
> @acka47 Language maps look fine. But they won't help us here in using language specific stemmers, right?

They would help us, because we could index `name.de` using the German stemmer, `name.en` using the English one etc. instead of indexing every `@value` in multiple languages.

> @literarymachine suggested to use Elasticsearch multi-fields. This is a handy approach as long as we effectively deal with a rather limited number of content languages. Looks like the most practical way to go.

Because using language maps will require some refactoring of not only the Elasticsearch configuration but also the input templates, I would suggest we go with the multi-fields for now.

**Comment by philboeselager** [comment]
@literarymachine Which languages should we start with? There's quite a bunch of possibilities, see [this elastic documentation](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/analysis-stemmer-tokenfilter.html).

- The more languages, the bigger our index mapping, which is manageable by the [python script](https://github.com/hbz/oerworldmap/blob/master/scripts/fix_mapping.py).
- And the more fields we must configure in [search.conf](https://github.com/hbz/oerworldmap/blob/master/conf/search.conf). Maybe we should develop something to easier configure the latter.

We are not in data size regions to need to severely care for performance being harmed by multiple fields, like [this answer](https://discuss.elastic.co/t/performance-issues-with-multiple-field-flt-queries/5493) suggests.

**Comment by literarymachine** [comment]
> Which languages should we start with? There's quite a bunch of possibilities, see this elastic documentation.

I would stick with the languages we also support in the UI: English and German.

> The more languages, the bigger our index mapping, which is manageable by the python script.

Yes, you can probably just modify https://github.com/hbz/oerworldmap/blob/master/scripts/fix_mapping.py#L92 for now by adding additional multi fields for English and German stemming there.

> We are not in data size regions to need to severely care for performance being harmed by multiple fields, like this answer suggests.

+1

**Comment by literarymachine** [comment]
> Yes, you can probably just modify https://github.com/hbz/oerworldmap/blob/master/scripts/fix_mapping.py#L92 for now by adding additional multi fields for English and German stemming there.

While you are at it, you could probably also add a `raw` multi field that is `not_analyzed` so that we can sort results alphabetically, see https://github.com/hbz/oerworldmap/issues/946#issuecomment-312839844.

**Comment by philboeselager** [comment]
> While you are at it, you could probably also add a raw multi field that is not_analyzed so that we can sort results alphabetically, see #946 (comment).

Sure. I would nevertheless keep branches separated.

**Comment by literarymachine** [comment]
@trugwaldsaenger: I assume you meant "erste sächsische OER Tage" vs "erste**n** sächsische OER Tage" in your error report.

@philboeselager Why not use the above error as the test case?

**Comment by philboeselager** [comment]
> @philboeselager Why not use the above error as the test case?

Because these words are used both, in the title and in the description, and in different variants:

- `name.@value : "Ersten sächsische OER-Tage"`
- `description : "ersten sächsischen OER-Tage"`

There's nothing bad about the words, esp. Umlaute are not a problem. I was just taking a test case where it was clear that the positive stemming test result could not be an effect of textual variants.
