### ISSUE TITLE
Replace Mapzen API

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#1410]
Unfortunately, Mapzen is shutting down, see https://mapzen.com/blog/shutdown/

We are obviously using it for location lookups in the web form, see 
https://github.com/hbz/oerworldmap/blob/4390ec43bb681989939e3e40625386ea7464d09c/public/javascripts/behaviours/resource-form-widgets/place.js#L190 and #64.

We will have to find another solution until the end of January. For lobid, we have a pelias server running but I think it only contains geodata for German-speaking countries. I am not sure whether we can easily cover the whole world . @dr0i, what do you think?

**Comment by dr0i** [comment]
We should be able add the global data to our pelias instance. At http://pelias.io/install.html it's said that would need 330GB in an ES index, which is pretty much. At lobid we have a two-node cluster without replica i.e. we would need 330/2 GB =160 GB per server. At the moment we have ~200GB per server free, so that would tightly fit.

**Comment by literarymachine** [comment]
Since time is pressing, I'll move back to https://nominatim.openstreetmap.org/ for now.

**Comment by acka47** [comment]
Ok. Just ping @dr0i if you need another pelias server. He will then start setting it up.
