### ISSUE TITLE
Landing page mobile view has several bugs

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1425]
I looked on an adroid phone:

- "Navigate" is cut off
- "Join" and "Login" buttons are above each other but not exactly
- The three points "What is OER" and so on are not centered (and the texts look pretty funny one word per line)
- the table "For actors" and so on doesn't look very well
- the E-Mail adress field is cut of
- most texts look pretty funny as centered lists of often single words

**Comment by j0hj0h** [comment]
Yes I know, it was plainly not yet taken care of at all :-) ... but I'm working on it since Friday already. For the future: When you see such a layout you can assume that things are not working in the hole and you can save you the time of listing the bugs in detail. Sorry that I don't warned you about the fact that the landing page was not responsive already.

**Comment by j0hj0h** [comment]
Landingpage is now responsive. Feel invited to test on your devices and post screenshots, if something doesn't work ...

**Comment by karindr** [comment]
Everthing nice on Android in horizontal and upright format!

**Comment by literarymachine** [comment]
Fixed in https://github.com/hbz/oerworldmap-static/commit/312588ea905e6b89e36afee6e23b47e5707d95df
