### ISSUE TITLE
Make CSV export more userfriendly

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1432]
This is based on feedback from a user trying 15 minuts to use our csv export and than stopping.

1. There should be a column with the URL of the entry on the OER World Map (Yes, I know that I can change the the @id column to this by saerch and replace, but this shurely can be done before the export)

2. In not so few cases the description is split to different fields in several rows (see for an example the csv of this entry: https://oerworldmap.org/resource/urn:uuid:25eeba89-ac87-4934-8c66-063c6180964d)

3. The columns are in an alphabetical order. It would be more helpful to have the name of a service at the beginning and put start and end date next to each other for example (I can provide a useful order if needed).

**Comment by literarymachine** [comment]
> There should be a column with the URL of the entry on the OER World Map (Yes, I know that I can change the the @id column to this by saerch and replace, but this shurely can be done before the export)

Right, that makes sense.

> In not so few cases the description is split to different fields in several rows (see for an example the csv of this entry: https://oerworldmap.org/resource/urn:uuid:25eeba89-ac87-4934-8c66-063c6180964d)

I think the problem here is that fields seems to be separated by semicolon, not comma. So if imported using a comma as a field separator, the entries indeed make little sense, especially for full text fields such as `description`. @philboeselager is there a reason you used commas?

> The columns are in an alphabetical order. It would be more helpful to have the name of a service at the beginning and put start and end date next to each other for example (I can provide a useful order if needed).

Yes, please let @philboeselager and me know which order would make sense!

**Comment by karindr** [comment]
The order of the rows should be the same as the order of the fields in the presentation on the map (if the csv skips some fields that is no problem).

**Comment by trugwaldsaenger** [comment]
+1 the order of the presentation on the map seems reasonable

@philboeselager: Would it be possible to connect the order of the fields to the order in the profil, so that, if we change the order of the fields in the profile, the order in the export is changed as well? Just asking - if it is problematic, a manual solution will work as well!

**Comment by literarymachine** [comment]
> There should be a column with the URL of the entry on the OER World Map (Yes, I know that I can change the the @id column to this by saerch and replace, but this shurely can be done before the export)

Will be added as an extra column.

> In not so few cases the description is split to different fields in several rows (see for an example the csv of this entry: https://oerworldmap.org/resource/urn:uuid:25eeba89-ac87-4934-8c66-063c6180964d)

Columns will be separated by commas, content will be wrapped in quotes.

> The columns are in an alphabetical order. It would be more helpful to have the name of a service at the beginning and put start and end date next to each other for example (I can provide a useful order if needed).

@philboeselager will look into this
