### ISSUE TITLE
Logos are often transparent with white letters, make dark background possible

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1455]
We often can't use the logos from the organisations websites because the logosare ofen transparent with white letters. Could we establish a possibility to change the backgroundcolor to black or a dark grey for these logos manually?

**Comment by formimkontext** [comment]
talked to @literarymachine and @j0hj0h about that. we decided not to implement a posibility to change the background color for logos / images manually. this is because we won’t start with personalizing the design of profiles right now. but we will implement an image uploader soon to make it easier to upload a appropriate picture, see: #647. and we should add a guide abut image requirements to the FAQ. 

for now the easiest way would be, to use the image search to find an alternative version of the logo your looking for. mostly you  will find a proper solution.
