### ISSUE TITLE
Problems with Myanmar on the map

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1456]
As name there is "MM" displayed.
When I click onto it I get this error:
![image](https://user-images.githubusercontent.com/18674205/37084805-c117ce04-21f3-11e8-8a70-3f50bd859096.png)

**Comment by literarymachine** [comment]
@karindr please add a link to the erroneous page in the issue if possible. Screenshots at this resolution are hard to read.

**Comment by literarymachine** [comment]
@acka47 We are currently using Wikidata to import ISO3166-2 country codes. While [Myanmar](https://www.wikidata.org/wiki/Q836)'s country code is definitely available there, my [import script](https://github.com/hbz/oerworldmap/blob/master/scripts/wikidata-labels.py) is currently discarding it:

```
$ python wikidata-labels.py P297 de | grep MM=
```

It probably has to do with my query excluding properties that have an `end` time because we don't want past country codes. There seems to be a mistake in there that also excludes the current code.

**Comment by karindr** [comment]
https://oerworldmap.org/country/mm
