### ISSUE TITLE
Sort search result list

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#147]
Activated country view US: Results seem to be randomly ordered. Some kind of order should be included, e.g. alphabetical.

**Comment by literarymachine** [comment]
Elasticsearch [sorts by relevance](https://www.elastic.co/guide/en/elasticsearch/guide/master/sorting.html) by default. This seems pretty random if no search term is given, indeed. If we want to sort alphabetically, we need to specify the field to sort on. This is not as easy as it sounds, because different resource types have different fields as their title (e.g. `legalName` for `Organizations` and `name` for `Persons`). Given the fact that we have full text search, I am not sure if we really need this old school sorting. So far, @dr0i et al got around it for the lobid API.

**Comment by acka47** [comment]
>  Given the fact that we have full text search, I am not sure if we really need this old school sorting. So far, @dr0i et al got around it for the lobid API.

You are right, the lobid API doesn't support alphabetical sorting. It supports sorting by issue date, though (parameter `sort` with values `newest` and `oldest`). 

I'd rather continually put some thinking into the relevance ranking for the oer worldmap and e.g. rank entries higher that have been posted recently and/or are mor up-to-date etc.

**Comment by literarymachine** [comment]
@trugwaldsaenger you said that that the OEC member data will not be part of the next release, right?

**Comment by trugwaldsaenger** [comment]
Yes, thats correct. I would propose to restrict ourselves to the story-data first. So I guess this issue is not so urgent right now.

**Comment by literarymachine** [comment]
On https://beta.oerworldmap.org/, see "more" link under "Recent additions".

**Comment by acka47** [comment]
+1

**Comment by trugwaldsaenger** [comment]
Sarah Hoosen from South Africa just came back with this wish. It seems to be especially important in cases where you are not looking for a special entry, but trying to gather an overview of the included data. E.g.: If you choose Germany (either per country view or by search filter) you get more than 200 hits, completely unordered. We should discuss this issue on thursday, if we find the time for it.

**Comment by literarymachine** [comment]
In the next version, entries are ordered by `dateCreated` by default (i.e. if no search term if given). If a search term is given, relevance ranking provided by elasticsearch is applied.
