### ISSUE TITLE
Entering regional information to locations in the map

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1495]
I did some corrections for organisation which did appear on the map with a point but did not affect the color of their region in The Netherlands. For these two organisations the regional information was missing. When I added the region the location was deleted and I had to enter it again.

In addition to this it is difficult to know the region for foreign countries. I had to look up the names of the regions of the netherlands in wikipedia because there is only a list in the oerworldmap but the names of the regions are not displayed on the map itself. Is there no possibility to extract the regional information from the coordinates?

**Comment by trugwaldsaenger** [comment]
+1 We should definetly get rid of the obligatory regions. If you want to add something in a country you do not now so good it will slow you down significantly

**Comment by literarymachine** [comment]
> +1 We should definetly get rid of the obligatory regions.

Regions are - UI-wise - obligatory if you want to add an exact address later on, because it makes the hits of the lookup much more exact. A region is *not* obligatory to save an entry, as before only a country is necessary for that! 

> When I added the region the location was deleted and I had to enter it again.

Ok, this is indeed not ideal.

> Is there no possibility to extract the regional information from the coordinates?

There is, but then we only get regions if people go ahead an enter their entire address.

In the end, I suggest showing only the Country drop-down first. When a country is selected, we show both the region drop-down and the other address fields.

**Comment by literarymachine** [comment]
Solution: show address along with region after a country is selected

**Comment by acka47** [comment]
I opened an issue regarding the retroactive addition of region information to older entries, see https://github.com/hbz/oerworldmap/issues/1508
