### ISSUE TITLE
Login does not work in IE, endless spinner

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1503]
Comment of the user Jacques Versteijnen per mail to info@oerworldmap.org: "When I login to the oerworldmap in IE I don’t get access. Turning circles endlessly."

**Comment by trugwaldsaenger** [comment]
Problem occurs within IE11 with me as well!

**Comment by literarymachine** [comment]
@dobladov already looked into this. The problem lies within a library we are relying on and is not easily fixed. Microsoft itself is only [supporting](https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support) the most current version and is urging its users to move on to Edge. Thus I would tend to clearly not support Internet Explorer, which should of course be indicated to the user instead of simply spinning endlessly.

**Comment by trugwaldsaenger** [comment]
On Edge it is working. 

> Thus I would tend to clearly not support Internet Explorer, which should of course be indicated to the user instead of simply spinning endlessly.

Would be OK for me. But we should check how many users are using still IE. Giving the users a hint probably will be necessary anyway and probably a good interim solution.

**Comment by literarymachine** [comment]
> But we should check how many users are using still IE.

@acka47 can you pull up the piwik stats for this?

**Comment by trugwaldsaenger** [comment]
@acka47 Could you check the stats concerning the IE-usage numbers? Since I guess we have to include the hint ("Please notice that Internet Explorer is currently not supportet by the OER World Map.") anyway, I gave the issue high priority.

**Comment by literarymachine** [comment]
@dobladov checked: in order to support IE, we would have to disable half of the functionality for those users. We will now explicitly not support IE and show those users an according message.

@dobladov please user [express-useragent](https://github.com/biggora/express-useragent) to detect IE users in `server.js`. The corresponding middleware should probably go [here](https://github.com/hbz/oerworldmap-ui/blob/master/src/server.js#L41).
