### ISSUE TITLE
Some problems/issues with the filter section

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1506]
A user from the Netherland and from OEGlobal writes (he is teacher of information literacy):

"What confuses me is the way the searching goes.
Even as a teacher of information literacy the search engine was (very) confusing to me.
What confused me was:
1.A. When I enter the map
b. click on tag
c. choose one the filters in the list
               I don’t get to see a list of the filter i chose.
I now found out that I first have to choose one of the 8 icons, then enter a term in the above the icons
OR
Enter a term in the search box
Then go to tag (or location)
Choose a filter
And the click on “Apply filter”
I would expect when choosing in the tag of locations list I would get that info right away.
Suggestion:
Instead of the orange “Apply filter”  I would put there:  “Select filter(s)” And at the bottom of the filter list “Apply filter”
Keep up the good work!
Kind regards.
J.V.

**Comment by literarymachine** [comment]
If I understand this correctly, we could fix this by not automatically unsetting other (primary) filters when changing the type (referred to as "one of the icons" above). To me it seems we have implemented this in https://github.com/hbz/oerworldmap/issues/977 in order to avoid zero hit results when a secondary filter (e.g. `license`) is enabled and the user switches to a type to which that filter does not apply.

In order to do this correctly, we would have to explicitly list which filters apply to all types.

**Comment by literarymachine** [comment]
- Simple mode: clicking on a filter directly sets it
- Advanced mode: SHIFT / CTRL + click allows to select multiple filters

**Comment by trugwaldsaenger** [comment]
It seem to me as if the issue is connected to our usage of data-types as primary filters. If you start searching/filtering with them, everything works fine. But there are many other click-paths, which make sense as well, for example:

1. Starting by choosing a country, than narrow it down to projects
1. Starting by choosing an educational sector, than narrow it down to services

In these cases your filter selection is lost. Do I see it correctly, that the main reason for doing it this way around is that the available filters are dependend on the data type? 

> In order to do this correctly, we would have to explicitly list which filters apply to all types.

If this is still needed I think we should be able to produce something like this quite fast....

Two more thoughts on this:

- If we distinguish between universal filters (which are available for all data types) and special filters, which are available only for one or several data types, it might make sense to visualize this distinction, e.g. by including a line between the filters.
- I think this is a really important issue, since the basic usability of our search field should be logical and intuitively to use. I therefore increased the Prio to 1. Nevertheless, we have to see, what is a realistic time planning for this issue. Do I see it right, that it will be solved by the new search section @formimkontext and @j0hj0h presented at our last team meeting? If I remember it right, we said that this will not be available before 2019. So we might think of an intermidiate fix.  A very easy fix would be to include a help sentence: "Start filtering by setting the type of data you are looking for".

**Comment by karindr** [comment]
I don't know much about the planned filter section.

For the meantime it would be better than nothing to have te sentence @trugwaldsaenger suggested above. 

It would be better to have each filter to be activated and deavtivatet by clicking on it with no regards to the other filters. For example when I have a list of the award winners and chose the 8 awards in the award filter and I want to change to the winning services and afterwards to the winning events and so on, I have to choose the 8 awards every time.

**Comment by literarymachine** [comment]
> It would be better to have each filter to be activated and deavtivatet by clicking on it with no regards to the other filters.

It is simple to enable this, and simple to then get 0 result lists. This will happen e.g. if you enable the `Language` filter for `Service` and then switch to `Organization` - because an Organization in our data model has no language.

**Comment by literarymachine** [comment]
> If we distinguish between universal filters (which are available for all data types) and special filters, which are available only for one or several data types, it might make sense to visualize this distinction, e.g. by including a line between the filters.

I would consider the filters that are always shown "universal":

![image](https://user-images.githubusercontent.com/149825/41715629-5c116916-7554-11e8-8ee9-0041887710fb.png)

And the ones under "more" specific:

![image](https://user-images.githubusercontent.com/149825/41715658-71d182fe-7554-11e8-9e8c-f3ae30db6474.png)

**Comment by karindr** [comment]
"Award" is "universal", too. And since we want to use the awards, especially the Open education Award to make marketing for the map, it would be very helpful to have awards be shown from the beginning on!

**Comment by karindr** [comment]
> It is simple to enable this, and simple to then get 0 result lists. This will happen e.g. if you enable the Language filter for Service and then switch to Organization - because an Organization in our data model has no language.

If we are afraid of 0 result list we could establish an answer for these cases like: You get no results here because "XY" in our data model is not a category for "Z".

**Comment by karindr** [comment]
+1

**Comment by literarymachine** [comment]
> It would be better to have each filter to be activated and deavtivatet by clicking on it with no regards to the other filters.

On production. Does this fix this issue for now?

**Comment by karindr** [comment]
+1
