### ISSUE TITLE
Close item view by clicking on the background

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1521]
As @acka47 also mentioned it would be useful to be able to leave the item view by clicking on the map behind so you don't have to scroll and unse the mouse.

**Comment by trugwaldsaenger** [comment]
I agree, it is rather unconfortable to scroll back to the top of the site and close the profile. I think it is not terrible urgent, so we can keep it on P3. On the other hand it might be implemented easily, so @literarymachine can check if this is something which can be done in between...

**Comment by formimkontext** [comment]
this is because the item view looks like an overlay but technically isn’t. one solution would be, to close it by clicking on the background. or we can make the x-button fix, so it isn’t floating out of the viewport. 

on the long run, we should ad some more content and functionality to the item view. like the ›similar entries‹ section shown in this draft: https://user-images.githubusercontent.com/15141949/36307425-66246592-131c-11e8-9cf1-4aad535166ca.png

we could add a ›back to list‹ button there, too.

**Comment by karindr** [comment]
Floatin x-button would be better than having scroll.
