### ISSUE TITLE
Include publication date

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#153]
Stories detail view: Include date of publication

**Comment by literarymachine** [comment]
On https://beta.oerworldmap.org/, see e.g. subline under heading of https://beta.oerworldmap.org/resource/urn:uuid:34a6c60c-23bb-11e5-902c-001999ac7927

**Comment by acka47** [comment]
I think it should better read "Contributed on yyyy-mm-dd by xy" (adding the "on"). Also, there is at least one white space too much between by and the contributor's name (which isn't new but should be fixed).

**Comment by literarymachine** [comment]
Fixed the wording. As for the spacing, this is due to a style be @j0hj0h separating the sub heading's label from the content (see e.g. the "Service Type" in the sub heading of https://beta.oerworldmap.org/resource/urn:uuid:fbbd8618-15d8-11e5-8850-2bd783bbdf05). I sort of fixed that by setting only "Contributed" as the label - if you want anything else, please discuss with @j0hj0h.

**Comment by acka47** [comment]
+1
