### ISSUE TITLE
Change in displaying markup mixed with HTML

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1531]
Have a look at this story
https://oerworldmap.org/resource/urn%3Auuid%3Afde78e22-a299-4b81-bc20-5e5f4ee76867?
It was displayed as planned in the old UI but now the headings aren't displayed as headings but with ##.

**Comment by dobladov** [comment]
This is because the new plugin for markdown does not allow invalid markdown, in this case `##title` without a space between the hash and the title, the correct way should be `## title`.

In the old version this was valid, but I think the proper solution is to fix the markdown text manually to valid Markdown.

**Comment by literarymachine** [comment]
> In the old version this was valid, but I think the proper solution is to fix the markdown text manually to valid Markdown.

I agree that we should fix this at the source.

**Comment by karindr** [comment]
I will do. Are you aware of more things we have to look for?
