### ISSUE TITLE
Strange proposal list in template for entering open

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1535]
I was editing the entry for Open up resources as service and wanted to add the organisation Open up resources as provider. When I entered "open" Open up resources was not in the list but a lot of entries without "open" in the name like Jan Neumann. In the template searching for entries to link to I expect the name to be looked at (as first source or even as single source). When I add "up" the organisation is shown as 5th entry. (Yes, I know "open" is probably one of the most used words on the OER World Map.)

**Comment by literarymachine** [comment]
> I was editing the entry for Open up resources as service and wanted to add the organisation Open up resources as provider. When I entered "open" Open up resources was not in the list but a lot of entries without "open" in the name like Jan Neumann.

For reference, here is the query that is generated when looking up from the input template: https://oerworldmap.org/resource/?q=open*&filter.about.@type=Person&filter.about.@type=Organization

> In the template searching for entries to link to I expect the name to be looked at (as first source or even as single source).

Making the name the single source would be quite easy; results would look like this: https://oerworldmap.org/resource/?q=about.name.@value:open*&filter.about.@type=Person&filter.about.@type=Organization

So again, just entering "open" does not deliver the "Open up resources" among the top hits. This is because as you say `"open" is probably one of the most used words on the OER World Map`. Entering "Open up" results in this:

https://oerworldmap.org/resource/?q=about.name.@value:open%20up*&filter.about.@type=Person&filter.about.@type=Organization

Why the entry for "open up resources" is not the first hit, @philboeselager must evaluate when he is back. What I could do in the short term is to limit the search to the name field.

**Comment by karindr** [comment]
As user I would expect to have to enter parts of the name, so I would prefer searching only for name and abbreviation. The abbreviation has to be included, because people often know only the abbreviation.

@trugwaldsaenger and @acka47 , what do you think?

**Comment by philboeselager** [comment]
Limiting search results to contents of fields "name" and "abbreviation" would mean that you can never find anything that's comprised for example in the "description" field, right? Just keep this in mind, when you're discussing, @karindr , @acka47  and @trugwaldsaenger .

My feeling is that you have to accept not getting proper results for "open" in an open network, like you won't find your desired result when googling for let's say "marketing". My suggestion to ignore this "issue" and only try to make sure that the entry in question is shown first when searching for "open up resources".
