### ISSUE TITLE
Avoid overlapping pins

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#159]
via @acka47 : Some other display method than overlapping pins would make sense when two or more organizations have a common location.

**Comment by buschfeld** [comment]
Yes we already thought about this but were not sure whether this feature will be needed for the upcoming release. But I think we should add an additional semi-transparent layer "inbetween" map and the Localize-Pin symbol which serves as a contrasting background for some figures indicating the amount of items in this area. Clicking on such a "cluster area" should then create a zoom request for the display of the map, now showing the whole area, i.e. Berlin as a city. As for an illustration please see refer to the same screen I used for task #148.
![oer_demo_map-detail_50-50_drag_cluster](https://cloud.githubusercontent.com/assets/10743356/7938456/e041d80c-0945-11e5-83a8-3f0190a7adef.png)


P.S.: Perhaps not too easy to implement since we will need a query about the actual size of the map and compare it with the density of pins to decide if this "cluster area" needs to be shown in the GUI
