### ISSUE TITLE
exchange open control-room grafic

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1592]
[Here](https://oerworldmap.org/about#the-vision) the grafic has to be exchanged. The new one is attached. Also there seems to be an minor issue with the text, currently the words "The OER" is standing besides the diagram, not under it. 

![opencontrolroom_v2](https://user-images.githubusercontent.com/6639965/42026417-553b04bc-7ac7-11e8-9734-51ea9fd6d91c.png)

**Comment by literarymachine** [comment]
> Here the grafic has to be exchanged. The new one is attached.

This is exactly why we switched to GitHub pages. So that you or @karindr can edit the pages without developers. You can just update the image by [uploading](https://github.com/hbz/oerworldmap-ui/upload/master/docs/assets/images) the new version. You can "Commit directly to the `master` branch" so that the new version is automatically deployed right away.

> Also there seems to be an minor issue with the text, currently the words "The OER" is standing besides the diagram, not under it.

This is a styling issue, @j0hj0h or @dobladov will look into it.
