### ISSUE TITLE
Enrty has no dots on minimap

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1593]
https://oerworldmap.org/resource/urn%3Auuid%3Aa7d8113b-a15d-4ed1-b7c1-efd40871a88e
This entry for a project is located by links to two organisations (in Spain and in Brazil, both with dots on thei minimap) but it gets no dots on its minimap. To compare the OER World Map Projects get the dot from hbz on the minimap.
![image](https://user-images.githubusercontent.com/18674205/42152751-6cc954f4-7de1-11e8-9d54-b2029faa21f0.png)

**Comment by literarymachine** [comment]
This is currently expected behavior for two reasons. First, the entry has a `location` (with the country, not with coordinates). Whenever something has a `location`, it does not inherit one from another entry.

Second, the project is `memberOf` two organizations. We do not inherit a location in that case, but only for `mentions`, `member`, `agent`, `participant` and `provider`. The relation for hbz and OER World Map is `agent` which is why the location is correctly "inherited".

**Comment by karindr** [comment]
Solved by using region as location also for coordinates.
