### ISSUE TITLE
Add policies to the OER World Map

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1615]
- In order to edit data on the OER World Map, it is necessary to first [create an account](https://oerworldmap.org/user/register). After having verified your email address, you can [log in](https://oerworldmap.org/.login).
- To [add a new policy](https://oerworldmap.org/resource/?add=WebPage), select "Publication" from the "Add" menu at the top right: ![image](https://user-images.githubusercontent.com/149825/43588098-1353578c-966c-11e8-93a6-ac16ecea150d.png)
- Enter the title and the URL of the policy, and chose "Policy" from the "Publication type" drop down: ![image](https://user-images.githubusercontent.com/149825/43588288-7615e34e-966c-11e8-8e6c-6d16ea176e80.png)
- You can also add a description and tags:  ![image](https://user-images.githubusercontent.com/149825/43588484-e5238e6c-966c-11e8-8fd1-91d715f77731.png)
- The "Authored by" and "Published by" fields are used to link to the Author of the policy and the OER Policy Institution; type to search and select the corresponding entry from the list: ![image](https://user-images.githubusercontent.com/149825/43588750-74fa80a4-966d-11e8-960c-3b914af7d3ac.png)
- If author or policy institution are not on the map yet, open a new tab and [add the organization](https://beta.oerworldmap.org/resource/?add=Organization); you have to enter at least a name and a country: ![image](https://user-images.githubusercontent.com/149825/43589123-587fdb8a-966e-11e8-89a4-fc7e5b70670a.png) Please note that it is not possible to add a Person to the map due to data privacy. Persons can only register themselves and create a profile.
- After saving the organization, go back to the tab with the policy and use the "Authored by" or "Published by" drop downs again. Please note that it might take a second until the new entry appears in the search because the index has to be updated.
- Optionally fill in the rest of the fields and hit "Publish":  ![image](https://user-images.githubusercontent.com/149825/43589314-b6d800e0-966e-11e8-83ff-c3da323f57e5.png)
- Congratulations, the policy is now on the OER World Map. Thank you!

**Comment by trugwaldsaenger** [comment]
You can also add policy related resources (e.g. case studies, reports, servcies, etc) to the policy layer by using the tag "policy". Most common will be following resource types:

- material which has already been published on the web can be added as a "publication", which is very similar to a usual bookmark.
- using the resource type "story" will allow you to add good practise examples and reports directly to the world map.
- less common will be services related to policy making. 
- last but not least persons and organisations which concentrate on policy making could be of relevance.

In each case, do not forget to add the tag "policy" so that we can refind you entry easily!

**Comment by programmieraffe** [comment]
https://github.com/hbz/oerworldmap/wiki/FAQs-for-OER-World-Map-editors

**Comment by literarymachine** [comment]
For an updated documentation, see https://docs.google.com/document/d/1QCM0Wo0hURm3wDTWOZxpKAiqC37qYiLrySLeq6u3nRw/edit#heading=h.8cpnwhj1rth7
