### ISSUE TITLE
Make description and url fields mandatory for all entries except ...

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1673]
To have the description and the url field be displayed in all templates for new entries at the first time please make both fields mandatory for all entries. The exception are entries for stories which don't have a description (instead they have teaser and body as mandatory) and don't have to have an url field because they can be published on the OER World Map only. @trugwaldsaenger agrees to this.

**Comment by literarymachine** [comment]
> The exception are entries for stories which don't have a description (instead they have teaser and body as mandatory) and don't have to have an url field because they can be published on the OER World Map only.

What about publications? Are you sure you want to make `description` required for them, too?

**Comment by acka47** [comment]
I think we did not make description and URL mandatory for Persons. Here is an updated query for invalid entriestaking this into account: https://oerworldmap.org/resource/?q=(NOT%20_exists_:about.description)%20OR%20(NOT%20_exists_:about.url)+AND+NOT+about.@type:Person

**Comment by literarymachine** [comment]
> I think we did not make description and URL mandatory for Persons.

We did: https://github.com/hbz/oerworldmap/blob/ae971c7e6a956b58d70f78365903b0de9c308856/public/json/schema.json#L1992

Since `LikeAction` and `LighthouseAction` cannot be performed on a `Person` though, this would not be a problem for #1702, you are right. Also, for `Service` the `url` field actually is `availableChannel.serviceUrl`. Here are more specific queries for invalid entries: [Organizations](https://oerworldmap.org/resource/?q=(NOT%20_exists_%3Aabout.description)%20OR%20(NOT%20_exists_%3Aabout.url)&filter.about.@type=Organization), [Projects](https://oerworldmap.org/resource/?q=(NOT%20_exists_%3Aabout.description)%20OR%20(NOT%20_exists_%3Aabout.url)&filter.about.%40type=Action), [Events](https://oerworldmap.org/resource/?q=(NOT%20_exists_%3Aabout.description)%20OR%20(NOT%20_exists_%3Aabout.url)&filter.about.%40type=Event), [Tools](https://oerworldmap.org/resource/?q=(NOT%20_exists_%3Aabout.description)%20OR%20(NOT%20_exists_%3Aabout.url)&filter.about.%40type=Product), [Publications](https://oerworldmap.org/resource/?q=(NOT%20_exists_%3Aabout.description)%20OR%20(NOT%20_exists_%3Aabout.url)&filter.about.%40type=WebPage), [Services](https://oerworldmap.org/resource/?q=(NOT%20_exists_%3Aabout.description)%20OR%20(NOT%20_exists_%3Aabout.availableChannel)&filter.about.%40type=Service).

**Comment by karindr** [comment]
I agree, that it is bad if you are not able to like/lighthouse entries in consequence of this change. 

What I wanted to achieve with this issue was a reasonable amount of fields in the templates of the different entry when they are first shown. To encourage the visitors to enter a description and a URL these fields should be shown in the part of the template that is shown first.

I still think it is reasonable to make these fields mandatory for new entries. Maybe there could be made a difference between saving an entry for the first time and saving an entry after it was changed?

**Comment by literarymachine** [comment]
> Maybe there could be made a difference between saving an entry for the first time and saving an entry after it was changed?

This would be a major change in implementation.

**Comment by karindr** [comment]
Ok, so that is not an option.

I will close this issue then and open a new one suggesting to have more than the obligatory fields in the template window shown first.
