### ISSUE TITLE
Change login procedure to HTML form

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1705]
The current login procedure via pop up window (Basic/HTTP-Auth?) is not compatible with password managers, e.g. 1Password or the "Save password"-feature (tested it with chrome). This could lead to frustration because multiple clicks are necessary to login.

**Comment by programmieraffe** [comment]
(Also the login pop up does not reveal that signing in via email address is also possible. To be fair it is stated on the previous page, but I did not read this info the first few times ;-))

**Comment by dobladov** [comment]
Related: https://github.com/hbz/oerworldmap/issues/1707

**Comment by acka47** [comment]
I walked thorugh it several times. As discussed on slack and telephone, there is a problem when clicking "decline" during the process. Otherwise verything is working but I have to suggestions for improvement:

- When the process is cancelled somehow, people might want to start registration anew. As the email address is already registered this won't work resulting in this message:
![image](https://user-images.githubusercontent.com/160292/57842324-8894d600-77cc-11e9-81aa-2c56ac233258.png)
We should add a "Go to [login](https://beta.oerworldmap.org/.login)" to the red error box
- When the registration is successfully finished and the email address is activated I am directed to the web form for my profile. This is unexpected and it does not say why I am here now. There is a small sentence "This is your personal profile. We appreciate very much if you want to share information about yourself with the OER community." at the top. This should at least be printed to the screen in bigger letters or another sentence should be shown why I am now in the profile web form.
