### ISSUE TITLE
URI instead of name in statistics

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1711]
In the statistics column there is a URI instead of the name of the funder which is Politecnico di Milano (Polimi), see:
![image](https://user-images.githubusercontent.com/18674205/49065398-37912580-f21e-11e8-8f87-197c0565eb41.png)
Politecnico di Milano (Polimi)
https://oerworldmap.org/resource/urn%3Auuid%3A551b5e44-1b67-4e40-850f-bf2dcc4e4c0e

**Comment by karindr** [comment]
@dobladov, is this the same for names only in Greek, Spanish, Portuguese or Arabic? I think we have names only in these languages.

**Comment by karindr** [comment]
it got worse, see:
![image](https://user-images.githubusercontent.com/18674205/49438270-2ddb6500-f7be-11e8-8549-d357bb9bc225.png)

**Comment by literarymachine** [comment]
Fixed by re-implementing the [global statistics](https://oerworldmap.org/aggregation/)in Kibana. @dobladov found a way to navigate to the corresponding search results when clicking the slices of the pie charts:

![image](https://user-images.githubusercontent.com/149825/50295189-d274cc80-0477-11e9-8e9c-c89375e6ed27.png)

It is still a little rough around the edges (it is much easier to configure now, but harder to style), but it is where we're heading!
