### ISSUE TITLE
Move "Clear filter" to X in search input

### ISSUE THREAD

**Issue by dobladov** [hbz/oerworldmap#1780]
Use an X button next to the text input for the search to clear all the filters.

**Comment by programmieraffe** [comment]
I really like it, but one small addition:

Google Maps implements it in a way, so that the search button position is not distracted:
![vfl3EizpaX](https://user-images.githubusercontent.com/777278/55880462-00a22780-5ba1-11e9-97ad-dff816e78a19.gif)

http://recordit.co/vfl3EizpaX

Users won't hit the X by accident, if they're just clicking where the search icon was before. With the current solution that would be the case, moving UI element position is dangerous imho.

**Comment by programmieraffe** [comment]
To visualize it more clearly - user thinks search button is always on the right edge, so with second search he/she maybe accidently clicks on the X
![k0UxLCArn7](https://user-images.githubusercontent.com/777278/55881043-372c7200-5ba2-11e9-98c0-13efd1e6bdf2.gif)

**Comment by dobladov** [comment]
I completely agree, we could keep the search icon on the left side like it was before the refactor, maybe @formimkontext has some idea for the new drafts.
