### ISSUE TITLE
Translation issues in PT interface

### ISSUE THREAD

**Issue by tamielbr** [hbz/oerworldmap#1867]
Navigating in portuguese I noticed a number of errors, which might show perhaps a larger problem. Some elements show in EN and some in DE. If this is a lapse on my part in Crowdin, please advise so I can fix.

**Adding a service**
Doubling of text (same portuguese in bold and below in smaller text). Elements in DE.
![add_service_2](https://user-images.githubusercontent.com/3904166/64563945-e8d4f800-d326-11e9-8320-aba21a49824c.PNG)

Item description and elements are in EN.
![add-service](https://user-images.githubusercontent.com/3904166/64563948-e96d8e80-d326-11e9-8085-6c2f5dde92df.PNG)

**Top right menu bar**
Activity in EN. Looked for it in Crowdin global search, couldn't find it.

![barra](https://user-images.githubusercontent.com/3904166/64563946-e8d4f800-d326-11e9-8d88-03d6f4a2476d.PNG)

**Adding new element**

![add](https://user-images.githubusercontent.com/3904166/64563947-e8d4f800-d326-11e9-8f96-718f4c78cb56.PNG)

**Comment by trugwaldsaenger** [comment]
@literarymachine @acka47 : Could you please advise how to proceed?

**Comment by acka47** [comment]
The last one ("Adding new element") will be fixed when the latest CrowdIn PR is merged and deployed, see https://github.com/hbz/oerworldmap-ui/pull/564/files#diff-dd42de343b79193ba2c415767ecf34adL2-R2

**Comment by literarymachine** [comment]
> The last one ("Adding new element") will be fixed when the latest CrowdIn PR is merged and deployed

Done.

**Comment by literarymachine** [comment]
> Top right menu bar
> Activity in EN. Looked for it in Crowdin global search, couldn't find it.

This was indeed hard coded and not available in Crowdin. Should appear there shortly!

**Comment by literarymachine** [comment]
> Doubling of text (same portuguese in bold and below in smaller text).

In the PT translation, the same texts are provided for the labels and for descriptions. In English and German, they differ:

![image](https://user-images.githubusercontent.com/149825/67221491-d53fa580-f42b-11e9-9a85-6cb5a5b8e970.png)

![image](https://user-images.githubusercontent.com/149825/67221531-e5578500-f42b-11e9-9c23-75e5fdf71329.png)

@tamielbr this should be fixed in Crowdin.

**Comment by literarymachine** [comment]
> Item description and elements are in EN.

The "list items" are currently not sourced from Crowdin but from https://github.com/hbz/oerworldmap-ui/blob/master/src/json/esc.json and https://github.com/hbz/oerworldmap-ui/blob/master/src/json/sectors.json (and actually a couple more vocabularies). @tamielbr would you be comfortable with adding PT texts straight to the JSON there? If not, @programmieraffe offered to provide an intermediate spreadsheet.

As for why the descriptions and elements are sometimes display in English and sometimes in German in your case (and not consistently in English), this is something I have to figure out!

**Comment by tamielbr** [comment]
I don't mind, but my experience is that editing JSON will make it break ;) If you don't mind exporting I think it would be safer. I checked all else in Crowdin, think it's all uptodate and 100%.

**Comment by programmieraffe** [comment]
Hey @tamielbr, I provided a quick google doc:
https://docs.google.com/spreadsheets/d/1G5thJ66Fu0YC8mjiShPOEvrRfdgcrhb1akyb7Sbi-4Q/edit?usp=sharing

No need to add quotation marks, we can add them later. Thanks very much for your effort!

**Comment by tamielbr** [comment]
Thanks. Done ;)

**Comment by programmieraffe** [comment]
Thank you very much @tamielbr! :+1: :+1: :+1: We'll notify you when it is deployed

**Comment by literarymachine** [comment]
@tamielbr I imported the labels back to the JSON files. A couple of strings where missing in the spreadsheet, I added them in https://github.com/hbz/oerworldmap-ui/pull/573/commits/35f87c10ae6a25b2cbceca21161bde746b36559a using https://www.deepl.com/translator. Could check if those translations make sense?

Also, there are actually more vocabularies that have not been translated to Portuguese (actually, not all them have been translated to German). I have provided initial translation (again using https://www.deepl.com/translator) in the JSON, it would be great if you could also check these. Since the JSON structure is already in place, you only have to edit the labels which you can do straight in the browser:

- [activities](https://github.com/hbz/oerworldmap-ui/edit/1867-portuguese/src/json/activities.json)
- [organizations](https://github.com/hbz/oerworldmap-ui/edit/1867-portuguese/src/json/organizations.json)
- [persons](https://github.com/hbz/oerworldmap-ui/edit/1867-portuguese/src/json/persons.json)
- [policyTypes](https://github.com/hbz/oerworldmap-ui/edit/1867-portuguese/src/json/policyTypes.json)
- [projects](https://github.com/hbz/oerworldmap-ui/edit/1867-portuguese/src/json/projects.json)
- [publications](https://github.com/hbz/oerworldmap-ui/edit/1867-portuguese/src/json/publications.json)
- [services](https://github.com/hbz/oerworldmap-ui/edit/1867-portuguese/src/json/services.json)

You can commit any changes directly to the `1867-portuguese` branch. For [licenses](https://github.com/hbz/oerworldmap-ui/edit/1867-portuguese/src/json/licenses.json) and [policies](https://github.com/hbz/oerworldmap-ui/edit/1867-portuguese/src/json/policies.json) there are the English labels as placeholders for the Portuguese translations because the lingo is fairly technical.

**Comment by literarymachine** [comment]
Ping @tamielbr, how should we proceed with this?

**Comment by tamielbr** [comment]
@literarymachine busy couple of weeks. Hope to get to this by monday at the latest!

**Comment by literarymachine** [comment]
@tamielbr thanks, just wanted to make sure you had seen this!

**Comment by tamielbr** [comment]
@literarymachine hope I did this correctly. Let me know if more needs to be done.

**Comment by literarymachine** [comment]
Thanks @tamielbr, deployed these changes!
