### ISSUE TITLE
Policy is tagged with country but doesn't show on country list

### ISSUE THREAD

**Issue by tamielbr** [hbz/oerworldmap#1873]
Policy "Resolução CNE/CES (1 de 11 de março de 2016) is tagged with country Brazil but does not show in Brazil when selecting policies from that country (URL https://oerworldmap.org/resource/urn:uuid:e3861f33-fe19-4dad-b89a-24dca7e9306b)

**Comment by tamielbr** [comment]
Same happens with `https://oerworldmap.org/resource/urn:uuid:ebd436b2-729c-4bec-989a-119c424c2edf`

**Comment by acka47** [comment]
These entries have in common that in the JSON the `feature` object is missing. Assigning @literarymachine who unfortunately currently is on vacation.

**Comment by literarymachine** [comment]
This is actually expected behavior, see https://github.com/hbz/oerworldmap/issues/1693#issuecomment-492187197. At some point we decided to only take into account the location of a `publisher` in case of `Policy` entries. This was due to the import of policies from the registry where the `location` had slightly different semantics. Please discuss with @trugwaldsaenger if you don't agree or add a publisher located in `BR`.

**Comment by trugwaldsaenger** [comment]
Yes, we assumed, that this would provide correct results, at least for the two main groups (national policies and instittutional policies), where the "publisher" is the either the institution or the ministry. In consequence we have to take care, that all policies are linked to the publishing institution. I did so for Resolução CNE/CES and now it appears in the list for Brazil.

https://oerworldmap.org/country/br?filter.about.@type=Policy&size=20&features=true

**Comment by trugwaldsaenger** [comment]
@tamielbr : Do you agree that we can close the issue?

**Comment by tamielbr** [comment]
This makes sense, but it might lead to proliferation of institutions (which is not all that bad). So this is not a Ministry publication but a National Council for Education publication. For each state, we would need to include the legislative body or executive branch for each policy. This is not a problem if this is expected and I can orient our person to do it that way, no problem. 
Still, I would add a note on 'country' on the policy edit screen so people expect it not to be there, since it seems like it would be expected from being in BRAZIL and filtering by POLICY.

**Comment by trugwaldsaenger** [comment]
> This makes sense, but it might lead to proliferation of institutions (which is not all that bad).

Yes, you have a point here! This is an inherent consequence of our data model. Many organisations are appearing on the map, not because they are important, but only, because they provide the location to put a service or project on the map...

> So this is not a Ministry publication but a National Council for Education publication. For each state, we would need to include the legislative body or executive branch for each policy. This is not a problem if this is expected and I can orient our person to do it that way, no problem.

Great, thanks for your understanding, Tel! I think in the case of policy the procedure might provide some real value, since it is quite an important information to see which body published the policy

> Still, I would add a note on 'country' on the policy edit screen so people expect it not to be there, since it seems like it would be expected from being in BRAZIL and filtering by POLICY.

You are absolutely right here as well - the current version is quite irritating. The whole topic of choosing countries and locations turned out to be pretty tricky, sometimes even a bit messy. It´s on our agenda to simplify this for all data types, but probably you are right that making a special explanation for policies will make sense!

**Comment by literarymachine** [comment]
> It´s on our agenda to simplify this for all data types, but probably you are right that making a special explanation for policies will make sense!

@tamielbr the background for the complexities regarding the locations was that e.g. web services don't really have a location, so we decided to use the location of the service provider. Then for projects we thought it would make sense to use the participants' locations, because the project does not necessarily have a location of it's own. Same goes for documents and policies, which are located where the authors / editors are. In most cases, a location attached directly to an entry overwrites this inheritance mechanism, with the exception of policies due to some peculiarities in the data imported from the original registry.

Anyways, I would tend to not add additional notes to the UI but to simplify things ASAP. As discussed with @programmieraffe, we should really consider to not "inherit" locations between entries at all but explicitly add locations to all entries and use those on the map.

> I did so for Resolução CNE/CES and now it appears in the list for Brazil.

Can we go with this for now and close this issue?

**Comment by tamielbr** [comment]
Sure. for now I'll add CNE as organization with its location, and attach it to the policy.
