### ISSUE TITLE
Inherited Locations are not working properly

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1916]
I searched for services of the subtye repository in the US and received 1 hit:

![grafik](https://user-images.githubusercontent.com/6639965/84251445-aaff3d00-ab0d-11ea-8961-ef2f9d7133a7.png)

Actually there are more examples of US Repositories, which are currently not found:
- https://oerworldmap.org/resource/urn:uuid:3331a161-d35f-4ec7-ac51-47b0d9516fda
- https://oerworldmap.org/resource/urn:uuid:b084ddc2-313a-11e5-a56e-001999ac7927

Both inherit the location from their provider. After adding the country separatly to 
https://oerworldmap.org/resource/urn:uuid:5971095c-6d99-4b97-9c30-6bc56126a4c6
which originally was not found either it appears.

While the provider (Yale University) carries a pin, the service does not:
![grafik](https://user-images.githubusercontent.com/6639965/84253711-8b1d4880-ab10-11ea-8b95-ffdedddec945.png)

**Comment by literarymachine** [comment]
Right, this is due to the fact that the filter filters on exact (non-inherited) locations. The quick work-around is to use the country view and then filter by type and sub-type: https://oerworldmap.org/country/us?filter.about.%40type=%22Service%22&filter.about.additionalType.%40id=%5B%22https%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fservices.json%23repository%22%5D

**Comment by trugwaldsaenger** [comment]
confirmed, now 9 repositories in the US can be found, also all/most policies carry a pin
