### ISSUE TITLE
Document triple store / sparql 

### ISSUE THREAD

**Issue by gandalfar** [hbz/oerworldmap#1928]
At the moment, I think it would be useful to have some documentation about this part of the project. Maybe it could answer the following questions:

1. How to inspect/view existing data schema
2. How to inspect tags and merge them into a new field
3. How to create a new field and populate it with date (maybe just a general / high level pointer to different files)
4. Any other common activities that are run on the triple store?

**Comment by literarymachine** [comment]
> How to inspect/view existing data schema

The schema is actually expressed as a [JSON Schema](https://github.com/hbz/oerworldmap/blob/master/public/json/schema.json), instance data is interpreted as JSON-LD with a matching [context](https://github.com/hbz/oerworldmap/blob/master/conf/context.json). You can also explore data using SPARQL e.g. by listing [all RDF properties](https://beta.oerworldmap.org/sparql/query?q=SELECT+DISTINCT+%3Fp+WHERE+%7B+%3Fs+%3Fp+%3Fo+%7D) currently in use (on beta here and in the following examples).

> How to inspect tags and merge them into a new field

To list all tags in use, you can again use a [SPARQL query](https://beta.oerworldmap.org/sparql/query?q=SELECT+DISTINCT+%3Ftag+WHERE+%7B+%3Fentry+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%3Ftag+%7D). In order to update data, we also provide an [endpoint](https://beta.oerworldmap.org/sparql/update) for [SPARQL delete/insert](https://www.w3.org/TR/sparql11-update/#deleteInsert). A simple example would be change keywords, let's say from [`open educational practice` to `OEP`](https://beta.oerworldmap.org/sparql/update?delete=%3Fentry+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%22open+educational+practice%22&insert=%3Fentry+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%22OEP%22&where=%3Fentry+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%22open+educational+practice%22):

```
DELETE {
    ?entry <http://schema.org/keywords> "open educational practice"
}
INSERT {
    ?entry <http://schema.org/keywords> "OEP"
}
WHERE {
    ?entry <http://schema.org/keywords> "open educational practice"
}
```

A more complex example could be to populate the `activityField` field defined in the [schema for `Person` entries](https://github.com/hbz/oerworldmap/blob/master/public/json/schema.json#L2303) [based on the `open educational practice` tag](https://beta.oerworldmap.org/sparql/update?delete=%3Fentry+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%22open+educational+practice%22&insert=%3Fentry+%3Chttp%3A%2F%2Fschema.org%2FactivityField%3E+%3Chttps%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Factivities.json%23oep%3E&where=%3Fentry+a+%3Chttp%3A%2F%2Fschema.org%2FPerson%3E+.+%3Fentry+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%22open+educational+practice%22+.):

```
DELETE {
    ?entry <http://schema.org/keywords> "open educational practice"
}
INSERT {
    ?entry <http://schema.org/activityField> <https://oerworldmap.org/assets/json/activities.json#oep>
}
WHERE {
    ?entry a <http://schema.org/Person> .
    ?entry <http://schema.org/keywords> "open educational practice" .
}
```

> How to create a new field and populate it with date (maybe just a general / high level pointer to different files)

New fields can be added by defining them in the [JSON Schema](https://github.com/hbz/oerworldmap/blob/master/public/json/schema.json) which is also the basis for our input templates.

**Comment by gandalfar** [comment]
For my reference:

**Query to list all tags:**

`SELECT DISTINCT ?tag WHERE { ?entry <http://schema.org/keywords> ?tag }`

Or to list entries that use tag `"Open Data"`

`SELECT ?entry WHERE { ?entry <http://schema.org/keywords> "Open Data" }`

**Comment by literarymachine** [comment]
> Or to list entries that use tag "Open Data"
>
> `SELECT ?entry WHERE { ?entry <http://schema.org/keywords> "Open Data" }`

Note that this query is case sensitive. Use the following to also get results for `open data`:

```
SELECT ?entry WHERE {
  ?entry <http://schema.org/keywords> ?tag .
  FILTER (lcase(str(?tag)) = "open data") .
}
```

which will give you the same results as when querying the [JSON API](https://oerworldmap.org/resource/?filter.about.keywords=%5B%22Open+Data%22%5D&ext=json&size=-1).
