### ISSUE TITLE
Email Cloaking

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1936]
Email cloacking (e.g stmartin [dot] oer [at] gmail [dot] com) on published e-mails to protect them from automated harvesting and spamming

**Comment by gandalfar** [comment]
Looking at entries like these: https://oerworldmap.org/resource/urn:uuid:b97fabb5-af3f-47c9-8535-a02cfe7d3113

I see there is already base64 encoded email for mailto: link. I guess, I could try to also modify it, so that it's also decoded once it gets displayed. 

(I'll also have to figure out how server-side react rehydration works. If it rerenders everything or if it's smarter than that.)

**Comment by literarymachine** [comment]
> I see there is already base64 encoded email for mailto: link. I guess, I could try to also modify it, so that it's also decoded once it gets displayed.

I don't really see a necessity to change things here in the markup. The email address is encoded when rendered by the server and only decoded on click. @trugwaldsaenger did you get any complaints about emails being harvested from us?

Another question would be the API because email addresses are in the JSON.

**Comment by trugwaldsaenger** [comment]
The issues was originally proposed by Santiago. I did not receive any concrete complaints. 

>The email address is encoded when rendered by the server and only decoded on click.

I understand, that we have a mechamism in place, which reduces possibilities to harvest and spam mail adresses by users. So the problem might be that users (including me) are not aware of this, which might scare them to share their address. Could adding a short help text to the e-mail field in the template ("Your password will be encoded and protected agains abuse") be the right way to approach this issue?

**Comment by gandalfar** [comment]
@literarymachine only mailto: part of href is encoded. The text part contains email but it's not encoded.

**Comment by literarymachine** [comment]
> only mailto: part of href is encoded. The text part contains email but it's not encoded.

Right, sorry I overlooked that! Then I would say

**Comment by gandalfar** [comment]
This is now fixed and in production.
