### ISSUE TITLE
Inconsistend behaviour using statistic gadgets

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1948]
For OERinfo we are currently working on a site, which shows statistics on the German OER landscape:
http://blog.oer-infostelle.de/materialien/oer-in-zahlen/

The chart "OER Plattformen in den Bundesländern" should show the number of repositories per state:
![grafik](https://user-images.githubusercontent.com/6639965/91461082-e1d12d80-e888-11ea-8555-b47fcd0b577a.png)

The presented numbers are inconsistend:

1. When hovering over the chart, it announces 2 entries for Baden Württemberg
![grafik](https://user-images.githubusercontent.com/6639965/91461473-57d59480-e889-11ea-8c74-ea233e75a21a.png)

1. When clicking on the chart segment, this should provide 2 entries. Instead I receive 166 hits:
![grafik](https://user-images.githubusercontent.com/6639965/91461766-adaa3c80-e889-11ea-9e98-03317d802285.png)
https://oerworldmap.org/resource/?filter.about.%40type=%22Service%22&filter.about.additionalType.%40id=%5B%22https%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fservices.json%23repository%22%5D&filter.about.location.address.addressRegion=%5B%22DE.BW%22%5D&q=about.location.address.addressRegion%3ADE.*&language=en

1. After activating the "region" filter in the search interface, I receive 5 hits:
![grafik](https://user-images.githubusercontent.com/6639965/91462057-07ab0200-e88a-11ea-8e41-7d0d281054a8.png)
https://oerworldmap.org/resource/?filter.about.%40type=%22Service%22&filter.about.additionalType.%40id=%5B%22https%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fservices.json%23repository%22%5D&filter.about.location.address.addressRegion=%5B%22DE.BW%22%5D&q=about.location.address.addressRegion%3ADE.*&language=en&filter.feature.properties.location.address.addressRegion=%5B%22DE.BW%22%5D

**Comment by literarymachine** [comment]
The problem here is once again our two different concepts of location:

- `filter.about.location.address.addressRegion` refers to "direct" (non-inherited) locations
- `filter.feature.properties.location.address.addressRegion` includes "indirect" (inherited) locations

While both can be used in the visualizations, only the latter works when linking to in the search result list. The former is simply ignored in this case, because `filter.about.location.address.addressRegion` is unknown to the UI. The 166 search results are simply all Services of the type Repository.

How are the visualizations included in http://blog.oer-infostelle.de/materialien/oer-in-zahlen/? It seems that the SVG code has been directly copied into the source of the page? If this is the case, the data is going to be inconsistent in the long run anyways because the SVG is a snapshot but links to our live data.

I believe a better approach is to first apply the following filters:

![image](https://user-images.githubusercontent.com/149825/91478495-4481f380-e8a0-11ea-90c3-14400dd414f4.png)

Then switch to the statistics view:

![image](https://user-images.githubusercontent.com/149825/91478587-6d09ed80-e8a0-11ea-8d2d-04e489550728.png)

Scroll down until you find the statistic you want:

![image](https://user-images.githubusercontent.com/149825/91478619-7a26dc80-e8a0-11ea-9fb9-89ccd9a44116.png)

And finally just copy the image URL using the corresponding button:

https://oerworldmap.org/stats?field=feature.properties.location.address.addressRegion&filter.about.@type=%22Service%22&filter.about.additionalType.@id=%5B%22https%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fservices.json%23repository%22%5D&filter.feature.properties.location.address.addressCountry=%5B%22DE%22%5D

You can then embed that image using a simple `img` tag, or to keep the links clickable using an `object` tag, see https://codepen.io/literarymachine/pen/QWNvrYY

**Comment by trugwaldsaenger** [comment]
May thanks for your quick answer @literarymachine !

**Comment by trugwaldsaenger** [comment]
After speaking with @literarymachine I understand following points:

1. We do have two fields for "region". One field is connected to the inheriting mechanism, the other one is a free text field. Currently our search interface supports only using the field with the inheriting mechanism.
2. As shown in https://codepen.io/literarymachine/pen/QWNvrYY there are two ways to include statistics into a web site, either as an image or as an object. Interactivity of the chart is only provided, when the chart is included as an object. We are currently checking how implementation was done in the present case (http://blog.oer-infostelle.de/materialien/oer-in-zahlen/).
3. Integration of interactive charts can only be guaranteed if filters are used, which are currently available via our search interface.

**Comment by trugwaldsaenger** [comment]
Closed
