### ISSUE TITLE
Security certificate for beta website expired?

### ISSUE THREAD

**Issue by st-martin** [hbz/oerworldmap#1991]
I'm getting error messages from different web browsers when attempting to connect to <https://beta.oerworldmap.org/> that may be related with the security certificate. I've used both Firefox 83.0 and Chromium 87.0.4280.66 on Fedora Linux (64-bit). The problem happens regardless attempting to connect via HTTP or HTTPS and cannot be skipped.

The error messages I'm getting are:
Firefox:

> Did Not Connect: Potential Security Issue
> 
> Firefox detected an issue and did not continue to beta.oerworldmap.org. The web site is either misconfigured or your computer clock is set to the wrong time.
> 
> It’s likely the web site’s certificate is expired, which prevents Firefox from connecting securely.
> 
> What can you do about it?
> 
> beta.oerworldmap.org has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.
> 
> The issue is most likely with the web site, and there is nothing you can do to resolve it. You can notify the web site’s administrator about the problem.

Chromium:

> Your connection is not private
> Attackers might be trying to steal your information from beta.oerworldmap.org (for example, passwords, messages or credit cards). Learn more
> NET::ERR_CERT_DATE_INVALID

**Comment by gandalfar** [comment]
Thanks for reporting this. I think @dr0i is correct person to update beta.oerworldmap.org HTTPS certificate.

**Comment by dr0i** [comment]
Wrote to internal IT, await answer.

**Comment by dr0i** [comment]
Signed certificate today, await the certificate to be generated by DFN.

**Comment by dr0i** [comment]
Security Certificates renewed. @st-martin and @gandalfar please check.

**Comment by gandalfar** [comment]
@dr0i it seems ElasticSearch index broke on Beta as part of ssl change (or maybe due to something else):

```{"responses":[{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"oerworldmap","index_uuid":"_na_","index":"oerworldmap"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"oerworldmap","index_uuid":"_na_","index":"oerworldmap"},"status":404}]}```

**Comment by dr0i** [comment]
This index is also missing at production:

> curl http://localhost:9200/oerworldmap/_search?q=*
{"error":{"root_cause":[{"type":"index_not_found_exception" ...

Both ES instances have the index `oerwm` and `beta.oerwm` (ah, I remember, they are in the same cluster!), though.
ES running since Jan 21.

Ah, got it I think:
despite proper config in `conf/application.conf`: `es.index.name="beta.oerwm"` there is the `elasticsearch proxy`-RewriteRule in `vhost.conf`, which was on `beta` configured like this:

>  RewriteRule ^/elastic/_search(.*) ${ELASTICSEARCH_HOST}/oerworldmap/_search$1 [P,L]

Substituted `oerworldmap` with `beta.oerwm` , restarted apache and it look ok, right @gandalfar ?

I suspect that at some point in history the `vhost.conf` was correctly configured, but then (at least since 14. September 2020 15:04, as there is a copy named `vhost.conf.orig`) the entry was set falsely to `oerworldmap` but the apache was not restarted and so everything worked ok.

**Comment by gandalfar** [comment]
@dr0i seems to be working correctly now. Thanks for investigating and fixing the issue.
