### ISSUE TITLE
Create ISCED as SKOS

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#220]
Based on the PDFs because classifications in structured, machine-readable format don't (yet) exist, see #175.

**Comment by acka47** [comment]
Needed for #40 and #41. Background: Discussion thread on the mailing list https://listen.hbz-nrw.de/pipermail/oerworldmap/2015-January/000000.html.

PDF documents (English) that serve as basis for SKOS scheme:
- ISCED 1997 Levels of Education: http://www.uis.unesco.org/Library/Documents/isced97-en.pdf
- ISCED 2013 Field of Education: http://www.uis.unesco.org/Education/Documents/isced-fields-of-education-training-2013.pdf

**Comment by acka47** [comment]
I would like to do this with support of a dedicated tool. [iQvoc](https://github.com/innoq/iqvoc) seems to do the job and it also looks like it is still maintained. I tried to set it up on heroku as described in the [readme](https://github.com/innoq/iqvoc/blob/master/README.md). Though it says "You can easily setup your iQvoc instance [on heroku] in under 5 minutes, we wanted to make this process really easy.", I wasn't able to do it in two hours. I guess the 5 minutes only hold for ruby developers – and I am no developer at all.
Will need some help on this...

**Comment by acka47** [comment]
Tried it once more to set up iQvoc on heroku. I didn't work. Filed an issue at https://github.com/innoq/iqvoc/issues/343. Maybe I get some help there.

**Comment by literarymachine** [comment]
Task for #118.

**Comment by acka47** [comment]
With @philboeselager help, I got iqvoc running, see https://iqvoc4isced.herokuapp.com/.

**Comment by acka47** [comment]
I created the SKOS version of ISCED-2013 (currently only with English labels) in this iqvoc instance: https://isced2skos.herokuapp.com/en/scheme.html 

I suggest creating a namespace at w3id.org (already pulled the repo, see https://github.com/hbz/w3id.org) and adjusting the RDF accordingly and then publishing it with Skosmos (see https://github.com/hbz/lobid/issues/209). I think we can then use the Skosmos API within the web form for adding services. What do you think, @literarymachine? And – provided that you agree – when will you need the data in Skosmos.

**Comment by literarymachine** [comment]
> I suggest creating a namespace at w3id.org (already pulled the repo, see https://github.com/hbz/w3id.org) and adjusting the RDF accordingly and then publishing it with Skosmos (see hbz/lobid#209).

The README at https://github.com/hbz/w3id.org states that links will be checked, and I assume they mean before the merge the Pull Request. So I guess the vocab has to be published when you create the Pull Request.

> I think we can then use the Skosmos API within the web form for adding services. What do you think, @literarymachine?

This looks good, since the API apparently uses JSON-LD as its primary format! The only question would be if would like the w3id.org-IDs to eventually resolve to oerworldmap.org-URIs. But we could perhaps solve this using proxy-rewrites. Besides that, Skosmos does need a SPARQL triple store in the background. I guess we could also simply index SKOS vocabularies in ES.

> And – provided that you agree – when will you need the data in Skosmos.

Given the rather small size of ISCED-2013, I am currently thinking about doing client-side auto completion. This would defer the need for Skosmos until we have a vocabulary of such a size that justifies additional technologies, at least from the point of the web forms. Like I stated above, the URIs should be resolvable when you create the Pull Request for w3id.org.

**Comment by acka47** [comment]
I created a new repository for ISCED, see https://github.com/hbz/isced. SKOS versions of isced-1997 and isced-2013 can be found there. For the record: I had some problems getting the data out of iqvoc (export didn't work) and manually adjusted the RDF, e.g. for the concept URIs to look prettier. Today, I also used [skosify](https://github.com/NatLibFi/Skosify) for isced-2013 to validate and enrich the scheme.

Closing this issue for now and opening another one for presenting the vocabs with skosmos (https://github.com/hbz/isced/issues/6).
