### ISSUE TITLE
Do we need a special contact page?

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#241]
Right now we have several sub-pages, including "About us" and "Legal". I`m wondering if we should include an additional page "contact" which shows our contact information. Also it could include the contact information of the "regional points of contact".

**Comment by karindr** [comment]
I would suggest to establish a contact page. People are used to find certain informations on this page. When visiting the websites of the OER services I’m always glad to find a contact page and haven’t to look everywhere for email and address etc.

**Comment by philboeselager** [comment]
It depends on what would be provided on a such contact page. If we are only going to provide an info@ email address, we wont need a dedicated contact page. (Because this is absolutely standard and you can even find this address on our [imprint page](https://oerworldmap.org/imprint).)

**Comment by formimkontext** [comment]
i agree with @karindr. i think a contact page would be helpful for the user. maybe we can merge the contact page with the imprint page.

**Comment by karindr** [comment]
There should be a link on every page that is named "Contact" because people are used to look for this. This might be a link together with imprint but at the moment we have for legal reasons "Imprint&Privacy". We could change this to "Contact, Imprint&Privacy" but it is not very elegant.

We should not think that people know they could find the contact information on the imprint page because the imprint page is not as common as we Germans think. When I do research for the map I think only about 30% of foreign websites have imprint information on it!

**Comment by karindr** [comment]
Jan Schallaböck writes that it doesn't have to be named "Imprint" "Contact&Privacy" would be ok,

**Comment by formimkontext** [comment]
On the last team-meeting we decided to implement a news- and a contact-page. And we agreed on simplify things and reduce the content and UI elements to its essentials. And since we have to add some more legal attribution (mapbox and openstreetmap) to the map, we might integrate the Contact/Privacy-Link into the main menu. To restructure the main menu would be another issue.

**Comment by dobladov** [comment]
At the current moment, we have a link **Contact** pointing to _info@oerworldmap.org_ in the header, we still need a separate contact page or we can close the issue?
![image](https://user-images.githubusercontent.com/1938043/49586133-93ffed80-f960-11e8-84da-8ffda4ed9ce4.png)

**Comment by literarymachine** [comment]
> Do we need a special contact page?

No.
