### ISSUE TITLE
Make a map query citable

### ISSUE THREAD

**Issue by drrobertfarrow** [hbz/oerworldmap#258]
As an OER WM user I want to be able to run queries on the data in such a way that I can produce a citation that can be used for academic papers, reports, etc.

e.g. OER World Map (year). [QUERY TITLE]. [URL/DOI].  Accessed [DATE OF ACCESS]

A button could be used to generate a citation - but in the first instance manual guidance could be provided in the FAQ 

NB synchronicity with #254

**Comment by drrobertfarrow** [comment]
TO DO: write something for the FAQ on suggested citation protocols for OER World Map.

**Comment by philboeselager** [comment]
Could be implemented as an additional database with mapping time-stamped URLs to query results, like:
https://oerworldmap.org/resource/?q=&filter.about.%40type=Service&filter.about.location.address.addressCountry=CO&2016-09-09-11-17-25-CEST

In order to not let this database become too crowded, a query result site could comprise a button called like "Make this query result citable" which triggers the result's storage.

**Comment by philboeselager** [comment]
related to #600

**Comment by literarymachine** [comment]
Inactive, closing.
