### ISSUE TITLE
Ghost pin evoking strange frontend behaviour

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#353]
- Click on https://beta.oerworldmap.org/country/za
- Zoom out
- Try to click the pin in the Atlantic, near Canary Islands
- The pin disappears
- Move over some country and they we all stay marked 
- Click another country and the strange behaviour stops

**Comment by literarymachine** [comment]
It turns out that both the placement of the pin and it disappearing on mouse over can be traced back to errors in the data: the `@id` is missing the `urn:uuid:` prefix, and `lat` and `lon` are mixed up for [Mindset Network].

[Mindset Network]: https://beta.oerworldmap.org/resource/4f5b1946-41af-11e5-804c-001999ac7927

**Comment by literarymachine** [comment]
Disappearing pin fixed on beta. @acka47 please fix data errors manually.

**Comment by acka47** [comment]
Thanks for the pointer. I already thought that it probably has something to do with the data. Couldn't track it down, though. Fixed the errors. Closing.
