### ISSUE TITLE
Different borders shown

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#365]
Zooming into the map anywhere one will see that two different kinds of borders are shown. One being more precise than the other. See this screenshot for example:

![double-borders](https://cloud.githubusercontent.com/assets/160292/9809720/0d34edd0-586b-11e5-80dd-103422d3684c.png)

I guess one border stems from the original coloured map and the other came in with https://github.com/hbz/oerworldmap/commit/e42e86a40d297a6c455d4b968d165fad53708dcf. Somehow this should be reduced to one type of border.

**Comment by literarymachine** [comment]
> I guess one border stems from the original coloured map and the other came in with e42e86a.

You are right. One border comes from the vector map, the other from the raster map. We cannot make the vector data as exact because this would result in a big GeoJSON file. As far as I can tell, the situation is as follows: if we remove the the border of the vector (heat) map, the colors of the countries will still potentially spill over the borders on the raster map. If we remove the borders of the raster map, we loose the sub-national divisions. I will discuss this with @j0hj0h, but assume that the priority of this is not huge?

**Comment by j0hj0h** [comment]
Yes I've thought about this. The borderlines used for the heatmap are rendered from one wordwide dataset, loaded in the beginning. This has limited detail, otherwise it would be to large. The other layer is rendered by zoomlevel and always has perfect detailed shapes.

There are three solutions for that:
1. Hide the heatmap on higher zoomlevels (easy)
2. Hide the countryborders in the raster layer (difficult, if we still want to keep the province borders)
3. Load the heatmap vector borders also by zoomlevel (We tried around with that a bit ... and didn't get it working yet. This is a bit bleeding edge. I'd love to work on that, but guess there are a lot other more urgent things.)

**Comment by acka47** [comment]
Fixed. Closing.
