### ISSUE TITLE
Pins disappeared

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#376]
Most pins disappeared - right now there are only 3 pins left.

**Comment by acka47** [comment]
This is the result of the paging mechanism implemented within https://github.com/hbz/oerworldmap/pull/369. The pins are correct as the ten resources on the first page obviously only include three geo locations.

**Comment by literarymachine** [comment]
It is indeed a result of the paging. Only pins for those resources in the current result page are displayed. If we want all pins there all the time, we might as well remove the pager again because then we have to fetch all data anyways. At least for the time being - I'll try to come up with a reasonable result format that is small enough to be performant but includes all data necessary to populate the map entirely.

On the other hand it could be argued that displaying only pins for the current result page is actually not that wrong.

**Comment by trugwaldsaenger** [comment]
I think we`ll have to provide at least an initial full view. If you get to the world map, I think you exspect to get an overview. 
>On the other hand it could be argued that displaying only pins for the current result page is actually >not that wrong.
I see some value in this as well, but I`m not sure, about the implications for the usability here. I guess we should discuss this issue a little bit more in detail...

**Comment by acka47** [comment]
Looks good on beta now.

**Comment by trugwaldsaenger** [comment]
Seems to be solved on producation. @literarymachine: Should we close the issue?
