### ISSUE TITLE
Alias @type, @id 

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#418]
We decided to do this in lobid API 2.0. It makes sense to use a common practice in hbz products.

Accodring to https://github.com/schemaorg/schemaorg/issues/854 this is a general emerging best practice.

**Comment by philboeselager** [comment]
Following the discussion in https://github.com/schemaorg/schemaorg/issues/854 , pros and cons of avoiding the '@' in JSON-LD keywords basically scale. Since the main reason points out to be comprehensibility, I would argue that keeping the '@' causes no problem for the oerworldmap, especially since everybody involved here knows its meaning. I would like to keep the '@' as it is semantically clarifying. (Of course the benefits of avoiding '@' may prevail in the lobid API case.)

@acka47 Or do I miss a concrete point?

By the way, the argumentation of not using a term or word in one language, just because it means something different in another language, is a bit weak IMO. One should never use the word "Gift" in neither English nor German then, would they?

**Comment by acka47** [comment]
Talking to @literarymachine some time ago he was also in favor of aliasing `@id` and `@type`. It would also make for nicer URLs without escaped characters, e.g. `https://oerworldmap.org/resource/?q=&filter.about.type=Service` instead of `https://oerworldmap.org/resource/?q=&filter.about.%40type=Service`...

**Comment by literarymachine** [comment]
> It would also make for nicer URLs without escaped characters

Chatting with @philboeselager just now, I couldn't really remember any other reason than that. Which would make this a really low priority for me...
