### ISSUE TITLE
Include Anti-Spam technique to Country Champion addresses

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#427]
Matteo, our Italian country champion proposed that we show the mails-adresses like this:
name[REMOVE]organization.com
I think this is a very understandable proposal. We should include something like this ASAP. @acka47: Is this something we have to do manually?

**Comment by acka47** [comment]
>  Is this something we have to do manually?

I don't think so, but the ideal person to answer this is @literarymachine. Thus, assigning him.

**Comment by literarymachine** [comment]
Is Matteo actually experiencing increased spam? Because this is something we have taken care of. While to the human, the email address is exposed readable, it is not so under the hood. Check out the page source (CTRL+u in most browsers) of https://oerworldmap.org/resource/urn:uuid:86365dfe-15ae-11e5-83b8-001999ac7930 for example, where the email address is exposed as
    mailto:&#104;&#117;&#101;&#64;&#103;&#114;&#101;&#121;&#115;&#112;&#97;&#114;&#107;&#108;&#101;&#46;&#99;&#111;&#109;

The JSON in the API on the other hand does contain the unencrypted email address, and this JSON is also embedded in the HTML page. I am unsure whether this poses a problem, though.

**Comment by literarymachine** [comment]
Fixed by https://github.com/hbz/oerworldmap-ui/commit/1c595ceb1e47a152c36f6174e3e16fbfea9bc4e0
