### ISSUE TITLE
Define optional and obligatory fields for different entity types

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#434]
Currently, we don't have a lot obligatory fields defined. We will need to define the "core entry" for different entity types. (Related to #433 .)

**Comment by acka47** [comment]
Here is my list of required fields for the different types (leaving out `@type` and `@id` which are automatically set by the system).

**Action**: name, description, agent (We _might_also include  as required field: startTime)

**Service**: name, description, availableChannel.serviceUrl (We _might_also include  as required field: serviceType)

**Person**: name, description, location.address.addressCountry

**Organization**: name, description

**Event**: name, description, startDate, endDate

**Comment by karindr** [comment]
I agree to  @acka47 . But I suggest to skip the agent for **project** because you can't finish your entry if you did not create the entry for the agent first, but nobody knows that before. And sometimes we are entering data for subprojects and don't have the information about the agent on the same list.

In addition there are **stories**, see #774 and #938: 
Stories need to have an author, a datecreated, a description (=teaser) and a articlebody (=text)

At the team meeting in Berlin we decided to make the **country field obligatory for all** the types of entries here to make them visible on the map and to enhance the localisation. See also #1123. If ther is a link to an organisation or person for service and project there is no need to enter a country.

The **new type publication** needs to have a title, an url to link at. This is the only type without localisation and for this reason without obligatory country

**Comment by literarymachine** [comment]
> If ther is a link to an organisation or person for service and project there is no need to enter a country.

"If there is (any!?) link to some person or organisation, it's ok, but if not you need to fill out the location in the field down there which is hidden by default": This is both hard to model in a schema and to communicate to users.

**Comment by literarymachine** [comment]
> This is both hard to model in a schema

@acka47 good news is that JSON schema actually allows for this; instead of simply using

```
"required": [
  "name", "description", "availableChannel"
]
```

you use a construct such as this:

```
"allOf": [
  {
    "required": [
      "name", "description", "availableChannel"
    ],
    "oneOf": [
      {
        "required": [ "location" ]
      },
      {
        "required": [ "provider" ]
      }
    ]
  }
]
```
> and to communicate to users

Trying to figure this out now while generally working on improving error reporting.

**Comment by literarymachine** [comment]
On beta.

**Comment by karindr** [comment]
+1

There is a space before the point at the end of the error message, please delete it.

Is it possible to sort the missing items in the error message the way they are sorted in the presentation (which will be the sorting of the template as well)?

I suggest to write "at least the country" instead of "location" because we don't want to stop people from saving an entry who could not find an address at the moment of entering.

**Comment by karindr** [comment]
See also related #1160.

**Comment by acka47** [comment]
I would like to test this but beta.oerworldmap.org is currently so slow and unreliable for me that I have to wait until it runs smoother again.

**Comment by literarymachine** [comment]
> Is it possible to sort the missing items in the error message the way they are sorted in the presentation (which will be the sorting of the template as well)?

Not out of the box. I suggest we deal with this when we rewrite the component and move the error messages directly to the inputs.

> I suggest to write "at least the country" instead of "location" because we don't want to stop people from saving an entry who could not find an address at the moment of entering.

The error messages are automatically generated from the schema validation errors. The descriptions are taken from the field names. The field is `location`, which points an object that has at least `address > addressCountry`. I suggest to implement #1123 which should clarify that a `location` only needs a country to be valid.

**Comment by literarymachine** [comment]
> I would like to test this but beta.oerworldmap.org is currently so slow and unreliable for me that I have to wait until it runs smoother again.

This is a very absurd bug that @j0hj0h and I are looking into now: #1164. For some reason, when a value of `1000` is encountered, the map hangs. Fixed on beta now, please carefully choose dates and other values though when testing for now.

**Comment by literarymachine** [comment]
> There is a space before the point at the end of the error message, please delete it.

Because of how the text message is built from the original schema error, the easiest thing was to simply remove the period. Hope that's ok.

**Comment by acka47** [comment]
+1

**Comment by literarymachine** [comment]
@acka47 FYI I removed the requirement of `description` for `Person` because it broke our registration (which validates against the schema):

![screenshot from 2017-04-04 17-25-59](https://cloud.githubusercontent.com/assets/149825/24664982/52f69a2c-195c-11e7-8f12-4b8ea0da7db8.png)
