### ISSUE TITLE
Provide structure and order for view of different entity types

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#482]
We haven't put much thought yet into the views of the different entity types.

I started thinking about it for `Event` type in https://github.com/hbz/oerworldmap/issues/464#issuecomment-161977290:

> I think some restructuring of the view would make sense though: Beneath the title we should directly show the date and the location followed by the description. Beneath that, the more specific other information should follow. 

We will have to look at other entries as well and keep in mind that views for different types are consistent.

**Comment by karindr** [comment]
I collected my ideas on this and put them to the team wiki:
[https://wiki1.hbz-nrw.de/display/OWM/OER+World+Map+Team+Wiki](url)
(Bad idea, can't link to it directly: Ideas on "Provide structure and order for view of different entity types 482" and the colors are only seen in the doc file ...)

**Comment by acka47** [comment]
I adjusted the link in your comment and also added colouring in the wiki.

**Comment by acka47** [comment]
I adjusted some things:

- switch language and subjects for services and events as the subject list can be very long
- move location of event up to have location, date (e.g. "Cologne, 2016-08-21 to 2016-08-23")
- for projects, I moved the start/end date up to the top of the list. i think it is quite important to asses the relevance of a project

**Comment by acka47** [comment]
Generally, we shouldn't list "profiles elsewhere" as a separate line but only put the logos of the services with underlying links somewhere, maybe in the upper right corner of the profile. I'll make an issue for this.

**Comment by formimkontext** [comment]
In the current drafts links to "profiles elsewhere" are already shown as a logo bar as part of the table below the article. The upper right corner should be the place for buttons or actions relating to the content of the entity (e.g. export, share, print).
We should be aware of the fact, that there won’t be an icon for every profile elsewhere included in the icon font we are using.

![20160411-oer-world-map](https://cloud.githubusercontent.com/assets/15141949/18133361/9b02a048-6f9a-11e6-91bf-cb9e2f79b11e.jpg)

**Comment by karindr** [comment]
Looks good!
If there are links to profiles we have no icon for, I think, the link should be placed at the end of the table, because it must be a profile not very common.
@formimkontext, I would prefer when the icons weren't placed in the middle but justified to the left like all other elements (except the image).

**Comment by trugwaldsaenger** [comment]
@formimkontext: have you already started working on this? 
If not I would like to discuss this issue one more time. I had a details discussion with @karindr about the current proposal yesterday. We agree on the point, that the displayed field order should be identically to the order of the input templates. 

I can also understand the underlying approach of the concept, which aims at putting the most important information more up. Since different fields are of different importance for different data types, this results in a different structure for different data types. Two examples for this:

1. For events time and location are very important. So this information should be displayed first.
2. For services it is important what subjects are included and in which language the ressources are, which are provided by the service.

Conflicting with this approach is another approach, which provides orientation to the user, by making groups of fields and using the same structure for the fields as far as possible. I started to make a sketch in a google spreadsheet: https://docs.google.com/spreadsheets/d/16g81Z1VuLG9M0HiAETNGaf-T12EBX2CWppAkauF0zYs/edit#gid=1862561132

I think at this stage of development it might be better to follow this kind approach for several reasons:

1. It is easier to get an overview on all included fields, not only for the user, but also for us, which makes quality assurance easier. As long as our data model is still developing, I consider this an important aspect.
1. We do have the opportunity to include something like a sub headline as can be seen in the screenshot included in this ticket. With this sub-headline we could highlight important information, e.g. the date and location (town) for events.
1. If we have consistant groups, it is more easy to develop a collapsable input template, which only shows the most important fields in order to avoid exspecting too much from the user. The groups could work as a toc for the fields.
1. Until now, we do not know precisely what information the user needs most. It makes sense, that the subjects will be of high importance. But on the other hand this is less important, if the user used the subject filter first. 

I`m not sure which way is the best way to proceed. Both seem reasonable to me. I would be interested what @formimkontext are thinking about this.

**Comment by formimkontext** [comment]
I don’t know if ths is the right place for this, but i think we should:

- set a limit to the number of characters in a headline. 
- integrate a subheadline for longer descriptions / the alternate name. 

Otherwise we will have headlines like this: https://oerworldmap.org/resource/?q=mat3#urn:uuid:5f023a27-3975-41a6-bd29-b94970b7bc9d

By subheadline i don’t mean the typespecific information (e.g. start date, end date of events) we used to call subtitle. This will be another line below the subheadline.

**Comment by karindr** [comment]
I don't know if it is a good idea to limit the length of the headline. Especially Projects often have long and "official" Names. I think it would not be easy to cut them into halves. See also:
https://oerworldmap.org/resource/urn:uuid:4b00515b-5e9a-4549-ab9e-b29e569ed972
It is not nice but it is correct.

**Comment by formimkontext** [comment]
It might be correct but not very user-friendly. Longer lines wouldn’t help you to select and apprehend information. To cut this information to a (short) headline and a (longer) subheadline could be even useful for the presentation in the search result list. Maybe we can introduce a subline there too.

**Comment by karindr** [comment]
I have created an order of fields following the three rules we decides on during the last team meeting. The list can be found on google docs, links below. They can be used for sorting the fields.
The rules were: 

1. This order follows the rule that the order should be the same for all entries. Because the different categories have lots of different fields it would not always look as if it was the same order but that is inevitable.
2. The second rule was to cluster similar information to blocks (the headings written in [] mark these blocks here in the list, these headings should not be displayed).
3. The third rule was the decision to emphasis the networking function of the OER World Map (what we decided in the last team meeting) so the contact block is the first block following the header.

List for Overview: https://docs.google.com/document/d/1e_SezYhhGMdPe4h8q9_xCI1CgmNvVecKAiqX7f6_TrY/edit?usp=sharing
Complete list with variable names and names in templates and profiles:
https://docs.google.com/spreadsheets/d/1XycxHG1hCn21NTzfGt8U1BymwIbz-Rbt0eH3WPPmJ4Q/edit?usp=sharing

**Comment by j0hj0h** [comment]
@karindr: I reworked the template, following your [list](https://docs.google.com/document/d/1e_SezYhhGMdPe4h8q9_xCI1CgmNvVecKAiqX7f6_TrY). some notes:

- I followed the order but didn't separate the sections so far. (Did we talk about seperating them visually? I'm not sure.)
- I put results – `Action.result` ("Resulting service") and `Service.resultOf` ("Project(s) the service was developed in") – at the end of content, as you listed it. But it's actually a link. I assume you put it there no purpose.
- I put `Action.instrument` ("Service used") and `Service.instrumentIn` ("Projects using the service") at the end of the links section. You didn't mention it in the list, there is no data provided for this field in any entity, but it is in the schema and in the edit form. So I assume it was setup, but not used yet? @acka47 
- For future correspondence about the data fields you could also have a look at the file [conf/labels.properties](https://github.com/hbz/oerworldmap/blob/master/conf/labels.properties), where we have the tranlations from the actual fieldnames to the labels in the templates. I'm not saying this is a must, but maybe you can get familiar with it, which might make the communication more precise.

Changes are not visible yet ... we'll let you know, when pushed to beta or production.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:e08975fe-acc0-4733-8496-2cfc034a120a

**Comment by acka47** [comment]
Looks quite good. I let @karindr check the details as she did most work on the structure. I noticed one thing that has to be improved: the alternate name is currently shown in brackets in the heading as well as later as single field. The second should be removed.

**Comment by literarymachine** [comment]
> The second should be removed.

Ah ok. We decided to put everything in the table, too. Because you cannot really see it as a field in it's own right if it is only shown e.g. in the title in brackets or as a location in the sub heading.

**Comment by acka47** [comment]
> Ah ok. We decided to put everything in the table, too. Because you cannot really see it as a field in it's own right if it is only shown e.g. in the title in brackets or as a location in the sub heading.

Yes, that's right. People might get confused. Adding the abbreviation in brackets to the title might already confuse people as it is the first step where the display diverges from the input. Hmm, I have to think about this. let's see what @karindr has to say.

**Comment by karindr** [comment]
> I followed the order but didn't separate the sections so far. (Did we talk about seperating them visually? I'm not sure.)
We did not decide this. I think we should start without separation because often there will be only one entry per section and then it will look strange to have a stronger separation. 

> I put results – Action.result ("Resulting service") and Service.resultOf ("Project(s) the service was developed in") – at the end of content, as you listed it. But it's actually a link. I assume you put it there no purpose.
Since I didn't have the definition I thought of these as reports. @j0hj0h you are right as Links they belong to the link section and should be displayed on the top of this section.

> I put Action.instrument ("Service used") and Service.instrumentIn ("Projects using the service") at the end of the links section.
I agree to this.

> Yes, that's right. People might get confused. Adding the abbreviation in brackets to the title might already confuse people as it is the first step where the display diverges from the input. Hmm, I have to think about this. 
We had often reactions from peoples who wanted to see their organisations abbreviation also in the title. So I don't think they will be confused to see it there. I think we should display the information only at this place because the place is prominent enough.

I am at the moment looking at the different data types on beta and will put a comment here after that.

**Comment by karindr** [comment]
(You can see all types of entries with all types of connections on beta looking at the entries with “Struktur” in their title. But keep in mind that nearly no real entry has all of these fields!)
In general:
@j0hj0h : I think we decided to use only the icons for the profiles elsewhere so there will be only one line of icons instead of the lists.
Could we get rid of the “DE.NW”-line in the address, please? And put the Zip code in the same line as the town?
There could be a stronger line at the end of the link section before the comments because this is something really different.

Person:
https://beta.oerworldmap.org/resource/?q=structur#urn:uuid:701c2bae-c918-45af-85dd-7805ad83ccab
 @j0hj0h : In my opinion there should be a slightly bigger font or bold or semibold used for the subtitle “Country champion of”. At the moment it seems more to be part of the description than to be a subtitle.

Organisation:
https://beta.oerworldmap.org/resource/urn:uuid:eb803f73-bbaf-422e-9c53-db7462680212
Country champion subtitle see person
Abbreviation/ Alternate name should only appear in the title.

Project:
https://beta.oerworldmap.org/resource/urn:uuid:8fe20c33-66d0-4dac-8f81-aa18999954f2
Naming both time and operator in the subtitle is too long. I suggest to use one of them (maybe time) or skip both and use no subtitle because projects often have long titles.
Abbreviation see organisation.
It looks a bit strange that “Budget” is a number between all the links in this section but it belongs to “Funded by”. I think both entries (Funded by and Budget) should be moved behind “Operator” and “Partner” so we have the related organisations all in one place followed by the linked projects.

Service:
https://beta.oerworldmap.org/resource/urn:uuid:1a780c44-2b25-4159-a6fb-d9aac4c7a9d0
I have no opinion whether the provider is so important to put him in the subtitle. What do you think  @acka47 ?
Abbreviation see organisation.

Event:
https://beta.oerworldmap.org/resource/urn:uuid:6dd760a6-d841-4e24-be46-04e2a2c3ff5b
I like the subtitle here.
Please move “Hashtag” from its place to the place before “Tag”. I thought it would be better to keep them separated a bit but it looks rather strange.

All together I think it is much better now. The templates will follow this order in a next step too?

**Comment by literarymachine** [comment]
>  The templates will follow this order in a next step too?

Please open a new issue for this. #482 is explicitly about "structure and order for view".

**Comment by karindr** [comment]
The templates should follow this order in a next step: #1141

**Comment by j0hj0h** [comment]
> @j0hj0h : I think we decided to use only the icons for the profiles elsewhere so there will be only one line of icons instead of the lists.

done

> Could we get rid of the “DE.NW”-line in the address, please? And put the Zip code in the same line as the town?

done

> There could be a stronger line at the end of the link section before the comments because this is something really different.

We think it's well distinguishable  because "Comments" is a subheading.

> Abbreviation/ Alternate name should only appear in the title.

As discussed here: https://github.com/hbz/oerworldmap/issues/482#issuecomment-288351132 we'll keep both.

> Naming both time and operator in the subtitle is too long. I suggest to use one of them (maybe time) or skip both and use no subtitle because projects often have long titles.

I'd keep it like that for now. The subtitle could have some lines in my opinion and maybe needs to be a bit redesigned, if not be readable that way. In general I'll have a look at the formating of the subline with @formimkontext.

> Project ...

done

> Event ...

done

**Comment by acka47** [comment]
Changes are not deployed to beta yet, as far as I can see...

**Comment by literarymachine** [comment]
> Changes are not deployed to beta yet, as far as I can see...

Yes. We took the liberty to deploy this to production because the remaining issues seemed rather minor.
