### ISSUE TITLE
Implement triple store repository

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#528]
Relying only on Elasticsearch as a storage backend has shown to lead to performance issues for write operations. Due to the heavily interlinked nature of our data, denormalization is a bottleneck. To address this problem, a triple store will act as the main data sink from which JSON representations will be generated asynchronously.

**Comment by literarymachine** [comment]
@karindr From a UI perspective, all that is new is a button next to the edit button with which you can take a look at the log (history) of an entry:

![screenshot from 2016-05-09 13 49 35](https://cloud.githubusercontent.com/assets/149825/15112237/19b6ca66-15ed-11e6-98a1-2be6da226859.png)

But under the hood, a lot has changed. Could you do some random testing to see if the data has been migrated properly? Please note that the data on beta is from Apr 26 so that any changes from afterwards are not available.

**Comment by karindr** [comment]
@literarymachine 
In the input form some code fragments are displayed:
Under Email there is
<<<<<<< HEAD =======
Under License there is
>>>>>>> 0d65bdf2a5cec6107a5e7c234754e64f39924155

The license field with the list of licenses is displayed two times, one of them must be deleted.
When you add license “unspecified” not the image with the question mark is displayed. Instead a little box with the name of the service or the logo is displayed. Next time you open the input form a question mark and a url is displayed in the two license fields. Same error if another license is chosen.

I found a services listed on beta, but the link isn’t working:
https://beta.oerworldmap.org/resource/urn:uuid:5e573656-47f3-11e5-a81e-54ee7558c81f
(It should look like here https://oerworldmap.org/resource/urn:uuid:5e573656-47f3-11e5-a81e-54ee7558c81f.)
Same for Livro Didático Público.

There was a bug: It wasn’t possible to enter English as additional language. This bug is solved on beta.

Under ’Recent Additions’ on the homepage a lot of concepts and schemes are listed. Is this correct? In the little table on the homepage concepts and schemes were added. OK?

Saving is really very slow!

Should I look for something else?

**Comment by literarymachine** [comment]
> In the input form some code fragments are displayed:

Fixed.

> The license field with the list of licenses is displayed two times, one of them must be deleted.

Fixed (was connected to the above error).

> When you add license “unspecified” not the image with the question mark is displayed. Instead a little box with the name of the service or the logo is displayed. Next time you open the input form a question mark and a url is displayed in the two license fields. Same error if another license is chosen.

My bad, I forgot to import the list of licenses into the database. Fixed.

> I found a services listed on beta, but the link isn’t working: https://beta.oerworldmap.org/resource/urn:uuid:5e573656-47f3-11e5-a81e-54ee7558c81f
> Same for Livro Didático Público.

Fixed, see https://beta.oerworldmap.org/resource/urn:uuid:5e573656-47f3-11e5-a81e-54ee7558c81f and https://beta.oerworldmap.org/resource/urn:uuid:fbbd8618-15d8-11e5-8850-2bd783bbdf05

> Under ’Recent Additions’ on the homepage a lot of concepts and schemes are listed. Is this correct? In the little table on the homepage concepts and schemes were added. OK?

We had them there for quite a while, I am unsure why you did not get to see them before. There previously was a need for this (only for logged in users) due to a limitation in the editing forms which is not given any more. Thus I took the opportunity to remove concepts and schemes from the listings. Fixed.

> Saving is really very slow!

Errors like this are hard to track down; could you specify a couple of entries for which you experience this? For example while not super-fast, [Thunderbolt Kids](https://beta.oerworldmap.org/resource/urn:uuid:5e573656-47f3-11e5-a81e-54ee7558c81f) does seem to have reasonable response times.

**Comment by karindr** [comment]
>> Saving is really very slow!

> Errors like this are hard to track down; could you specify a couple of entries for which you experience this? For example while not super-fast, Thunderbolt Kids does seem to have reasonable response times.

Thunderbolt Kids saves in almost the same time on oer and on beta. Try Länkskafferiet, it is much slower on beta. Same with Koolielu. 

The points above are all ok.

**Comment by philboeselager** [comment]
@literarymachine you know better than me what's the problem here. Though, I'm thinking about how to decouple the user's experience from the storage / indexing time. Probably we could handle it like this:

- User says "save" my Resource
- Resource is only being validated (if not OK, back to input page)
- if OK, User is presented the Resource
- lag 1 (very short) ?
- Triple history operations
- lag 2 (little longer) ?
- Indexing starts
- lag 3 (quite long) ?
- Indexing is finished

Now, if the user queries something after being presented the Resource and before Indexing is finished, the result has to be composed as follows:

- take query result from index
- modify it according to newest triple (diff) history

To be precise about what means "newest" here: we compare the diff timestamp to the last indexing timestamp.

Now if it turned out that updating the index query result with the triple diff is not sufficiently up-to-date, we could even update it with the Resource object itself (the latter being cached for the session).

Please let me know if I'm fully barking up the wrong tree.

**Comment by literarymachine** [comment]
> Now, if the user queries something after being presented the Resource and before Indexing is finished, the result has to be composed as follows:
>
>take query result from index
>modify it according to newest triple (diff) history

Not sure if I understand you correctly, but the most recent version is stored in the triple store right after saving - when viewing an individual resource, it is loaded from the triple store.

**Comment by literarymachine** [comment]
The most expensive operation currently seems to be validation, especially for heavily interlinked entries.

**Comment by literarymachine** [comment]
> The most expensive operation currently seems to be validation, especially for heavily interlinked entries.

More precisely, the problem arises when saving Services with a lot of links to subjects. We need to re-implement the old BroaderConceptEnricher which is based on JSON to operate on a Model.

**Comment by literarymachine** [comment]
> Try Länkskafferiet, it is much slower on beta. Same with Koolielu.

@karindr can you confirm response time for these has improved?

**Comment by karindr** [comment]
Yes, ist seem even a bit faster than on the public website.
