### ISSUE TITLE
Switch Logo

### ISSUE THREAD

**Issue by j0hj0h** [hbz/oerworldmap#549]
Switch to new logo – testwise – current might be better concerning outline fitting in the bar and typographic contrast.

**Comment by trugwaldsaenger** [comment]
You guys where right - the old one fits better with the rest of the top bar! I guess, we should stay with the old one. Nevertheless thanks for checking this out!

**Comment by literarymachine** [comment]
> I guess, we should stay with the old one.

As far as I know, nothing has been changed so far.

**Comment by buschfeld** [comment]
Hi Johannes and Felix,
since I still receive the GitHub notifictaions, time to pose a reminder or at least a question: 
In June 2015 I designed and finished a special logo using "Clear Sans", which was also the appropriate font used in the the most layouts for the Top-Navi-Bar. To try and exchange this was part of the Finalize-UI task at that time. Did you ever tried this one? In case not, I enclose a PNG once again ...

**Comment by buschfeld** [comment]
Hi Johannes and Felix,
months back (in June 2015) I designed and finalized a logo using "Clear Sans" which was also to the font used in the whole top navigation bar in the most recent layouts at that time. Amongst others, it was part of the "Finalize UI"-task to exchange the logo and the navi-font according to that. But for some reasons this never happened. Did you ever try use my original logo? In case not, I enclose it once again ... Best - Ben
![oer_world_map_neg_logo_00](https://cloud.githubusercontent.com/assets/10743356/12716985/e2d96c2e-c8e4-11e5-9aa5-9d94a3c44bbb.png)

**Comment by literarymachine** [comment]
> But for some reasons this never happened. Did you ever try use my original logo?

We had to move on to implement the input templates etc, and sometimes even small tasks like exchanging the logo fall by the wayside. Re-opening this since the logo has not been switched yet, be it test wise or for good.

**Comment by formimkontext** [comment]
Here two drafts of the three-column-layout, showing different logos and fonts. I think, the decision for a logo depends on the typeface used on oerworldmap.org, so we have to decide on that too. 

By using the new "Clear Sans"-logo – which is not implemented on oerworldmap.org right now –, we also should exchange the navigation- and text-font to "Clear Sans". "Clear Sans" and "Source Sans" are both sans serif typefaces with similar character, so we won’t mix them. Ben already used "Clear Sans" in some layouts, here it is shown in the layout with the new logo. 

I prefer the old logo currently shown on oerworldmap.org – and with this the font-mix of "Source Sans" (content) and "Economica" (navigation-bar). In my opinion, the font-mix is more user-friendly by seperating the meta-information (navigation-bar) from the world-map-content. 

Furthermore and according to the limited space we have to deal with by implementing the three-column-layout, i see a big benefit in using "Source Sans" and "Economica": Both typefaces are narrower than "Clear Sans", so they allow more letters / words in a line or in a button. Also the lettershapes (e.g.: I, i, l, L) of "Source Sans" are more definite. So, besides the small fact, that "Clear Sans" may appear a little lighter and maybe more modern, i see no reason, why we should exchange the fonts and switch to the new logo.

![20160401-oer-clear-sans](https://cloud.githubusercontent.com/assets/15141949/14289151/dcd7f604-fb59-11e5-9e91-e0beffb89b6a.jpg)

![20160401-oer-source-sans](https://cloud.githubusercontent.com/assets/15141949/14289152/dcd96912-fb59-11e5-8269-66a709f0aa22.jpg)

**Comment by buschfeld** [comment]
I do not agree with Felix in all points. 
Especially I would definetly not use "Economica" in the top navi bar.

Basically "Clear Sans" and "Source Sans" are somehow similar and both of them would make a good choice for the content typography. But – here I agree with Felix – they are maybe too close to mix them in navi and content. But mixing them in logo and content would be OK

As for the logo, I like the "Clear Sans" Logo (= the one that never got implemented in the current  layout, but was used in the far most of my original designs and is also shown in Felix top "screensshot" simulation) much better than the older one, since its much more easy to read and provides a sharper and more self-assured brand design than the logo that is currently implemented.

As for the typeface used in the top navi bar and the slogan on top right, I do not like the "Economica" at all (this was choice Johannes once made quite quickly which never got altered afterwards), since it is really hard to read and contains some very peculiar letter forms (i.e. Q, g) that are kind of over-pretentious and – within that – have no correspondance to the overall look of the design of the site as a whole (UX, colors, icons etc.). 

It is true that "Clear Sans" needs more horizontal space if it is used in the same font-size like "Economica", but since it is much easier to read, the font size could (and should) be reduced if we use that. If after testing that the majority of you still thinks the choice of typeface should be (or offer) a condensed or more narrow font version, I am sure that there will be better open-licensed choices than "Economica"

For that reason my preference and recommendation is ... 
Best: go for "Clear Sans" completely and reduce the font size within the top navi for ca. 15%.
Otherwise: stick to the old content, use either one of the logos, but exchange "Economica" for a better readible and visually more appropriate semi-narrow typeface.

**Comment by formimkontext** [comment]
Following Bens advise, i adjusted the font size of "Clear Sans" within the top navi as well as in the content. 

Since we agree, that we should not mix "Clear Sans" and "Source Sans" anyway, i also agree to Bens recommendation to:
– gor for "Clear Sans" completly or
– stick to the old content

Unlike Ben, i find the peculiar letterforms of "Economica" kind of characteristic in a positive way, showing a clearly recognizable contrast to "Source Sans". 

![20160405-oer-clear-sans](https://cloud.githubusercontent.com/assets/15141949/14314579/4fccf3e6-fbf8-11e5-8562-e590599c2833.jpg)

**Comment by literarymachine** [comment]
Outdated, closing.
