### ISSUE TITLE
Optimize Search Ranking

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#571]
When I search for "BC Campus" 255 results are found - "BC Campus" ranks nr. 8.

**Comment by literarymachine** [comment]
Sorry, almost forgot about this (see also #461). @philboeselager we should take a look at this soon.

**Comment by philboeselager** [comment]
My first impression is that we should add a boost on the search-side (not on the index-side). As long as we do not get in trouble with search performance, this approach gives us as much flexibility as possible, since we easily can adjust boost settings.

Once we should get in trouble with performance, we could switch to index-side boosting then, using the boosting values that we have found out to work best so far.

The search-side boost generally works like:

    "query": {
        "multi_match": {
           "query": "BC Campus",
           "fields": ["@id^5", "_all"]
        }
    }

resulting in a "5 times higher" weight of the @id field. The value "5" is just an initial example of course.

We would also boost URLs, but a bit less than @id maybe, wouldn't we?

**Comment by literarymachine** [comment]
> My first impression is that we should add a boost on the search-side (not on the index-side).

Excellent, that saves us from re-indexing while finding the right boost values!

**Comment by acka47** [comment]
This should alread ybe closed. Closing.
