### ISSUE TITLE
Aggregated pin is not resolving

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#582]
Navigate as following:
1) click on Germnay
2) click on the aggregated pin ("7") right over Frankfurt

4 pins are now shown on the map, three single pins and one aggregated pin "4". This aggregated pin cannot be resolved by clicking on it.

**Comment by literarymachine** [comment]
> 4 pins are now shown on the map, three single pins and one aggregated pin "4". This aggregated pin cannot be resolved by clicking on it.

Those pins are too close together as that they could be resolved within our current maximum zoom level. While this can be resolved by increasing that zoom level, it probably won't be possible to resolve it for those cases where there are several pins at the same location (though those cases should be rather unusual).

**Comment by philboeselager** [comment]
> While this can be resolved by increasing that zoom level, it probably won't be possible to resolve it for those cases where there are several pins at the same location (though those cases should be rather unusual).

I would in fact expect that to happen, for example: one organization hosts two or more services, could it not?

**Comment by literarymachine** [comment]
> I would in fact expect that to happen, for example: one organization hosts two or more services, could it not?

It could, but there would be only one pin for the organisation. Services themselves should usually not get a location and thus no pin!

**Comment by philboeselager** [comment]
> It could, but there would be only one pin for the organisation. Services themselves should usually not get a location and thus no pin!

Ah, interesting. I had been asking that myself and I thought they (one day) could provide a location, since our data model allows that to happen - see https://github.com/hbz/oerworldmap/blob/master/conf/index-config.json#L667 . 

Nevertheless, it might occur that two (or more) - maybe cooperating - organizations are hosted in the same building. At least this is quite regular in other kinds of businesses. 

I wouldn't insist on a solution that is safe to this quite special case, but I am in favour of a such solution.

**Comment by trugwaldsaenger** [comment]
> Ah, interesting. I had been asking that myself and I thought they (one day) could provide a location, since our data model allows that to happen - see https://github.com/hbz/oerworldmap/blob/master/conf/index-config.json#L667 . 
Yes, our data model allows that and our front end does so, too. There is a small number of cases, where it makes sense to add a location to a service, but we have to keep care that this remains the exception, not the rule...

**Comment by trugwaldsaenger** [comment]
I guess we should consider increasing the zoom level or relating the search result list to the display of the map (see #581). Right now you are simply stuck, when you find an aggregated pin, that can not be resolved, also because the search result list does not follow the map display (as we learned in #581). I think it is important, because you can find aggregated pins quite often, for example in Munich, Berlin, Netherlands, London and probably in many other cities as well. So we should not wait too long before fixing this issue. Nevertheless I do not consider it so important, that it has to be done immediately.

**Comment by trugwaldsaenger** [comment]
We definetly should not to forget this. I propose to solve this issue latest with the release of V1.1. I would guess that most users start by "clicking themselves down" on the pins. If this first attempt to use the platform leads to an dead end, we risk loosing these users.

**Comment by acka47** [comment]
The prefered solution for this is twofol:

1. The resource list should update according to the area one has zoomed into (covered by #581.)
2. When there are two resources that have exactly the same coordinates or which can't be differentiated because of the lack of zoom level, the cluster should open a the number of pins behind it linked by a line to the original cluster. As I can not describe this well click a cluster at http://oermap.org/home/1900-2/ and watch what happens.

**Comment by karindr** [comment]
Also on V1.1 aggregated pins are not resolving.

**Comment by literarymachine** [comment]
- First step: #581
- Second step: Show popover list
- Third step: evaluate location indexing / javascript

**Comment by literarymachine** [comment]
> First step: #581 

While aggregated still don't resolve, the result list is now reduced to the pins that are actually visible on the map. Thus, zooming into aggregated pins that are exactly in the same place will result in a list contains only the corresponding entries. On https://beta.oerworldmap.org/

**Comment by literarymachine** [comment]
Rephrase as "Search as I move the map"

**Comment by literarymachine** [comment]
> Second step: Show popover list

On beta. When hovering over a cluster of pins, a summary is now shown for that cluster:

![screenshot from 2016-12-08 17-01-04](https://cloud.githubusercontent.com/assets/149825/21016994/1582adde-bd68-11e6-9cb8-4bce9cd369bf.png)

If the cluster contain three or less pins, the summary is extended:

![screenshot from 2016-12-08 17-02-56](https://cloud.githubusercontent.com/assets/149825/21017046/432ca776-bd68-11e6-9275-773317bc9a0d.png)

If a cluster is clicked, the map zooms in and the list is shown:

![screenshot from 2016-12-08 17-50-29](https://cloud.githubusercontent.com/assets/149825/21019490/ebd4dce2-bd70-11e6-8849-90e157bbea09.png)


> Third step: evaluate location indexing / javascript

Already fixed in #872.

**Comment by acka47** [comment]
This already looks quite good but some things are confusing. For example:

![bildschirmfoto vom 2016-12-09 10 07 21](https://cloud.githubusercontent.com/assets/160292/21043444/3a89fda0-bdf7-11e6-8d88-516f9ddd7558.png)

Here the World Map project is shown twice in the pop over plus two other entries but the cluster has a "2" on it. When I take a look at Jan's profile though, the project is only shown once in the popover withe cluster being labeled "2" as well:

![bildschirmfoto vom 2016-12-09 10 08 52](https://cloud.githubusercontent.com/assets/160292/21043488/6a0174fa-bdf7-11e6-83ab-9ce1d5dd50ce.png)

I think, generally each resource behind the cluster should only be shown once with the cluster having the correct number as label. This means, the second example would be fine if the cluster was labeled "3". 

Obviously, there is a problem with resources (projects, services) that are only indirectly geo tagged via a provider or operator. it looks like they are not taken into account for the cluster numbering. I see two options here:

1. Don't show indirectly geo-tagged resources at all on the map.
2. Show indirectly geo-tagged resources on the map and take them into account in the cluster numbering.

As we won't consider 1.), this leaves us with 2.).

**Comment by literarymachine** [comment]
> Here the World Map project is shown twice in the pop over plus two other entries but the cluster has a "2" on it.

This is correct. There are only two "direct" entries on the map. The other ones, in pale blue and with the little arrow pointing up, are related but have no pin.

> When I take a look at Jan's profile though, the project is only shown once in the popover

This we have to investigate.

> I think, generally each resource behind the cluster should only be shown once with the cluster having the correct number as label. This means, the second example would be fine if the cluster was labeled "3".

This will make things much more complicated, because there actually are only two pins behind the cluster. Take a look at a single pin with related resources, they have been like this for a long time. If we follow your approach, we would also have to turn them into a cluster:

![screenshot from 2016-12-09 10 21 12](https://cloud.githubusercontent.com/assets/149825/21043855/468ba750-bdf9-11e6-83cd-adde2a80e19c.png)

This whole indirect location thing is leading to a lot of confusion and we have spent more hours on this issue than I believe is appropriate. By now I believe we should probably put an explicit pin e.g. for a Service on the map, too. This will lead to a lot of (non-resolving) clusters, but if we cut the "related" (pale blue) entries from the cluster popovers, things might be clearer.

**Comment by literarymachine** [comment]
We never really specified together with the product owner / map users how the actual map interface should work. We really need to do this, because every technical iteration does take quite some time. We need an approach before we we continue here.

**Comment by j0hj0h** [comment]
I think it makes sense to show the relations in the popovers, because it shows the relational character of our data. The layout of the popovers could be improved to better show which "units" belong together – e.g. by a small gap instead of the dark line.

**Comment by karindr** [comment]
A "simple" solution would be to change the pin for Dresden university shown above into a 3. This means showing all entries that are located by being connected to a pin as pins (respectively as aggregated pin) on the map too.

This will solve the problem that there is often a difference between the numbers in the country lists and the number of pins shown on the map, see for example 5 and 6 for Czech Republic:
https://oerworldmap.org/country/cz

This only leaves the hbz/Jan/oerworldmap problem unsolved which is an entry connected to two (or more) other entries at the same place. But I think people will probably understand this exception better than differences everywhere.

**Comment by karindr** [comment]
I like the little triangle pointing to the "master" entry. It makes the relation visible maybe it could be a bit bigger?

**Comment by j0hj0h** [comment]
Then it would reach below the icon of the master, if it has only one line.

**Comment by karindr** [comment]
> Then it would reach below the icon of the master, if it has only one line.
Then it's OK.

**Comment by formimkontext** [comment]
I think the popover should show all located and related entries. I see no problem in showing related entries several times but in different relation to various superordinated entries. The cluster should indeed count every listet entry only once. Just like the search result list does.

**Comment by karindr** [comment]
I agree, probably people will understand why entries are shown more than once because the relation is shown by the triangle.

**Comment by j0hj0h** [comment]
As "Search as i move the map" is not active by default anymore, I'm going to solve this by persistent popovers with clickable entries ...

**Comment by karindr** [comment]
Sounds useful.

**Comment by literarymachine** [comment]
> Sounds useful.

But *is* it also useful? Please check https://beta.oerworldmap.org/ and also see https://github.com/hbz/oerworldmap/issues/1033#issuecomment-274066053.

**Comment by acka47** [comment]
It seems a bit strange that the map gets the blue shade when clicking on a cluster. Also, I noticed some problems with the feature:

- When I try this with the location of the hbz, the popup misses most information: 
![bildschirmfoto vom 2017-01-23 10 29 49](https://cloud.githubusercontent.com/assets/160292/22198490/02df56ec-e157-11e6-890b-dca57d474d62.png)
- When click on a single map pointer (e.g. [OKFN Germany](https://beta.oerworldmap.org/resource/urn:uuid:b337d172-69ff-4ee8-a2cc-b65ff8536697)) and then on a unresolvable cluster both the single resource and the persistent popover are shown. I would expect the single resource to be "unchecked".
![bildschirmfoto vom 2017-01-23 10 34 27](https://cloud.githubusercontent.com/assets/160292/22198608/8a1996c2-e157-11e6-88b2-1b39d115e6dd.png)

**Comment by literarymachine** [comment]
> It seems a bit strange that the map gets the blue shade when clicking on a cluster.

This is to clarify the difference in application state, i.e. that now a popover list is in focus. I think it is a good idea, but you may of course discuss with @j0hj0h.

> When I try this with the location of the hbz, the popup misses most information:

Interesting catch. I think the behavior is currently coupled to the display of the list (instead of only the cluster stats as in case of hbz), which again is only activated when the list is <= 3. Could you take a look, @j0hj0h?

> When click on a single map pointer (e.g. OKFN Germany) and then on a unresolvable cluster both the single resource and the persistent popover are shown. I would expect the single resource to be "unchecked".

You mean that the column should disappear just because you clicked on such a cluster? I disagree, I believe the resource should be replaced by the selected one once the selection has been made. What do you think, @j0hj0h?

**Comment by acka47** [comment]
> When click on a single map pointer (e.g. [OKFN Germany](https://beta.oerworldmap.org/resource/urn:uuid:b337d172-69ff-4ee8-a2cc-b65ff8536697)) and then on a unresolvable cluster both the single resource and the persistent popover are shown. I would expect the single resource to be "unchecked".

Looking at the thread at #1033 I realized that the popover was introduced to solve problems with showing the clustered entries in the list on the right. Obviously, this brings with it this new problem. Generally, you now have to click _one_ specific resource (not a cluster) to replace the selection on the right side. So the behaviour has some logic to it and we can leave it for now.

**Comment by literarymachine** [comment]
> So the behaviour has some logic to it and we can leave it for now.

IMHO, it has quite some logic. But if all of this is really still unclear, I would suggest a session with @j0hj0h and @formimkontext so that you can define what would actually be a desired behavior. The trial and error approach in developing this should come to an end at some point.

**Comment by karindr** [comment]
A little bug in this feature: The labels get cut off at the top sometimes, See:
![image](https://cloud.githubusercontent.com/assets/18674205/22199447/443566c8-e15b-11e6-956f-381e7ee2a75f.png)

**Comment by karindr** [comment]
I think the new feature is useful and would suggest to extend its behaviour (that you can click in the different entries in the popup) on pins with connected entries for example an organisation with a project. At the moment you can't get to the project via the map because when clicking on the pin you only get to the organisation but not to the project. If the popover was clickable as for the clusters you can get to the project directly from the map.

**Comment by acka47** [comment]
> IMHO, it has quite some logic. But if all of this is really still unclear

Yes, it has quite some logic and thinking about it, it is the best solution for the different problems we are dealing with (i.e. having entries that have no location and also having locally clustered entries). Also, this approach works really good when I arrive at a cluster via searching instead of browsing the map. See e.g. https://beta.oerworldmap.org/resource/?q=geschichte#urn:uuid:5ce85685-c24c-4a2a-b92b-39c6136464dc.

**Comment by literarymachine** [comment]
> I think the new feature is useful and would suggest to extend its behaviour (that you can click in the different entries in the popup) on pins with connected entries for example an organisation with a project.

You mean when displaying the list of a single pin? That sounds like a good idea! @j0hj0h?

**Comment by karindr** [comment]
Yes, a singele pin for an organisation and a project for example.

**Comment by j0hj0h** [comment]
> If the popover was clickable as for the clusters you can get to the project directly from the map.

Makes sense, I will implement this. All popovers with more then one resource, no matter if direct or linked, will go in "persistent" more, when pin/cluster is clicked.

> which again is only activated when the list is <= 3

Yes, that's correct. So I'll refine this:

- Always show the list, when popover goes to "persisten" mode
- Make it scrollable, if it's to large

Fine?

>  I disagree, I believe the resource should be replaced by the selected one once the selection has been made. What do you think, @j0hj0h?

Yes, no automatic closing at this point, as no selection is made yet.

> A little bug in this feature: The labels get cut off at the top sometimes

This has always been like that. You have to move the map, to see it completely. If we switch to MapBox GL, the popovers will change direction automatically – so I would suggest, to leave it like that for now.

**Comment by karindr** [comment]
I agree to all suggestions from @j0hj0h.

**Comment by literarymachine** [comment]
> I agree to all suggestions from @j0hj0h.

On https://beta.oerworldmap.org

**Comment by acka47** [comment]
+1

**Comment by karindr** [comment]
+1
