### ISSUE TITLE
Enhancement for users while entering data

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#640]
When you are entering data and you klick on the background by mistake, all the entries since the last saving are lost. Users will add a lot of data bevor saving, because saving is not very quick an you have to go to the input form again. Is there any possibility to make it impossible to leave the input form without choosing save or quit? Or is it possible to insert a question if the user really wants to quit without saving when he clicks on the background.

**Comment by literarymachine** [comment]
> When you are entering data and you klick on the background by mistake, all the entries since the last saving are lost.

Which browser are you using? As long as the page is not reloaded, this is currently not the behavior I experience. Try clicking on "Add Organization", enter something in the `name` field, click on the background and click on "Add Organization" again (without navigating somewhere else in between). The contents of the field should still be there. Same goes for editing an existing entry.

> Is there any possibility to make it impossible to leave the input form without choosing save or quit? Or is it possible to insert a question if the user really wants to quit without saving when he clicks on the background.

Since the above is not really intuitive, this will be introduced with #577. Which of the two options would you prefer?

**Comment by karindr** [comment]
I’m using Chrome on Windows 7 Proffesional.

If I klick on “Add service” etc. again, the data isn’t lost. Good to know. I wouldn’t have tried this because it sounds like creating a new service etc. As you say, not really intuitive ;-)

Having to choose between the two options, I would prefer to be asked if I want to quit or to save when I klick on the background. This would also be a shortcut when you don’t want to scroll to the bottom for saving!

**Comment by karindr** [comment]
The solution for this on v1.1 works very good for me!

**Comment by acka47** [comment]
Closing.
