### ISSUE TITLE
Searching for longer words without adding an asterisk to the search term

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#651]
When you want to search for words beginning with your search term you have to put  an asterisk at the end of the search term.  Most users won’t expect this. It is much more common to search for the search term and words beginning with this term at the same time. Is it possible to change this?

**Comment by literarymachine** [comment]
@philboeselager please take this into account when looking at #605.

**Comment by karindr** [comment]
it would be really useful when there is no * needed any more. Our new visitors may leave, if they get often "0 entries" instead of finding what they searched for. If it cant be realized in the next time, it might be useful to ad a little hovering label saying "If you want to search with an incomplete word, please put an * at the end of the word."

**Comment by literarymachine** [comment]
@philboeselager to me it seems as if a [`match_phrase_prefix` query](https://www.elastic.co/guide/en/elasticsearch/guide/current/_query_time_search_as_you_type.html) exhibits the behavior expected by @karindr. The problem is that our [field boosts](https://github.com/hbz/oerworldmap/blob/f28fa8bf513378d5d98d3241852497b68e24849f/app/services/repository/ElasticsearchRepository.java#L376) do not work when exchanging our `QueryStringQueryBuilder` with a `PrefixQueryBuilder`. Also, we would loose the ability to use the [query string syntax](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html) which is in use in several cases, especially the auto completion in the editing templates.

A naive approach would be to simply concatenate the `*` to the [end of the query](https://github.com/hbz/oerworldmap/blob/f28fa8bf513378d5d98d3241852497b68e24849f/app/services/repository/ElasticsearchRepository.java#L374):

    queryBuilder = QueryBuilders.queryString(aQueryString.concat("*"));

I have not checked for any side effects yet, though.

**Comment by jprante** [comment]
Hint: wildcard queries are dangerous, especially on high cardinality fields. To build an expanded query, such a query visits all matching terms in the index and that can be millions and can bring down even large Elasticsearch installations unexpectedly.

`max_expansions` parameter can limit the term expansion of `match_phrase_prefix`. Without `max_expansions`, `match_phrase_prefix` queries are slow and resource consuming.

But the answer to the question is introducing n-gram tokenization https://www.elastic.co/guide/en/elasticsearch/guide/current/_ngrams_for_partial_matching.html 

N-grams for partial matching avoid `match_phrase_prefix` or wildcard queries for autocompletion, at the price of much larger index size.

**Comment by literarymachine** [comment]
> But the answer to the question is introducing n-gram tokenization https://www.elastic.co/guide/en/elasticsearch/guide/current/_ngrams_for_partial_matching.html

Thanks @jprante!

**Comment by philboeselager** [comment]
Thanks for this hint @jprante !

@literarymachine I suggest using trigrams in the first try.

**Comment by literarymachine** [comment]
> @literarymachine I suggest using trigrams in the first try.

+1

**Comment by literarymachine** [comment]
Deployed bigram tokenization to beta, see e.g.

https://beta.oerworldmap.org/resource/?q=stax 
https://beta.oerworldmap.org/resource/?q=Le%20Mill
https://beta.oerworldmap.org/resource/?q=unglue

**Comment by karindr** [comment]
+1
