### ISSUE TITLE
clicking on logo does not activate original zoom level

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#665]
Currently a click on the logo brings the user back to the start position. On the new version the zoom level does not go back into its original position.

**Comment by karindr** [comment]
In addition to this for a second a distorted map is shown (height is ok, but width is to big). That doesn't happen on production.

**Comment by literarymachine** [comment]
Deployed to http://oerworldmap.graphthinking.com/

**Comment by karindr** [comment]
the zoom level is ok now, but look at this:
![image](https://cloud.githubusercontent.com/assets/18674205/16001768/4b715800-3154-11e6-8791-ce94f63df869.png)
This happens when I am in Australia an click on the logo. When I start in Mongolia it is ok. Same for Greenland:
![image](https://cloud.githubusercontent.com/assets/18674205/16001827/a85ba4f8-3154-11e6-98b3-593dbcf51628.png)

**Comment by karindr** [comment]
OK
