### ISSUE TITLE
Show organisations only in the country view of country, which they are located in

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#680]
When clicking on the country view for Nepal (http://oerworldmap.graphthinking.com/country/np) the organization "Mongolische Vereinigung" (http://oerworldmap.graphthinking.com/resource/?filter.about.location.address.addressCountry=MN&filter.about.@type=Organization#urn:uuid:9cecf8ad-a3fe-439f-80d4-dbc416d4ec52) is displayed. According to my understanding this is wrong, because the "Mongolische Vereinigung" is being located in Mongolia, not in Nepal. The reason why the map does this is that the "Mongolische Vereinigung" provides the "Nepal Service" (http://oerworldmap.graphthinking.com/country/np#urn:uuid:4265f140-1bd4-4bc6-aff7-3b04fa9d9fc8), which is located in Nepal.

**Comment by literarymachine** [comment]
The problem here is that initially, we did not plan to give a `Service` a `location`, so we decided to use the `location` of the providing `Organization` (like you write in your comment). At some point, we started to add `location` to `Service`. We should at some point clearly define which locations are relevant, which pins to display etc. This has never been specified.

**Comment by literarymachine** [comment]
Note to self: this behavior is occurring because when indexing we are copying the locations of embedded entities to the parent. See e.g. https://github.com/hbz/oerworldmap/blob/577-implementThreeColLayout/conf/index-config.json#L102. Once a decision is made, the index configuration must be updated accordingly.

**Comment by trugwaldsaenger** [comment]
I would prefer to keep the current model active. I think that the rule that a service should be displayed at the location of its provider is a good one, which prooved to work in most of the cases. Only for a few exeptions it is necessary to add a location directly to a service or a project. In order to avoid confusion on the side of the customer resulting from this multiple locations, I proposed to hide the address field within projects and service by making it collapsable (see #565). I still think that this is the best way to go. I think it is an interesting issue, but we should not overestimate it. It did not happen with real world data yet and the example is a bit constructed...

**Comment by trugwaldsaenger** [comment]
The issue appears for projects as well. I connected the world map project with the OU UK and now OU UK appears as an German organization: http://oerworldmap.graphthinking.com/resource/?filter.about.location.address.addressCountry=DE&filter.about.@type=Organization.
