### ISSUE TITLE
Layout Global Statistics 

### ISSUE THREAD

**Issue by formimkontext** [hbz/oerworldmap#707]
Current draft for the new global statistics modal. 
![20160622-oer-statistiken](https://cloud.githubusercontent.com/assets/15141949/16276822/59a7bfaa-38b0-11e6-9f4f-a3bf3bab0e05.jpg)

**Comment by literarymachine** [comment]
@formimkontext The biggest pie has eleven slices. Could you provide color codes for all of them here? Thanks!

**Comment by literarymachine** [comment]
While certainly not final, I do believe this is an improvement to the current layout. Deployed to https://beta.oerworldmap.org/aggregation/. What do you thing @trugwaldsaenger and @karindr, should I deploy this to production?

**Comment by trugwaldsaenger** [comment]
Looks pretty cool! Please deploy on production! One small improvement would be to link not only the segment in the diagram, but also the name in the legend, since this will be clicked first. But we could also implement this later.

**Comment by literarymachine** [comment]
> One small improvement would be to link not only the segment in the diagram, but also the name in the legend, since this will be clicked first.

@trugwaldsaenger: on https://beta.oerworldmap.org/aggregation/

**Comment by trugwaldsaenger** [comment]
+1

**Comment by karindr** [comment]
I liked it better when all statistics where displayed one following the other. The list under the headline could be used as links to jump to the different statistics. Displaying all statistics shows to every visitor at the first glance that there is more than one statistic.

The colours will be changed to the colours suggested by @formimkontext, I assume? They are much nicer.

Side note: I prefer pie charts instead of donut charts, because people understand them at the first glance and there is no new information in using a different form.

**Comment by j0hj0h** [comment]
> @formimkontext The biggest pie has eleven slices. Could you provide color codes for all of them here? Thanks!
I'd suggest to use even steps between the orange and green. That way we're independ from the actual number of slices as long as they are distingualble. This can be easily done via HSL color definitions. I will implement this when I'm back at work.
