### ISSUE TITLE
Displaying of homepage is slow here in hbz

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#728]
The fist displaying of oerworldmap.org in the browser here in hbz is really slow. I started counting slowly an got to over 20. It is not only today, last days have also been slow. First nothing is shown, then the website with the spinner is shown. 

In addition to this every going back to the homepage of the site by clicking on the logo is also slow, but not as muchas in the first time (3-4 s).

**Comment by trugwaldsaenger** [comment]
I made the same experience. Using my personal fast DSL access it takes about 7 seconds to start the page for the first time. Returning to the homepage, e.g. from the search result list takes about 3-4 seconds, like @karindr observed. Saving new entries also takes quite some time.

**Comment by literarymachine** [comment]
> The fist displaying of oerworldmap.org in the browser here in hbz is really slow. I started counting slowly an got to over 20.

I also noticed this today; it was probably due to an unnecessarily large version of a Javascript library being loaded, which I fixed. Still, loading all necessary libraries and geographic data currently results in ~3MB that need to be downloaded initially. Can you confirm that the initial load has gotten a bit better, though? It takes ~7s with my connection. You might have to enforce a reload by hitting `CTRL+F5`.

> In addition to this every going back to the homepage of the site by clicking on the logo is also slow, but not as muchas in the first time (3-4 s).

Navigating to the homepage involves loading the entire data set so that the map can be populated. This means that ~1MB have to be downloaded. I will try to further reduce the data in the future, and add some caching, but it is unfortunately nothing that can be done quickly now.

**Comment by literarymachine** [comment]
Deployed to https://beta.oerworldmap.org/.

**Comment by trugwaldsaenger** [comment]
The initial start of the homepage on production took me now 7-8 seconds. On Beta it is only about 3-4 seconds, which is a significant improvement. Returning to the homepage from a search result the improvement is less significant. Here it takes 4-5 seconds on production and 3-4 seconds on beta.

**Comment by literarymachine** [comment]
@trugwaldsaenger deployed to production.
