### ISSUE TITLE
Do we need multilingual tags?

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#753]
Most fields can be entered in several languages. I`m wondering, if we need this functionality for tags as well. @acka47: What do you think?

**Comment by acka47** [comment]
I haven't encountered multingual tags before. Tags are a simplistic approach to adding whatever information and I think we should stick with this simplicity.

**Comment by literarymachine** [comment]
> I haven't encountered multingual tags before. Tags are a simplistic approach to adding whatever information and I think we should stick with this simplicity.

+1

**Comment by trugwaldsaenger** [comment]
I have not seen multilingual tags before either. On the other hand we simply might not have recognized them, because if only on set of tags is displayed you might not be aware of the fact that sets in other languages are available as well.  

I`m not sure if not offering multilinguality for tags really supports simplicity at this point.  For example: Someone adds his organization in English and in Spanish. Since he cannot add tags in  a special language he will add all his tags in English and in Spanish. Someone who looks at the entry will see all information either in English or in Spanish, depending on which language is choosen in his/her browser. Except the tags, which are shown in English and in Spanish, since we did not differentiate the language. So I would argue that not diffentiating the language makes the appearance more complicated. This is even more true, when using the complete tag list as a means of searching information. A tag cloud including tags from multiple languages will be much more complicated to handle than a cloud with tags from one language.

**Comment by karindr** [comment]
I expected that people would use English tags if there wasn't the possibility to choose the language. But the new entries show that if they use tags they use their own language even when the service is also in English.
When I work as visitor with the tag list it would be easier to have the possibility to choose tags only in the language I want to see.

**Comment by drrobertfarrow** [comment]
I think that in practical terms it makes sense keep tags lingually undifferentiated.  This allows people to tag with whatever language they wish.  I suspect most people will use English since the site is mostly in English.  But we should allow flexibility.  For instance, in Spanish speaking countries 'OER' is 'REA' (Recursos educativos abiertos).  Allow people to use their preferred tag and it is more likely that a person like them will find it.  

In addition to it being practical I think there would be no problem producing a tag cloud from these tags, even if they are in different languages.  Maybe it would even be possible to produce something like this (http://www.free-vectors.com/vector-world-map-countries-word-cloud/) but using tags at some point - then differences like the OER/REA preference would be more apparent and provide another way to explore the data - though I imagine this could be a bit more complex.

**Comment by acka47** [comment]
Tags are simple strings attached to a resource. This holds for every usage of tags I know and sometimes results in use of ambiguous tags, see e.g. [the tag "chat" on flickr](https://www.flickr.com/search/?tags=chat) which mostly includes pictures of cats ("cat" on French is "chat") but also people chatting.

This is how tags work and people familiar with them expect them to work like this. We should not confuse users by re-inventing tagging. If we want to ask for a tag's language, we should relabel the process and not use the terms "tag" and "tagging".

From [wikipedia](https://en.wikipedia.org/wiki/Folksonomy):

> A folksonomy is a system in which users apply public tags to online items, typically to aid them in re-finding those items. 

To make it easy for users to handle tags and to filter out unwanted resources tagged with a specific string, they should be able to only show items tagged with a specific string by a specific user, e.g. show all resources tagged with "oep" by user x. Other services do the same (e.g. https://www.flickr.com/photos/7528991@N02/tags/chat/ vs. https://www.flickr.com/photos/142924216@N06/tags/chat/).

**Comment by trugwaldsaenger** [comment]
> We should not confuse users by re-inventing tagging.
Convinced. Closing for now - we still can re-open the issue, if needed.
