### ISSUE TITLE
List of already used tags to choose from in templates

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#754]
It would be very useful to have a list opened when you start entring tags in a template. This makes sure we don't have too much different names or writings for the same topic.

**Comment by trugwaldsaenger** [comment]
I think, we have implemented this by now, though I`m not 100% sure, if it works reliable. @Karindr could you check if it is working reliable for you (within all different templates), so that we eventually can close the issue?

**Comment by acka47** [comment]
I just tried it on production and beta and there was no list of suggested tags at all. One minor thing that should also be fixed when working on this: When I click on "+ Add Tags" a new input field opens but I have to place the cursor there manually. It would be better if the cursor was set in the new field automatically.

**Comment by karindr** [comment]
If you start entring a word, there is a list appearing (if there are already tags with this characters). It works on beta and on production.

I agree with @acka47 that it would be better if the cursor is placed automatically.

In my opinion there should be a possibility to enter more than one tag at the same time, maybe by using ";" to separate the tags. With lots of tags this is much quicker.

**Comment by acka47** [comment]
>  It works on beta and on production.

Not for me, neither on beta nor on production.

![tag-bug](https://cloud.githubusercontent.com/assets/160292/18829269/cf5c2350-83db-11e6-809c-eddac11f2207.png)

**Comment by karindr** [comment]
@acka47 is right. It only works in some cases. See:
![image](https://cloud.githubusercontent.com/assets/18674205/18830145/b8da0a1c-83df-11e6-8605-b85f845d2dd8.png)

**Comment by literarymachine** [comment]
> Not for me, neither on beta nor on production.

This is indeed because the functionality has not been implemented until now. What @karindr and @trugwaldsaenger are experiencing is their browsers autocomplete function which completes words they have typed in before. But only in that browser, and not including the keywords other people have used.

Deployed to https://beta.oerworldmap.org/ now. Known limitations: keywords are not ordered case insensitive as in #807. This is because the solution makes use of [datalist](https://developer.mozilla.org/de/docs/Web/HTML/Element/datalist) and we cannot override the way it works. I would argue though that this is not a problem because the actual autocompletion is case insensitive, try typing "oe" as an example.

**Comment by acka47** [comment]
Works good but it currently doesn't look like other auto-suggests in the web form. The font colour is black instead of blue and there is no icon in front of the tag. As the missing icon makes sense, at least the colouring should be aligned with the rest.

**Comment by literarymachine** [comment]
> Works good but it currently doesn't look like other auto-suggests in the web form.

As stated above, "the solution makes use of datalist and we cannot override the way it works". This is why it generally looks different. We can either leave it as it is or wait until @j0hj0h is back from vacation. In this case, I would deploy anyways since the functionality is already a working improvement and create a new issue for styling datalist inputs.

**Comment by acka47** [comment]
+1 for deploying as is. We will see whether a change is needed in the future...

**Comment by karindr** [comment]
I don't get any tags to chose from, neither on beta nor on production. Did I miss an change?

**Comment by literarymachine** [comment]
This broke with #740.

**Comment by literarymachine** [comment]
@karindr: if we reintroduce `autocomplete`, #740 will occur again. See https://github.com/hbz/oerworldmap/issues/740#issuecomment-288376384.

**Comment by karindr** [comment]
Then please reintroduce autocomplete, #740 wasn't showing up too often. I think it is more important to have good tags for our entries than to avoid this little bug.

**Comment by karindr** [comment]
Since we want to make more use of the filter section and tag lists are a good way please reintroduce autocomplete soon. Otherwise we will have typos and entries not listed besause of this.
