### ISSUE TITLE
Newly entered service seems to be lost

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#755]
I entered OpenScout to the Map and edited it some times. When I now want to go back to the entry I can't find it neither by searching nor in Recent Additions.

This kind of occurrence would be discouraging for users.

**Comment by philboeselager** [comment]
About how many seconds or minutes after entrying did you check or search?

**Comment by karindr** [comment]
I checked several times, 5 minutes, 10 minutes an an hour.

**Comment by literarymachine** [comment]
> When I now want to go back to the entry I can't find it neither by searching nor in Recent Additions.

As in #685, the entry has been properly saved but could not be indexed. The problem was entering "2009-00-00" as "Available since", because this is not a valid date. I fixed this, see https://oerworldmap.org/resource/urn:uuid:076a3822-e38e-4f9d-b7fe-2a807e1bf3df.

This is obviously a bug in our JSON schema, dates as the one above should be rejected: #765

**Comment by karindr** [comment]
+1

**Comment by literarymachine** [comment]
Closing this in favor of #765.
