### ISSUE TITLE
Wrong link to story from entity mentioned

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#780]
https://oerworldmap.org/resource/urn:uuid:967fca4e-15cf-11e5-abe2-4785fa5f5d27
Under this story the organisation "Community of Practice for Information Literacy Online Teaching" is listed as "Entities mentioned". But when you go to this organisation there is a "mentioned in" link to another story where this organisation is not mentioned.

I think this is a bug, but I don't know how to change the link.

**Comment by literarymachine** [comment]
@acka47 #784 is deployed to production: https://oerworldmap.org/sparql/update?delete=&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FmentionedIn%3E+%3Fo+.+%3Fx+%3Chttp%3A%2F%2Fschema.org%2Fmentions%3E+%3Fy+.&where=OPTIONAL+%7B%3Fo+%3Chttp%3A%2F%2Fschema.org%2Fmentions%3E+%3Fs%7D+OPTIONAL+%7B%3Fy+%3Chttp%3A%2F%2Fschema.org%2FmentionedIn%3E+%3Fx%7D

Since #791 is also deployed, one the links are fixed @karindr can fix the relations by editing the story.

**Comment by acka47** [comment]
Fixed after I patched the database with the patch @literarymachine linked to in the last comment. Closing.
