### ISSUE TITLE
Add street layer to map

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#809]
When zooming into the map, streets should be displayed.

**Comment by literarymachine** [comment]
On https://beta.oerworldmap.org/ I disabled the subnational division layer for now because this needs some more work. The street layer is an improvement in itself, though, I believe.

**Comment by karindr** [comment]
I appreciate streets to be displayed on the OER WM. But I think they should be displayed much “later”. E.g. looking at this zoom level of Germany the street information does not give any useful information in my opinion. The heat map of the Bundesländer would give more information at this level. 
![image](https://cloud.githubusercontent.com/assets/18674205/17509538/b7a7a608-5e1a-11e6-8acd-55751a0589be.png) 
In this zoom level the street map often looks even „broken“, e.g. in this part of England seen below. I think this is more distracting than helpful to show the streets in this level. Even the rivers get broken in this level (look at the rivers in France or the Main).
![image](https://cloud.githubusercontent.com/assets/18674205/17509547/c78ec5d8-5e1a-11e6-90f5-03b404943d91.png)
Looking at the details there also seems to be missing information e.g. in Cologne. But with the street names it is helpful nevertheless.
![image](https://cloud.githubusercontent.com/assets/18674205/17509558/d89120ce-5e1a-11e6-8133-d30560726898.png)

**Comment by literarymachine** [comment]
Decided offline with @trugwaldsaenger to postpone this until the team meeting and integrate it along with #810.

**Comment by literarymachine** [comment]
- [ ] More city names and less streets on medium zoom level
- [ ] Color of Pins and rivers are similar, fix by taking brigher blue for water
- [ ] Orange color of streets and action buttons too similar

**Comment by j0hj0h** [comment]
- [ ] disable country popover and click on street level

**Comment by literarymachine** [comment]
- [ ] add country borders to street layer

**Comment by literarymachine** [comment]
On https://beta.oerworldmap.org/

**Comment by karindr** [comment]
- Country’s names not in uppercase letters and/or smaller font. Now there is too much emphasis on the names in my opinion. The distinction to city names better by colour/darkness or font size.
- Maybe first view of the world map without names? We should have a good looking home page. Heat map and pins respectively numbers are the relevant information and look good on production.
- “Bundesland”-borders are missing at the moment. Maybe display them in the zoom level when the first cities appear (which is good) before the steers appear.
- Points for cities better also blue not black. I think it would be helpful to have more classes of cities shown in different ways, e.g. by different font size and maybe different sized points. At the moment the cities look a bit ‘random’ in some views:
![image](https://cloud.githubusercontent.com/assets/18674205/18628361/244584d2-7e60-11e6-8c54-8c1e02fd77a1.png)

- In my opinion themap should change later to the street level.
- The lighter blue for the rivers looks good. Maybe yet a little bit lighter.
- Is there no information in the map data to prevent rivers from getting interrupted? Other maps look better at this point, maybe also because there is background colour for cities, forests and so on. Could we also display some background colour? 
- Shouldn’t points for cities disappear at the zoom level when so much streets are shown, that the cities can be localized by seeing a lot of streets? See this zoom level below. Also there could me more names for villages at this level. See:
![image](https://cloud.githubusercontent.com/assets/18674205/18628448/919b6100-7e60-11e6-8efe-0843e90d4c85.png)

- Names for roads should not be displayed at this level (see below), exception maybe numbers for highways and so on. The street names below in Baden look strange. First road names should be displayed many zoom levels later. Then there could be more names at the same time (the classification is not intuitive to the user).
![image](https://cloud.githubusercontent.com/assets/18674205/18628462/a25ac468-7e60-11e6-972e-d7e22d3cdf1f.png)
  
- In Cologne the Zoobrücke and the “Stadtautobahn” are missing as streets, only the labels are displayed. These mayor roads seems to be in a still missing class of roads, kind of “Autobahnen” but not officially. See below:
![image](https://cloud.githubusercontent.com/assets/18674205/18628478/b13f8ce8-7e60-11e6-85b6-4365527679ec.png)
  
-

**Comment by trugwaldsaenger** [comment]
Very cool, great work!
It seems to be working quite well on beta. I found two issues till now:

1. The mouseover is not woking any longer, as soon as you get to the street layer
1. The pins are still hard to find. To improve this I would encourage to

a) Make the pins a bit bigger
b) Change color of black points for cities into light grey
![blackpoints](https://cloud.githubusercontent.com/assets/6639965/18628492/c1c3fc84-7e60-11e6-9fc7-6801bc6332c4.JPG)

**Comment by literarymachine** [comment]
In general, please note that we will not get things perfectly right at this point, and there will even be some bugs like borders not perfectly aligning. This is due to the fact that our map data comes from to separate sources at the moment; if we want everything fixed before updating production, it will take a while because it involves some major refactoring of the underlying map code. I would say we live with some imperfection it for now and focus on improving the map, not making it perfect. Here are some things I tried to fix by myself on https://beta.oerworldmap.org/. The question is if it is enough before @j0hj0h and @formimkontext can take another look by KW 41.

> Country’s names not in uppercase letters and/or smaller font. Now there is too much emphasis on the names in my opinion. The distinction to city names better by colour/darkness or font size.

This did not work very well when we tried.

> Maybe first view of the world map without names? We should have a good looking home page. Heat map and pins respectively numbers are the relevant information and look good on production.

Country names are now displayed later.

> “Bundesland”-borders are missing at the moment. Maybe display them in the zoom level when the first cities appear (which is good) before the steers appear.

Done.

> Points for cities better also blue not black. I think it would be helpful to have more classes of cities shown in different ways, e.g. by different font size and maybe different sized points. At the moment the cities look a bit ‘random’ in some views.

We have three different classes now.

> In my opinion themap should change later to the street level.

If we do this, cities will look even more random.

> Is there no information in the map data to prevent rivers from getting interrupted? Other maps look better at this point, maybe also because there is background colour for cities, forests and so on. Could we also display some background colour?

Styling a map as perfectly as e.g. Google Maps will require much more detail work. Our first tries with background colors did not work out very well.

> Shouldn’t points for cities disappear at the zoom level when so much streets are shown, that the cities can be localized by seeing a lot of streets?

Done.

> First road names should be displayed many zoom levels later. Then there could be more names at the same time (the classification is not intuitive to the user).

Done.

> In Cologne the Zoobrücke and the “Stadtautobahn” are missing as streets, only the labels are displayed. These mayor roads seems to be in a still missing class of roads, kind of “Autobahnen” but not officially.

Indeed there was a classification named `trunk` in mapbox missing!

**Comment by literarymachine** [comment]
> The mouseover is not woking any longer, as soon as you get to the street layer

This was removed on purpose; should we bring it back? I believe at street level, the popover only adds noise.

> The pins are still hard to find. To improve this I would encourage to
a) Make the pins a bit bigger
b) Change color of black points for cities into light grey

Color of the cities changed, from my perspective this actually helps a lot without resizing the pins.

**Comment by trugwaldsaenger** [comment]
As far as the mouseover is concerned, I would activate it again. If you zoom into a big city like e.g. Hamburg, you can get a screen, where many pins are displayed. Using the mouseover you could easily find the one you are interested in. At the moment you have to click on each of them to see, what is behind it.

> Color of the cities changed, from my perspective this actually helps a lot without resizing the pins.
+1 much better now!

**Comment by trugwaldsaenger** [comment]
>  I would say we live with some imperfection for now and focus on improving the map, not making it perfect.
+1, that is, what we discussed in Milton Keynes! We will have (and maybe even need) years to make the map perfect!

**Comment by trugwaldsaenger** [comment]
One interestig aspect: I noticed, that railroad information is missing. In Cologne therefore also the "Hohenzollernbrücke" is not displayed. Did you experiment with this?

**Comment by literarymachine** [comment]
> As far as the mouseover is concerned, I would activate it again. If you zoom into a big city like e.g. Hamburg, you can get a screen, where many pins are displayed. Using the mouseover you could easily find the one you are interested in. At the moment you have to click on each of them to see, what is behind it.

Ah, sorry! I meant to only disable the country popover, not the ones for the pins of course. Brought them back!

> One interestig aspect: I noticed, that railroad information is missing. In Cologne therefore also the "Hohenzollernbrücke" is not displayed. Did you experiment with this?

Added them, not sure about the greenish color but should do for now!?

**Comment by trugwaldsaenger** [comment]
I think we have achieved enough to bring it to production. Ready for deploy!
