### ISSUE TITLE
Add subnational divisions to country views

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#810]
When viewing an individual country, internal first-order administrative boundaries (e.g. German "Bundesländer") should be displayed and used for the heat map.

**Comment by literarymachine** [comment]
Interestingly, we do not have any issues related to subnation divisions so far although this is a major milestone on or road map. @trugwaldsaenger, @karindr et al, feel free to specify requirements further here.

**Comment by karindr** [comment]
(I know this issue is postponed, but comments won’t get lost.) I like the way the first-order administrative boundaries are shown in the WM on production. They give orientation in big countries and when you have zoomed into countries. I think it would be a good feature for the visitors to be able to change the heat map from displaying countries to display the different counties, Bundesländer or whatever. But in my opinion it would be irritating if the heat map changes automatically with the changing of the zoom level.

**Comment by literarymachine** [comment]
> But in my opinion it would be irritating if the heat map changes automatically with the changing of the zoom level.

@trugwaldsaenger, @j0hj0h and I discussed the idea that not zooming, but actually clicking on a country (thus entering "country view") could switch to the first-order administrative boundaries heat map.

**Comment by philboeselager** [comment]
Just as a side note: in the current version, the subnational boarders (e. g. in Germany) disappear when zooming in "too far".

**Comment by literarymachine** [comment]
> @trugwaldsaenger, @j0hj0h and I discussed the idea that not zooming, but actually clicking on a country (thus entering "country view") could switch to the first-order administrative boundaries heat map.

Fixed on production, also see #1484.
