### ISSUE TITLE
Add 'sign up to OER World Map' to the 'How do I contribute?' page

### ISSUE THREAD

**Issue by drrobertfarrow** [hbz/oerworldmap#839]
The page at https://oerworldmap.org/contribute provides several options for becoming involved with the project except without perhaps the most important one:  join the mailing list and sign up for the project.

https://oerworldmap.org/contribute

**Comment by karindr** [comment]
I agree below "Spread the news" there should be a point "Register to the map and create your profile".

Because the newsletter is relatively prominent with the orange button on the map, in my opinion it is not necessary to mention this possibility her. Especially because you don't contribute by getting a newsletter.
