### ISSUE TITLE
Restructure Operators & Participants for projects

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#941]
After discussion with @acka47 we aggreed to distinguish more clearly between the operating organization(s) and the team members for projects. In order to do so the operators & participants fields should be changed as following:

1. The field "operator" stayes as it is. This field includes the organization (or person), which drives the project. It will continue to be open for organizations as well as for persons. The mouse-over help in the input template could be supplemented as following: "The agent(s) driving the project. _This will usually be an institution but might be a person in case of bottom-up organized projects_".

2. The field "participant" changes its name into "partner". It remains to be open for organizations and persons. The mouse-over help in the imput template could be supplemented as following. "The co-agent(s) _(usually organizations)_ participating in the project".

3. Include a new field "affiliation". This field will include the team members. The field should be filled by the "affiliation field" within a personal profil. This has to be changed, so that a person can become an affiliate of an organization, of an service as well as of an project.

**Comment by acka47** [comment]
For the json schema this basically means adding "Action" as possible type for the "memberOf" property of a person.

**Comment by literarymachine** [comment]
> For the json schema this basically means adding "Action" as possible type for the "memberOf" property of a person.

Are you sure? Shouldn't `Action` be a possible type for the `affiliation` property, as introduced in https://github.com/hbz/oerworldmap/issues/942#issue-190741233?

**Comment by acka47** [comment]
We will use the `memberOf` property and might label the field "affiliation" in the UI. See also #367 for the general decision to only use the super-property `memberOf` to hold the overall number of properties down.

**Comment by literarymachine** [comment]
Hmm. I just implemented it the other way; please clarify with @trugwaldsaenger.

> This has to be changed, so that a person can become an affiliate of an organization, of an service as well as of an project.

because this is conjunction with

> Currently the organizations profile does not distinguish between "members" (=organizations) and "affiliates" (=persons). https://github.com/hbz/oerworldmap/issues/942#issue-190741233

had me understand it this way.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:43526b28-66f8-49bb-bf1c-c3cb8d4bbbcd

**Comment by acka47** [comment]
As already discussed with @literarymachine on the phone and as written in https://github.com/hbz/oerworldmap/issues/941#issuecomment-262916792 and https://github.com/hbz/oerworldmap/issues/941#issuecomment-267069777 I had something else in mind on the data model side. Taking a  look at this again, I agree with @literarymachine that using the `memberOf` field wouldn't suffice and an `affiliation`/`affiliate` property is actually needed here. 

Generally, I have the feeling we could win if we stopped defining relationships narrowly in the data model as well as adding new fields to cover new cases (`agent`/"operator", `member`/"partner" and `affiliate`/"affiliates" etc.). We will always have cases where our data model won't fit. Instead we could record a general "member" relation and let people type in a "role" to specify this membership. This is actually supported by schema.org and I already mentioned it in https://github.com/hbz/oerworldmap/issues/954#issuecomment-263026294. Basically this means adding a level of indirection that let's us specify a `member`/`memberOf` relation, e.g. like so:

```json
{
   "@id":"urn:uuid:43526b28-66f8-49bb-bf1c-c3cb8d4bbbcd",
   "member":[
      {
         "@type":"Role",
         "roleName":"Project Lead",
         "member":{
            "@type":"Person",
            "name":[
               {
                  "@value":"Jan Neumann",
                  "@language":"en"
               }
            ],
            "@id":"urn:uuid:839897e6-178f-11e5-871b-3c970e4a9cbf"
         }
      }
   ]
}
```

For the UI it actually is much easier to implement and we could use the role information given by the editor as field name. (See this [draft](https://github.com/lobid/lobid.github.com/blob/nwbib-362/_posts/2016-12-13-data-modeling-client-effects.md) by @fsteeg for UI implementation of a similar approach.)

Form the implementation and UI side this approach may have a lot of advantages. One disadvantage might be that we can not make very specific queries as the labels editors choose for a role will very and we can rather query for general member/memberOf relations. We have to ask ourselves what we want here.

@literarymachine, I hope I am not bugging you bringing this up but it was on my mind for quite some time since I read that schema.org actually supports this and I think we should keep this in mind, when further additions of relationships are discussed.

**Comment by acka47** [comment]
I conflated two things in my previous post that should be kept apart.

1. Using an intermediate role for recording isPartOf/memberOf relations between two entities.
2. Giving user the possibility to specify the roles themselves by typing in role names.

1.) can already be useful from the software side even if we stick to predefined types of relations (like we do in lobid/NWBib). 2.) is a way to let user decide which roles they define. I am not sure about this. It could be problematic approach especially with the prospect of internationalization for the site.

**Comment by literarymachine** [comment]
> 1.) can already be useful from the software side even if we stick to predefined types of relations

I don't really see the advantage here. Isn't this basically the same as specifying `:role rdf:subPropertyOf :memberOf`? Using sub properties also has the advantage that we don't introduce a *lot* of additional (blank) nodes. Plus I think that the JSON, but even more so the RDF would be much harder to parse by a human.

> 2.) is a way to let user decide which roles they define. I am not sure about this. It could be problematic approach especially with the prospect of internationalization for the site.

If we want to use specified roles, the intermediate role approach indeed seems to be the only feasible way. But this has to be well thought through; even if it wasn't for internationalization. The roles would be strings, not things.

**Comment by literarymachine** [comment]
For now, I would stick with the `affiliation` as deployed to beta. Ok to deploy and move this discussion somewhere else?

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
> Isn't this basically the same as specifying `:role rdf:subPropertyOf :memberOf`? 

No, there is no `role` property but only an intermediary node with type `Role`.

> Using sub properties also has the advantage that we don't introduce a *lot* of additional (blank) nodes. 

That's right.

> Plus I think that the JSON, but even more so the RDF would be much harder to parse by a human.

As you know, I think our JSON is already not really to be parsed by humans.

**Comment by literarymachine** [comment]
> No, there is no role property but only an intermediary node with type Role.

I know. You're approach:

    :organization :member [a :Role; :roleName "predefinedRoleName"; :member :person]

As long as role names are predefined though, I think this is basically (as in: same semantics) the same as

    :organization :predefinedRole :person .
    :predefinedRole rdfs:subPropertyOf :member .

The latter would of course only have to be specified once.

**Comment by literarymachine** [comment]
@acka47 just explained offline what I missed in https://github.com/hbz/oerworldmap/issues/954#issuecomment-263026294. The reification of the role allows to add data beyond the specific role; e.g.

```
:organization :member [
  a :Role ;
  :roleName "Software Developer ;
  :startDate "2008" ;
  :endDate "2010" ;
  :member :person
]
```

This is not possible with the `rdfs:subPropertyOf` approach which is limited to narrowing down the type of relation.
