### ISSUE TITLE
Rework SEO/meta-data concept

### ISSUE THREAD

**Issue by j0hj0h** [hbz/oerworldmap#962]
For SEO and to improve snippet appearance of worldmap links:
- resource title -> title-tag
- other title-tags
- meta-description
- open graph meta tags (e.g. logo as image)
- evaluate http://oembed.com
- alternates (csv, json, iCal)

**Comment by j0hj0h** [comment]
We agreed on the following meta data:

* Landingpage:
    * `<title>`: Navigate the world of OER! / OER World Map
    * `og:title`: Navigate the world of OER!
    * `og:image`: large, designed by felix
    * `og:description`, `<meta>`-description: The goal of the OER World Map is to illuminate the global Open Educational Resources movement by facilitating interaction and collaboration.
* other static:
    * `<title>` & `og:title`: About / OER World Map
    * `og:image`: none (or a square logo image)
    * `og:description`, `<meta>`-description: first one to two sentences (if possible)
* search-results:
    * `<title>` & `og:title`:
        * Results for „…“ / OER World Map 
        * Organizations, Services, … / OER World Map
    * `og:image`: small, map with placemarks, designed by felix
    * `og:description`, `<meta>`-description: Discover the OER movement
* countryview:
    * `<title>` & `og:title`: Sweden, … / OER World Map
    * `og:image`: none (or static mapbox image from the country, if not to much work)
    * `og:description`, `<meta>`-description: Discover the OER movement in Sweden!
* single resource:
    * `<title>`: name of resource / OER World Map
    * `og:title`: name of resource
    * `og:image`: logo (in sqaure format) or none
    * `og:description`, `<meta>`-description: one or to two sentences from description

**Comment by j0hj0h** [comment]
Also see:
https://github.com/hbz/oerworldmap/issues/1515
https://github.com/hbz/oerworldmap/issues/1354
https://github.com/hbz/oerworldmap/issues/1112

**Comment by formimkontext** [comment]
what about using details of the colorplath map for facebook posts? so we won’t favour any country or region and get some nice images. maybe something like this:

![oerworldmap-facebook-250x250](https://user-images.githubusercontent.com/15141949/39822701-863cde66-53ab-11e8-84d4-1d066a9a8b51.png)
![oerworldmap-facebook-1200x628-2](https://user-images.githubusercontent.com/15141949/39822702-865862a8-53ab-11e8-91ac-e7ceb9648605.png)

**Comment by karindr** [comment]
In what cases would these details be shown?

**Comment by formimkontext** [comment]
we decided to show those images for sharing on facebook and twitter: 
![oerworldmap_opengraph_400x400](https://user-images.githubusercontent.com/15141949/40372648-6d9409e0-5de5-11e8-92e5-42d4fe8dbca1.png)
![oerworldmap_opengraph_1200x630](https://user-images.githubusercontent.com/15141949/40372649-6dcaf05e-5de5-11e8-8c82-a5f299826987.png)

**Comment by karindr** [comment]
When are we going to see these both pictures used on twitter and facebook?

**Comment by literarymachine** [comment]
> When are we going to see these both pictures used on twitter and facebook?

Now that https://github.com/hbz/oerworldmap-ui/pull/321 has been deployed.

**Comment by dobladov** [comment]
These are screenshots showing how the Facebook and Twitter previews looks

Main view without any search or filter https://oerworldmap.org/resource/
This is also the view for resources without image or with an invalid image

![main](https://user-images.githubusercontent.com/1938043/41242663-6b6f369c-6da0-11e8-9d2e-aa27abffcaa2.png)
![resourecetw](https://user-images.githubusercontent.com/1938043/41242666-6e430eb6-6da0-11e8-865c-3624bb5ac3c7.png)

With a filter or search https://oerworldmap.org/resource/?q=oer&filter.about.%40type=Organization&size=20

![filter](https://user-images.githubusercontent.com/1938043/41242773-b45c3594-6da0-11e8-988d-618e31262731.png)
![filtertw](https://user-images.githubusercontent.com/1938043/41242775-b5ae5a44-6da0-11e8-84d0-a098b0cfba16.png)

Country view: https://oerworldmap.org/country/de
![countrytw](https://user-images.githubusercontent.com/1938043/41242549-236edd34-6da0-11e8-92a2-42f68833d6b7.png)
![country](https://user-images.githubusercontent.com/1938043/41242550-25054174-6da0-11e8-9c9c-e86979c75395.png)

Resource with a valid picture https://oerworldmap.org/resource/urn%3Auuid%3A4a15dd14-2fbb-11e5-9571-001999ac7927

![reswithimg](https://user-images.githubusercontent.com/1938043/41242833-df59da4e-6da0-11e8-936f-5936afb649fd.png)
![resourcetw](https://user-images.githubusercontent.com/1938043/41242841-e4eef08e-6da0-11e8-8028-e4a7d4eba884.png)

**Comment by karindr** [comment]
Thanks for the pictures from the different views. This makes very clear what will be shown in what case! I think the first ones with the picture created by Felix and the last ones using the images will work very well on twitter and facebook. 

But I see some problems with the preview for the country views. As I said an empty map is in my opinion worse than no map because it contradicts the expectations of the users: The text says “Discover …” and on the little map there is no sign of anything to discover only the well-known frontiers of the country. I would suggest to use the picture from above also for the country view.

**Comment by karindr** [comment]
There is a strange case happening in the twitter window on our blog: when retweeting a tweet with a comment including a link to the OER World Map the peview picture of the OER World Map is shown here as if it belongs to text of the retweeted tweet (also the link to oerworldmap is shown instead of both links). 
![image](https://user-images.githubusercontent.com/18674205/41654530-08b51c10-748a-11e8-926b-0e2d04aaf979.png)
It only happens in the blog, not on twitter itself, see:
https://twitter.com/oerworldmap/status/1008975262812459009

Has anybody a clue if there is a possibility to prevent this? (And yes I know that I could stop making such tweets but there are good reasons for doing so.) If not it is not so important because it only happens in the blog.
