### ISSUE TITLE
Highlight resource from detail column in list

### ISSUE THREAD

**Issue by j0hj0h** [hbz/oerworldmap#975]
Show visual connection between resource in detail column and list entry.

**Comment by formimkontext** [comment]
I recommend to mark the list entry with a darker blue in the background (see some older draft below) or to display text and icon orange. it is not only about showing the connection between resource and list entry but also to highlight the list entry in order to recognize it while you scroll through the list. 

maybe the second is the better solution since it works for calendar list, too.

![20160307-oer-world-map-aggregation resource-3](https://cloud.githubusercontent.com/assets/15141949/21261146/f2d46c6e-c389-11e6-8348-57710e0f893b.jpg)

**Comment by karindr** [comment]
This is a good thing.
> display text and icon orange
I would prefer this, the highlighted pin is also in orange.

**Comment by dobladov** [comment]
Outdated with the new UI, closing.
